- controls/cf_serverd.cf
With cfengine/core@4d67db312b1b9 the default is ::/0.0.0.0
instead of just 0.0.0.0 so the explicit value of :: is not needed
and can be dropped to resolve issues on hosts that don't have
working IPV6 and only try to bind to :: if that's the explicit
value.
Ticket: ENT-7362
Changelog: controls/cf_serverd.cf no longer specifies explicit
default for bindtointerface and relies on the default
binding to both :: and 0.0.0.0 on IPV6-enabled hosts
https://github.com/cfengine/core/pull/4750
https://github.com/cfengine/masterfiles/pull/2041
> Comment-out the default bindtointerface specification

- controls/cf_serverd.cf
With cfengine/core@4d67db312b1b9 the default is ::/0.0.0.0
instead of just 0.0.0.0 so the explicit value of :: is not needed
and can be dropped to resolve issues on hosts that don't have
working IPV6 and only try to bind to :: if that's the explicit
value.
Ticket: ENT-7362
Changelog: controls/cf_serverd.cf no longer specifies explicit
default for bindtointerface and relies on the default
binding to both :: and 0.0.0.0 on IPV6-enabled hosts
(cherry picked from commit 60f92f7ed441e4123f03d44b5d6e7fcbfb2e872d)
https://github.com/cfengine/core/pull/4756
https://github.com/cfengine/masterfiles/pull/2046
> [3.18.x] Comment-out the default bindtointerface specification

- modules/packages/vendored/msiexec-list.vbs.mustache
Windows software is like the wild west. This change tries to fall back to
InstalledVersion if DisplayVersion is not defined in the registry, if that
fails, it falls back trying to look for keys named the same as the software
itself which while not correct, was seen in the wild for at least one piece of
software.
Ticket: ENT-7501
> ENT-7501: Added fallback logic for determining installed software version on Windows

- modules/packages/vendored/msiexec-list.vbs.mustache
Windows software is like the wild west. This change tries to fall back to
InstalledVersion if DisplayVersion is not defined in the registry, if that
fails, it falls back trying to look for keys named the same as the software
itself which while not correct, was seen in the wild for at least one piece of
software.
Ticket: ENT-7501
(cherry picked from commit 6140be60a049d5ba762bbf4ea3fb2b135d4dd9f0)
> ENT-7501: Added fallback logic for determining installed software version on Windows (3.18)

- modules/packages/vendored/msiexec-list.vbs.mustache
Windows software is like the wild west. This change tries to fall back to
InstalledVersion if DisplayVersion is not defined in the registry, if that
fails, it falls back trying to look for keys named the same as the software
itself which while not correct, was seen in the wild for at least one piece of
software.
Ticket: ENT-7501
(cherry picked from commit 6140be60a049d5ba762bbf4ea3fb2b135d4dd9f0)
> ENT-7501: Added fallback logic for determining installed software version on Windows (3.15.x)

- cfe_internal/update/update_policy.cf
Ticket: CFE-3721
(cherry picked from commit e1117eb03d611b2335d4a398364dd249940c4aba)
> CFE-3721 Skip ownership of package modules on termux (3.18.x)

- modules/packages/vendored/apt_get.mustache
Prior to this change packages promises using the apt_get package module would
use dpkg to handle the case when the path to a package was the promiser. dpkg
does not resolve dependencies, so the result could be a half installed package,
or a package installed with unmet dependencies leaving it in a nonfunctional
state.
This change switches to using apt-get to install the package from a local file,
with apt-get, dependencies are automatically resolved and would be installed
from repositories if available.
Ticket: CFE-3724
> CFE-3724: apt_get package module fails to fully install packages from local files

- MPF.md
- lib/autorun.cf
- promises.cf.in
The class services_autorun continues to enable both automatic inclusion of .cf
files in services/autorun and the running of bundles tagged with autorun.
This change adds the classes services_autorun_inputs and
services_autorun_bundles for independently enabling addition of .cf files in
services/autorun and automatic execution of bundles tagged with autorun
respectively.
Ticket: CFE-3715
(cherry picked from commit 01850824a48c32ce43dce614ef4935b175f32f34)
> CFE-3715: Added separate classes for controlling autorun inputs and bundles (3.18)

- tests/unit/test_package_module_apt_get
Recently switched to using apt_get instead of dpkg for local file installs so
that dependencies would be resolved automatically, and so that the behavior was
more in line with user expectations without having to read something.
> Fixed mock test for apt_get package module

- modules/packages/vendored/apt_get.mustache
- tests/unit/test_package_module_apt_get
Prior to this change packages promises using the apt_get package module would
use dpkg to handle the case when the path to a package was the promiser. dpkg
does not resolve dependencies, so the result could be a half installed package,
or a package installed with unmet dependencies leaving it in a nonfunctional
state.
This change switches to using apt-get to install the package from a local file,
with apt-get, dependencies are automatically resolved and would be installed
from repositories if available.
Ticket: CFE-3724
(cherry picked from commit fb147024136eb16bc8eac209e1dae2121a4123c3)
> CFE-3724: apt_get package module now uses apt-get for file based installs instead of dpkg (3.15)

- cfe_internal/enterprise/CFE_hub_specific.cf
> ENT-7465: Insured exported reports from Mission Portal are in the correct location

- modules/packages/vendored/apt_get.mustache
- tests/unit/test_package_module_apt_get
Unfortunately, there seems to be a race condition between apt-get
and dpkg and in some cases (incl. out test cases), apt-get thinks
different packages (or versions) are installed.
This reverts commit e5e7e524f211babd0a2fbcc1761817c6d9d3fecd.
This reverts commit 60b6a8f2ca650d13b8bde00b20dfddf9e2c4eef1.
This reverts commit fb147024136eb16bc8eac209e1dae2121a4123c3.
> ENT-7508: Revert "apt_get package module now uses apt-get for file based installs instead of dpkg"

- cfe_internal/enterprise/CFE_hub_specific.cf
Ticket: ENT-7465
(cherry picked from commit af35c4f7a434b3a55f5e60de3ae5b83bdcad459b)
> ENT-7465 Ensured exported reports from Mission Portal are in the correct location (3.18)

- cfe_internal/enterprise/CFE_hub_specific.cf
Ticket: ENT-7465
(cherry picked from commit af35c4f7a434b3a55f5e60de3ae5b83bdcad459b)
> ENT-7465: Ensured exported reports from Mission Portal are in the correct location (3.15)

- lib/services.cf
This change restores 71cb6946b2e45c3466f45c0be29cd377508b22ec from CFE-290 which
limits the scope of the report to cases when the desire is to have the service
functioning. When the desire is to have a service not function, a missing
service fufills this desire. Only in the case of desiring a functional service
does is a missing service problematic.
Ticket: ENT-7360
> ENT-7360: Reduced scope of report informing of missing systemd service

- lib/services.cf
This change restores 71cb6946b2e45c3466f45c0be29cd377508b22ec from CFE-290 which
limits the scope of the report to cases when the desire is to have the service
functioning. When the desire is to have a service not function, a missing
service fufills this desire. Only in the case of desiring a functional service
does is a missing service problematic.
Ticket: ENT-7360
(cherry picked from commit d6c81d5f922dba7f746840a6d654562afd135b4a)
> ENT-7360: Reduced scope of report informing of missing systemd service (3.18)

- inventory/any.cf
Now that the windows package module is used by default we can stop using the
legacy packages promise to generate software inventory. Furthermore, this change
should prevent log spam generated by MsiInstaller in the default policy which
was generated for each piece of software found as a result of the use of the
Win32_Product class.
Ticket: ENT-2589
> ENT-2589: Switched from using package_method generic to default package_module for windows software inventory

- inventory/any.cf
Now that the windows package module is used by default we can stop using the
legacy packages promise to generate software inventory. Furthermore, this change
should prevent log spam generated by MsiInstaller in the default policy which
was generated for each piece of software found as a result of the use of the
Win32_Product class.
Ticket: ENT-2589
(cherry picked from commit d2fb4fb0679739eefa200e1fb66a0dd670b161ef)
> ENT-2589: Switched from using package_method generic to default package_module for windows software inventory (3.18)

- lib/services.cf
The state of a particular systemd service can change during the
agent run, either by external actions or even by actions done by
the agent itself. For this reason, the 'systemd_service_info'
variable holding the information about a state of a system
service needs to be refreshed for every 'services' promise.
Only versions of cf-agent greater than or equal to 3.18.1 support
'ifelapsed => "0"' disabling function caching, older versions
produce a warning for 'vars' promises using 'ifelapsed'.
Ticket: CFE-3753
Changelog: State changes of systemd services during agent run are now properly registered
> Make sure systemd service info is always fresh

- README.md
> ENT-7627: Changed IRC channel reference from freenode to libera.chat

- README.md
Ticket: ENT-7627
(cherry picked from commit b0ead81d95da3a1a4d60c4622abc36a447f61477)
> ENT-7627: Changed IRC channel reference from freenode to libera.chat (3.15)

- tests/acceptance/30_custom_promise_types/11_handle.cf
Just making sure the '$(this.handle)' expression is properly
expanded to the value of the attribute.
Ticket: CFE-3439
https://github.com/cfengine/core/pull/4795
https://github.com/cfengine/masterfiles/pull/2087
> Add a test for a custom promise using the 'handle' attribute

- tests/acceptance/30_custom_promise_types/11_handle.cf
Just making sure the '$(this.handle)' expression is properly
expanded to the value of the attribute.
Ticket: CFE-3439
(cherry picked from commit 63881fa89fa8de7123081465715626202b9ee8e9)
> [3.18.x] Add a test for a custom promise using the 'handle' attribute

- inventory/README.md
Merge with:
- https://github.com/cfengine/documentation/pull/2530
Ticket: ENT-7573
> ENT-7573: Corrected link target for Promise Types documentation

- inventory/README.md
Ticket: ENT-7573
(cherry picked from commit b4c42afdffb1849cdfe110826adde60f1357c24f)
> ENT-7573: Corrected link target for Promise Types documentation (3.18)

- inventory/README.md
Ticket: ENT-7573
(cherry picked from commit b4c42afdffb1849cdfe110826adde60f1357c24f)
> ENT-7573: Corrected link target for Promise Types documentation (3.15)

- inventory/redhat.cf
This change improves the reliability when detecting a Red Hat system.
- Now if the ID field in `/etc/os-release` is set to `rhel`, the `redhat_pure` class
will be defined.
- If the variable `sys.os_release` does not exist, `redhat_pure` is defined if we have already
defined `redhat` and we do not find classes for well known derivatives
- rocky, a class defined on Rocky Linux was added to the list of well known derivatives
- `almalinux`, a class defined on AlmaLinux was added to the list of well known derivatives
Tickets: ENT-7628, ENT7644
Changelog: Ticket
> ENT-7628: Improved detection of pure Red Hat

- MPF.md
Ticket: CFE-3775
(cherry picked from commit 67a8bf15da8d217fbfc1545b46eed83b10251348)
> CFE-3775: Added cross reference to packagesmatching functions from MPF tunables (3.18)

- tests/acceptance/lib/files/append_user_field.cf
- tests/acceptance/lib/files/append_user_field.cf.finish
- tests/acceptance/lib/files/append_user_field.cf.start
The implementation in this bundle from the standard library triggers a bug that
prevents datastate() from being reported. We should have a test before we go
changing the implementation of the standard library, so here it is.
Ticket: CFE-3776
> CFE-3776: Added test for bundle edit_line append_user_field

- lib/files.cf
The use of this local variable triggers a bug that prevents datastate() from
printing. Since the variable is un-necessary, it's been removed and the
parameter is used directly.
Ticket: CFE-3776
> CFE-3776: Dropped un-necessary local variable

- lib/autorun.cf
Previously, when the autorun feature was enabled to automatically run bundles
tagged with autorun the bundle actuation was affected by promise locking. The
effect of this is that agent runs that happen close together would skip running
bundles run within the last minute. Now autorun bundles no longer wait for a
lock to expire, they will be actuated each agent execution. Note, promises
within those bundles have their own locks which still apply.
Ticket: CFE-3795
Changelog: commit
(cherry picked from commit 58d8b14953ff0b3c0fcb3c778cf8a4cb2007bd23)
> CFE-3795: Autorun bundles now run regardless of locks (3.15)

- inventory/any.cf
In dmidecode 2.11 larger memory devices started being reported in GB units
instead of only MB. This change handles that case by converting GB to MB when
found.
Ticket: ENT-7714
(cherry picked from commit 0e0de9ac8a303938cd57c1f5772b1ce29a2c0b75)
> ENT-7714: Physical Memory (MB) inventory now handles dmidecode MB or GB units (3.18)

- Makefile.am
- configure.ac
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
- tests/acceptance/testall
- tests/unit/test_package_module_apt_get
- tests/unit/test_package_module_yum
Instead of creating files from .mustache templates
just copy them over in the tests where they are needed:
tests/unit/test_package_module_apt_get
tests/unit/test_package_module_yum
Ticket: ENT-7359
> ENT-7359 Removed build dir from install/dist targets

- tests/acceptance/30_custom_promise_types/21_with_attribute.cf
Dependent on: https://github.com/cfengine/core/pull/4842
Ticket: CFE-3441
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
> CFE-3441: Test using attribute `with` with custom promise types

- Makefile.am
- configure.ac
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
- tests/acceptance/testall
- tests/unit/test_package_module_apt_get
- tests/unit/test_package_module_yum
Instead of creating files from .mustache templates
just copy them over in the tests where they are needed:
Ticket: ENT-7359
(cherry picked from commit 74dd96135f4666c71d734d02830443915b1c6c0b)
> ENT-7359 Removed build dir from install/dist targets (3.18)

- Makefile.am
- configure.ac
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
- tests/acceptance/testall
- tests/unit/test_package_module_apt_get
- tests/unit/test_package_module_yum
Instead of creating files from .mustache templates
just copy them over in the tests where they are needed:
Ticket: ENT-7359
(cherry picked from commit 74dd96135f4666c71d734d02830443915b1c6c0b)
> ENT-7359 Removed build dir from install/dist targets (3.15)

- tests/acceptance/30_custom_promise_types/21_with_attribute.cf
Ticket: CFE-3441
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 7ae6d5c2f478a88cb7b26ce95ac6a8c1202588e0)
> CFE-3441: Test using attribute `with` with custom promise types (3.18.x)

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that both Mission Portal and Apache log files have
restrictive permissions. Previously this was un-managed.
Ticket: ENT-7730
> ENT-7730: Promised permissions for Mission Portal application and Apache log files

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that both Mission Portal and Apache log files have
restrictive permissions. Previously this was un-managed.
Ticket: ENT-7730
(cherry picked from commit 30bb82c7f8f75f3a5d3851ea7e1ef2a04feed9a1)
> ENT-7730: Promised permissions for Mission Portal application and Apache log files (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that both Mission Portal and Apache log files have
restrictive permissions. Previously this was un-managed.
> ENT-7730: Promised permissions for Mission Portal application and Apache log files (3.15.x)

- cfe_internal/enterprise/federation/federation.cf
So that we get consistent data and avoid repairing a config JSON
just because the keys are in a different order.
Ticket: ENT-7967
Changelog: setup-status.json is no longer being repaired over and over on FR feeder hubs
> Sort output from ssh-keyscan in FR policy

- cfe_internal/enterprise/mission_portal.cf
Changing the apache configuration file can result in apache being unable to
stop/restart when the new config file is in place. Case in point, moving the
httpd.pid. If the config file has been updated, then apachectl will fail to find
a pid in the new loction, being unable to stop or restart.
This change carefully stops apache with the old config when there is a valid
config change and then starts it after the config has been moved into place.
Ticket: ENT-8045
> ENT-8045: Made apache restart more robust

- cfe_internal/enterprise/mission_portal.cf
Changing the apache configuration file can result in apache being unable to
stop/restart when the new config file is in place. Case in point, moving the
httpd.pid. If the config file has been updated, then apachectl will fail to find
a pid in the new loction, being unable to stop or restart.
This change carefully stops apache with the old config when there is a valid
config change and then starts it after the config has been moved into place.
Ticket: ENT-8045
(cherry picked from commit d1b3f70b4a3f67e51d84af33554e6aadb4d4b320)
> ENT-8045: Made apache restart more robust (3.15)

- cfe_internal/enterprise/mission_portal.cf
Changing the apache configuration file can result in apache being unable to
stop/restart when the new config file is in place. Case in point, moving the
httpd.pid. If the config file has been updated, then apachectl will fail to find
a pid in the new loction, being unable to stop or restart.
This change carefully stops apache with the old config when there is a valid
config change and then starts it after the config has been moved into place.
Ticket: ENT-8045
(cherry picked from commit d1b3f70b4a3f67e51d84af33554e6aadb4d4b320)
> ENT-8045: Made apache restart more robust (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
Policy Analyzer was not able to be enabled because
the flagfile could not be written due to policy which
prohibited write access to /var/cfengine/httpd/htdocs
for cfapache user/group.
Ticket: ENT-8065
merge together
https://github.com/cfengine/mission-portal/pull/1578
https://github.com/cfengine/masterfiles/pull/2168
https://github.com/cfengine/buildscripts/pull/908
> ENT-8065 Gave cfapache group full access to docroot

- cfe_internal/enterprise/CFE_knowledge.cf
Policy Analyzer was not able to be enabled because
the flagfile could not be written due to policy which
prohibited write access to /var/cfengine/httpd/htdocs
for cfapache user/group.
Ticket: ENT-8065
(cherry picked from commit a8e59558d9432a0608b5b1f9530728e193deffb1)
> ENT-8065: Gave cfapache group full access to docroot (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
Policy Analyzer was not able to be enabled because
the flagfile could not be written due to policy which
prohibited write access to /var/cfengine/httpd/htdocs
for cfapache user/group.
Ticket: ENT-8065
(cherry picked from commit a8e59558d9432a0608b5b1f9530728e193deffb1)
> ENT-8065: Gave cfapache group full access to docroot (3.15)

- inventory/README.md
The dynamic lookup failed, breaking doc builds. This change avoids the dynamic
lookup to make sure the docs build.
Ticket: ENT-8262
> ENT-8262: Added direct link to correct docs

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7698
(cherry picked from commit 7b7b75f02af3e9df0d8a5b525a86984f0a0d5e0d)
> Truncate FR dabase settings when a feeder is off (3.18.x)

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7698
(cherry picked from commit 7b7b75f02af3e9df0d8a5b525a86984f0a0d5e0d)
> Truncate FR dabase settings when a feeder is off (3.15.x)

- README.md
Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870
> ENT-7870 Remove inaccurate build badges

- README.md
Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870
(cherry picked from commit 0a4cffa32ddc2f0fbf844bf6aced62784a79d5d6)
> ENT-7870 Remove inaccurate build badges (3.18)

- README.md
Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870
(cherry picked from commit 0a4cffa32ddc2f0fbf844bf6aced62784a79d5d6)
> ENT-7870 Remove inaccurate build badges (3.15)

- .gitignore
- autogen.sh
- cfe_internal/update/update_bins.cf
- configure.ac
- controls/update_def.cf.in
- misc/determine-release.sh
- standalone_self_upgrade.cf.in
For self-update needs.
Current release number is taken from env variables, or detected from git
tags. If everything else fails, it defaults to '1' as before.
> Auto-detect current release and add it to policy

- standalone_self_upgrade.cf.in
This change adds the necessary mapping for an enterprise hub to download
packages to the appropriate location. Prior to this change the packages had to
be downloaded and placed manually.
Ticket: ENT-8283
> ENT-8283: Added support for downloading windows packages as part of self upgrade

- standalone_self_upgrade.cf.in
This change adds the necessary mapping for an enterprise hub to download
packages to the appropriate location. Prior to this change the packages had to
be downloaded and placed manually.
Ticket: ENT-8283
(cherry picked from commit bd2676e824c9cebbff01a34511821920a44289e5)
> ENT-8283: Added support for downloading windows packages as part of self upgrade (3.18)

- standalone_self_upgrade.cf.in
This change adds the necessary mapping for an enterprise hub to download
packages to the appropriate location. Prior to this change the packages had to
be downloaded and placed manually.
Ticket: ENT-8283
(cherry picked from commit bd2676e824c9cebbff01a34511821920a44289e5)
> ENT-8283: Added support for downloading windows packages as part of self upgrade (3.15)

- cfe_internal/update/windows_unattended_upgrade.cf
On some versions of windows escaping the space in the path to the script that
performs the upgrade from the script that schedules the upgrade. This change
uses "Here-strings" so that we can have matroska quotes.
This change also runs the script to schedule the upgrade with powershell
-NoProfile -ExecutionPolicy bypass -F path to schedule script because it was
observed to be necessary on some (but not all?) hosts. Probably related to some
other system setting that I just dunno (or care) about. Possibly, it's only
required for use when running on the command line interactively and is not
necessary to do from policy, but it works from policy to do it this way, so it
makes manual testing and investigation much easier.
Ticket: ENT-8066
> ENT-8066: Fixed windows unattended self upgrade on Windows 2008

- inventory/os.cf
Currently the core agent sets sys.os_name_human to RHEL on Rocky Linux. This
fixes the case for reporting inventory but a change in core is needed to address
the root issue.
Ticket: ENT-8292
> ENT-8292: Fixed inventory for OS on Rocky Linux

- inventory/os.cf
Currently the core agent sets sys.os_name_human to RHEL on Rocky Linux. This
fixes the case for reporting inventory but a change in core is needed to address
the root issue.
Ticket: ENT-8292
(cherry picked from commit 66d5107e657c65f660519e5b5f3e687428bf69cc)
> ENT-8292: Fixed inventory for OS on Rocky Linux (3.18)

- .no-distrib/README.md
- MPF.md
- cfe_internal/update/update_policy.cf
- controls/cf_serverd.cf
- https://github.com/cfengine/core/pull/4882
- https://github.com/cfengine/documentation/pull/2597
These changes to the MPF add .no-distrib as a directory that should not be copied as part of policy update so that cfbs modules could populate this directory with assets that should not be implicitly distributed but are not necessarily explicitly prohibited from distribution.
> ENT-8079: Plumbing in support of distributing compliance reports from cfbs modules

- standalone_self_upgrade.cf.in
Prior to this change Amazon Linux hosts (based on redhat|fedora) would not
attempt to upgrade themselves as they were not explicitly supported. With this
change hosts that have the amazon_linux class defined will use the same
methodology as redhat and centos hosts with respect to self upgrade.
> ENT-8274: Added support for Amazon Linux in standalone self upgrade

- .gitignore
- autogen.sh
- cfe_internal/update/update_bins.cf
- configure.ac
- controls/update_def.cf.in
- misc/determine-release.sh
- standalone_self_upgrade.cf.in
For self-update needs.
Current release number is taken from env variables, or detected from git
tags. If everything else fails, it defaults to '1' as before.
Ticket: ENT-4822
(cherry picked from commit 2ec642c0e66f9bbe2455b352b6cbb07a2c3f64b4)
> Auto-detect current release and add it to policy - 3.15.x

- .gitignore
- autogen.sh
- cfe_internal/update/update_bins.cf
- configure.ac
- controls/update_def.cf.in
- misc/determine-release.sh
- standalone_self_upgrade.cf.in
For self-update needs.
Current release number is taken from env variables, or detected from git
tags. If everything else fails, it defaults to '1' as before.
Ticket: ENT-4822
(cherry picked from commit 2ec642c0e66f9bbe2455b352b6cbb07a2c3f64b4)
> Auto-detect current release and add it to policy - 3.18.x

- cfe_internal/enterprise/federation/federation.cf
Check existence of tables and if present TRUNCATE them.
Ticket: ENT-8294
> ENT-8294 Only run clean_when_off FR bundle when needed (3.15)

- cfe_internal/enterprise/federation/federation.cf
Only on 3.15 and newer hubs when the remote_hubs and
federated_reporting_settings tables have rows in them.
Ticket: ENT-8294
(cherry picked from commit 85bdb768206a4a378889ffeb132e1a0cab8a6fda)
> ENT-8294 Only run clean_when_off FR bundle when needed (3.18)

- cfe_internal/enterprise/federation/federation.cf
Only on 3.15 and newer hubs when the remote_hubs and
federated_reporting_settings tables have rows in them.
Ticket: ENT-8294
(cherry picked from commit 85bdb768206a4a378889ffeb132e1a0cab8a6fda)
Conflicts:
cfe_internal/enterprise/federation/federation.cf
> ENT-8294 Only run clean_when_off FR bundle when needed (master)

- cfe_internal/update/windows_unattended_upgrade.cf
On some versions of windows escaping the space in the path to the script that
performs the upgrade from the script that schedules the upgrade. This change
uses "Here-strings" so that we can have matroska quotes.
This change also runs the script to schedule the upgrade with powershell
-NoProfile -ExecutionPolicy bypass -F path to schedule script because it was
observed to be necessary on some (but not all?) hosts. Probably related to some
other system setting that I just dunno (or care) about. Possibly, it's only
required for use when running on the command line interactively and is not
necessary to do from policy, but it works from policy to do it this way, so it
makes manual testing and investigation much easier.
Ticket: ENT-8066
(cherry picked from commit …
> ENT-8066: Fixed windows unattended self upgrade on Windows 2008 (3.18)

- tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
- tests/acceptance/30_custom_promise_types/append_promises.py
I.e. that elementary promise locking works, as implemented in
cfengine/core@24e2de71c749.
Ticket: CFE-3434
https://github.com/cfengine/core/pull/4905
https://github.com/cfengine/masterfiles/pull/2223
> Add a test that custom promises are only evaluated once in an agent run

- tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
- tests/acceptance/30_custom_promise_types/append_promises.py
I.e. that elementary promise locking works, as implemented in
cfengine/core@24e2de71c749.
Ticket: CFE-3434
(cherry picked from commit a3484a9b5ed034837cd8dfa279312bf357b21a92)
> [3.18.x] Add a test that custom promises are only evaluated once in an agent run

- tests/acceptance/30_custom_promise_types/22_single_evaluation.cf
It is supposed to be defined in the test on all versions, even on
those where the test is skipped.
> Make sure the 'test' bundle is defined in the 22_single_evaluation test

- standalone_self_upgrade.cf.in
Prior to this change Amazon Linux hosts (based on redhat|fedora) would not
attempt to upgrade themselves as they were not explicitly supported. With this
change hosts that have the amazon_linux class defined will use the same
methodology as redhat and centos hosts with respect to self upgrade.
Ticket: ENT-8274
(cherry picked from commit e4831d12046c5a9e470b2dce4612c34de3e1359d)
> ENT-8274: Added support for Amazon Linux in standalone self upgrade (3.18)

- standalone_self_upgrade.cf.in
Prior to this change Amazon Linux hosts (based on redhat|fedora) would not
attempt to upgrade themselves as they were not explicitly supported. With this
change hosts that have the amazon_linux class defined will use the same
methodology as redhat and centos hosts with respect to self upgrade.
Ticket: ENT-8274
(cherry picked from commit e4831d12046c5a9e470b2dce4612c34de3e1359d)
> ENT-8274: Added support for Amazon Linux in standalone self upgrade (3.15)

- cfe_internal/update/lib.cf
This change simply reduces some duplication of policy within the update policy.
Now that 3.10.x is 2 LTS series out it's safe to use inherit_from which was
introduced in 3.8.0.
Ticket: CFE-3917
> CFE-3917: Made body classes u_kept_successful_command_results inherit_from u_results

- cfe_internal/core/watchdog/templates/watchdog.mustache
At 3.18.1 cf-execd began running cf-agent from a child process instead of a
thread on POSIX systems. This change accounts for that difference.
> CFE-3915: Fixed AIX watchdog default threshold for number of cf-execd processes

- cfe_internal/enterprise/CFE_knowledge.cf
This is setup by packaging but should be maintained by policy.
Ticket: ENT-8212
(cherry picked from commit 3f3f1c394696fe9c627bcc2fa8f5dff76ad37068)
> ENT-8212 Enforce 755 perms on hub htdocs dir (3.15)

- cfe_internal/update/update_policy.cf
- cfe_internal/update/update_processes.cf
- controls/def.cf
- controls/update_def.cf.in
- lib/README.md
- lib/cfe_internal_hub.cf
Now that 3.12.x is not under standard support, we can remove anything that was
not used in 3.12. Things used in 3.12 need to remain to cover the case where
someone is upgrading to 3.15.x because 3.12.x was supported when 3.15.0 was
released.
This change redacts policy related to cf-consumer and cf-redis-server.
Ticket: CFE-3920
> CFE-3920: Cleaned up policy related to versions prior to 3.12

- configure.ac
configure.ac was missing entry
controls/update.cf already includes *.py so OK there.
Ticket: ENT-8393
> ENT-8393 Fixed inclusion of distributed cleanup python files during install

- configure.ac
configure.ac was missing entry
controls/update.cf already includes *.py so OK there.
Ticket: ENT-8393
(cherry picked from commit 90e23aa7043f75d34d38666a5e39d75b125c8707)
> ENT-8393 Fixed inclusion of distributed cleanup python files during install (3.18)

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7969
- Fixed variables name that check if remote_hubs and federated_reporting_settings tables exist.
- Removed federation-config.json when state is off
> Fixed FR clean bundle when off state

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7969
- Fixed variables name that check if remote_hubs and federated_reporting_settings tables exist.
- Removed federation-config.json when state is off
(cherry picked from commit b63b0fc6471d9be21f4f5d99db50090351ea0dbc)
> Fixed FR clean bundle when off state (3.15.x)

- MPF.md
- controls/cf_agent.cf
- controls/def.cf
Supersedes https://github.com/cfengine/masterfiles/pull/2248
> CFE-3925: Enabled settings environment vars in body agent control via augments

- MPF.md
I believe you don't need to escape _ in links
> Fix docs building

- MPF.md
- controls/cf_agent.cf
- controls/def.cf
It is sometimes necessary to set environment variables in cfengine context,
as setting them globaly/systemwide is not possible due to various unwanted side effects.
This change enables this.
Ticket: CFE-3925
> CFE-3925: Enable setting environment attribute in body agent control via augments (3.18)

- inventory/debian.cf
- inventory/linux.cf
CFEngine 3.11.0 brought classification based on /etc/os-release to core.
This change removes policy pre-dating core support for classification based on /etc/os-release.
> CFE-3993: Removed policy deprecated by sys.os_release

- modules/packages/vendored/msiexec-list.vbs.mustache
I can not find any legitimate reason that we are lowercasing software names on
Windows.
Ticket: ENT-8424
> ENT-8424: Stopped lowercasing software inventory on Windows

- MPF.md
I believe you don't need to escape _ in links
(cherry picked from commit b273f083690aa06f1cb65af8e474372d51b2d369)
> Fix docs building - 3.18.x

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/update/lib.cf
- cfe_internal/update/update_policy.cf
- lib/files.cf
Beginning with CFEngine 3.20 rxdirs default has changed from true to false.
This change explicitly sets the value to align with binary defaults. When
running binary versions prior to 3.20 rxdirs is enabled. For versions 3.20 and
greater rxdirs is disabled by default.
Starting with CFEngine 3.18.2, if a perms body sets mode without
specifying rxdirs a warning will be emitted. This change prevents those warnings
for perms bodies that are part of the MPF.
Ticket: CFE-951
> CFE-951: Adjusted rxdirs to have correct explicit default

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/update/lib.cf
- cfe_internal/update/update_policy.cf
- lib/files.cf
Beginning with CFEngine 3.20 rxdirs default has changed from true to false.
This change explicitly sets the value to align with binary defaults. When
running binary versions prior to 3.20 rxdirs is enabled. For versions 3.20 and
greater rxdirs is disabled by default.
Starting with CFEngine 3.18.2, if a perms body sets mode without
specifying rxdirs a warning will be emitted. This change prevents those warnings
for perms bodies that are part of the MPF.
Ticket: CFE-951
(cherry picked from commit 655b0816301b91371b98cc95d1c7ffad4d5488c8)
> CFE-951: Adjusted rxdirs to have correct explicit default (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
- lib/files.cf
Effectively reverting the change of the default for rxdirs in
https://github.com/cfengine/core/commit/c79917e80682fecb444a9949742fcf4096c9e6b3 for now until we have a proper solution
with explicit values for specific cases in our policy.
> Use 'rxdirs => "true"' explicitly

- templates/federated_reporting/distributed_cleanup.py
> Fix typo of classname in distributed cleanup python script

- templates/federated_reporting/distributed_cleanup.py
Ticket: none
(cherry picked from commit 2e8624000af10591b766c5ab36e623f53cbd798e)
> Fix typo of classname in distributed cleanup python script (3.18)

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/enterprise/federation/federation.cf
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
- lib/cfe_internal_hub.cf
- lib/files.cf
- templates/federated_reporting/psql_wrapper.sh.mustache
This change aligns the Masterfiles Policy Framework and the CFEngine binary
default for rxdirs. With this change, the vendored policy should not result in
any warnings about rxdirs not being explicitly defined. Cases where rxdirs was
previously relied on have been adjusted so that cases were directories should
have the executable bit are explicitly promised.
Ticket: CFE-951
(cherry picked from commit 999a27585567e6e1689917d1250e03eb1cbd37b3)
https://github.com/cfengine/core/pull/4930
https://github.com/cfengine/masterfiles/pull/2270
> CFE-951: Adjusted MPF to handle rxdirs default from true to false (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2275
- https://github.com/cfengine/buildscripts/pull/958
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
> ENT-8495: Stopped loading webdav apache modules by default

- promises.cf.in
- services/main.cf
This change helps to avoid potential duplicate definition of bundle errors from
having a bundle named main included by a policy entry that contains a bundle
agent __main__.
Ticket: CFE-3947
> CFE-3947: Renamed bundle agent main to bundle agent mpf_main

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2276
- https://github.com/cfengine/buildscripts/pull/959
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
(cherry picked from commit 545db12ab6d7df13511a6111a08a1d4aba048904)
> ENT-8495: Stopped loading webdav apache modules by default (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2277
- https://github.com/cfengine/buildscripts/pull/960
CFEngine Enterprise does not currently use webdav by default, so we do not need
to load these modules. They are still present in the build so users can still
leverage them if desired.
Ticket: ENT-8495
Changelog: CFEngine Enterprise Hub Apache no longer loads webdav modules by default
(cherry picked from commit 545db12ab6d7df13511a6111a08a1d4aba048904)
> ENT-8495: Stopped loading webdav apache modules by default (3.15)

- configure.ac
lib/testing.cf (which is not loaded as part of the stdlib by default) uses
lib/templates/tap.mustache and lib/templates/junit.mustache but those files were
not part of the packaged MPF prior to this change, making it difficult to simply
add lib/testing.cf to inputs to start writing policy tests.
Ticket: ENT-8533
> ENT-8533: Added lib/templates to packaged assets

- configure.ac
lib/testing.cf (which is not loaded as part of the stdlib by default) uses
lib/templates/tap.mustache and lib/templates/junit.mustache but those files were
not part of the packaged MPF prior to this change, making it difficult to simply
add lib/testing.cf to inputs to start writing policy tests.
Ticket: ENT-8533
(cherry picked from commit 5bb9a9eb928e2af04ba0a52652ff44d7d076911f)
> ENT-8533: Added lib/templates to packaged assets (3.18)

- configure.ac
lib/testing.cf (which is not loaded as part of the stdlib by default) uses
lib/templates/tap.mustache and lib/templates/junit.mustache but those files were
not part of the packaged MPF prior to this change, making it difficult to simply
add lib/testing.cf to inputs to start writing policy tests.
Ticket: ENT-8533
(cherry picked from commit 5bb9a9eb928e2af04ba0a52652ff44d7d076911f)
> ENT-8533: Added lib/templates to packaged assets (3.15)

- controls/reports.cf
This has not been true since 3.6.0 when variables_exclude was removed. Prior to
it's removal it did indeed exclude underscore prefixed variables as part of
bce7032f603deb2b8df8f87a26838816d6d2266d.
Ticket: ENT-8547
> ENT-8547: Removed comments about underscore prefixed vars not being reported by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/962
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
> ENT-8506: Stopped loading mod_status by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/963
Since we do not use the features provided by this module we don't need to load
it by default.
Ticket: ENT-8504
(cherry picked from commit 5ec784902cefa5c6f7a3d357e523793db469ec65)
> ENT-8504: Stopped loading mod_info (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/964
Since we do not use the features provided by this module we don't need to load
it by default.
Ticket: ENT-8504
(cherry picked from commit 5ec784902cefa5c6f7a3d357e523793db469ec65)
> ENT-8504: Stopped loading mod_info (3.15)

- controls/reports.cf
This has not been true since 3.6.0 when variables_exclude was removed. Prior to
it's removal it did indeed exclude underscore prefixed variables as part of
bce7032f603deb2b8df8f87a26838816d6d2266d.
Ticket: ENT-8547
(cherry picked from commit f48a7b6b504282fd434087e06a00474b3654a7e3)
> ENT-8547: Removed comments about underscore prefixed vars not being reported by default (3.18)

- controls/reports.cf
This has not been true since 3.6.0 when variables_exclude was removed. Prior to
it's removal it did indeed exclude underscore prefixed variables as part of
bce7032f603deb2b8df8f87a26838816d6d2266d.
Ticket: ENT-8547
(cherry picked from commit f48a7b6b504282fd434087e06a00474b3654a7e3)
> ENT-8547: Removed comments about underscore prefixed vars not being reported by default (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/965
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
(cherry picked from commit c05723e44302eb25aee2410f3a55739a76f75466)
> ENT-8506: Stopped loading mod_status by default (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/966
Since we don't make active use of this module, we don't need to load it by default.
Ticket: ENT-8506
(cherry picked from commit c05723e44302eb25aee2410f3a55739a76f75466)
> ENT-8506: Stopped loading mod_status by default (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/970
We don't use any of the features this module provides, so we should not load the
module by default.
Ticket: ENT-8499
> ENT-8499: Stopped loading Apache speling_module by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/971
We don't use any of the features this module provides, so we should not load the
module by default.
Ticket: ENT-8499
(cherry picked from commit 02cb6eb17c40b52ac5e8b7f605bf4e3b3801adfc)
> ENT-8499: Stopped loading Apache speling_module by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/972
We don't use any of the features this module provides, so we should not load the
module by default.
Ticket: ENT-8499
(cherry picked from commit 02cb6eb17c40b52ac5e8b7f605bf4e3b3801adfc)
> ENT-8499: Stopped loading Apache speling_module by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/973
We do not use the functionality provided by this module, so we should  not load
it by default.
Ticket: ENT-8497
> ENT-8497: Stopped loading Apache mod_version by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/974
We do not use the functionality provided by this module, so we should  not load
it by default.
Ticket: ENT-8497
(cherry picked from commit c9b9ed92f4cbe8d765836d3223defff558c40881)
> ENT-8497: Stopped loading Apache mod_version by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1017
default.
Ticket: ENT-8522
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1018
default.
Ticket: ENT-8522
(cherry picked from commit 0a766d665f920654027911c38675f5a05f399893)
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1019
default.
Ticket: ENT-8522
(cherry picked from commit 0a766d665f920654027911c38675f5a05f399893)
> ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2302
default.
Ticket: ENT-8514
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2303
default.
Ticket: ENT-8514
(cherry picked from commit 149713b87cbd4446693fbad445e64318c6e44300)
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/masterfiles/pull/2304
default.
Ticket: ENT-8514
(cherry picked from commit 149713b87cbd4446693fbad445e64318c6e44300)
> ENT-8514: Stopped loading Apache mod_autoindex by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/969
We do not use functionality provided by this module so we should not load it by
default.
Ticket: ENT-8498
(cherry picked from commit 1a3a662e16116a1789a81578b57d8983aeedbb06)
> ENT-8498: Stopped loading Apache substitute module on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/968
We do not use functionality provided by this module so we should not load it by
default.
Ticket: ENT-8498
(cherry picked from commit 1a3a662e16116a1789a81578b57d8983aeedbb06)
> ENT-8498: Stopped loading Apache substitute module on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/987
default.
Ticket: ENT-8503
> ENT-8503: Stopped loading Apache mod_actions by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/988
default.
Ticket: ENT-8503
(cherry picked from commit d8f8f7272e0b237c240ca9475a1327c5f3c7fc50)
> ENT-8503: Stopped loading Apache mod_actions by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/989
default.
Ticket: ENT-8503
(cherry picked from commit d8f8f7272e0b237c240ca9475a1327c5f3c7fc50)
> ENT-8503: Stopped loading Apache mod_actions by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/991
default.
Ticket: ENT-8505
(cherry picked from commit 6237f333df7736f2fcc941a617c5f438d23a457e)
> ENT-8505: Stopped loading Apache mod_asis by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/992
default.
Ticket: ENT-8505
(cherry picked from commit 6237f333df7736f2fcc941a617c5f438d23a457e)
> ENT-8505: Stopped loading Apache mod_asis by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/993
default.
Ticket: ENT-8507
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/994
default.
Ticket: ENT-8507
(cherry picked from commit 8ffe176eb3654f3b3aa9f1daa0cbcaa948e816e3)
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/995
default.
Ticket: ENT-8507
(cherry picked from commit 8ffe176eb3654f3b3aa9f1daa0cbcaa948e816e3)
> ENT-8507: Stopped loading Apache mod_include by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/996
default.
Ticket: ENT-8509
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/997
default.
Ticket: ENT-8509
(cherry picked from commit c423f32fb5d36502438a7765c7f06640b6efbe1e)
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/998
default.
Ticket: ENT-8509
(cherry picked from commit c423f32fb5d36502438a7765c7f06640b6efbe1e)
> ENT-8509: Stopped loading Apache mod_ldap by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/999
default.
Ticket: ENT-8511
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1000
default.
Ticket: ENT-8511
(cherry picked from commit 2580e1a21c2251104f369847c0afe1534376afdf)
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1001
default.
Ticket: ENT-8511
(cherry picked from commit 2580e1a21c2251104f369847c0afe1534376afdf)
> ENT-8511: Stopped loading Apache mod_negotiation by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1002
default.
Ticket: ENT-8512
> ENT-8512: Stopped loading Apache mod_authnz_ldap by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1003
default.
Ticket: ENT-8512
(cherry picked from commit b3fbdd36bf1caf32a1e741d4f1c471327116a2f4)
> ENT-8512: Stopped loading Apache mod_authnz_ldap by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1004
default.
Ticket: ENT-8512
(cherry picked from commit b3fbdd36bf1caf32a1e741d4f1c471327116a2f4)
> ENT-8512: Stopped loading Apache mod_authnz_ldap by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1005
default.
Ticket: ENT-8513
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8513: Stopped loading Apache mod_vhost_alias by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1008
default.
Ticket: ENT-8517
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1009
default.
Ticket: ENT-8517
(cherry picked from commit 9fbdb77a01c4457e6cd6ef8dd243c0e3f6dfe1a4)
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1010
default.
Ticket: ENT-8517
(cherry picked from commit 9fbdb77a01c4457e6cd6ef8dd243c0e3f6dfe1a4)
> ENT-8517: Stopped loading Apache mod_mime_magic by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1011
default.
Ticket: ENT-8519
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1012
default.
Ticket: ENT-8519
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1013
default.
Ticket: ENT-8519
(cherry picked from commit b099381e2f2479e2736a6faf5b10a78893e003a3)
> ENT-8519: Stopped loading Apache mod_unique_id by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1014
default.
Ticket: ENT-8521
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1015
default.
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1016
default.
> ENT-8521: Stopped loading Apache mod_usertrack by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/984
default.
Ticket: ENT-8501
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/985
default.
Ticket: ENT-8501
(cherry picked from commit 15a7df927d57c76d4190cb9b74fb3de430415ed9)
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/986
default.
Ticket: ENT-8501
(cherry picked from commit 15a7df927d57c76d4190cb9b74fb3de430415ed9)
> ENT-8501: Stopped loading Apache mod_log_forensic by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/982
default.
> ENT-8526: Stopped loading Apache mod_dumpio by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8526: Stopped loading Apache mod_dumpio by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1032
> ENT-8525: Stopped loading Apache mod_reqtimeout by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1033
> ENT-8525: Stopped loading Apache mod_reqtimeout by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1028
We do not use the features provided by these modules, so we should not load them by default.
Ticket: ENT-8524
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1029
We do not use the features provided by these modules, so we should not load them by default.
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1030
We do not use the features provided by these modules, so we should not load them by default.
> ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs (3.15)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/distributed_cleanup.py
- templates/federated_reporting/nova_api.py
- templates/federated_reporting/transfer_distributed_cleanup_items.sh
Testing was done on machines where platform.node() was
the same as socket.getfqdn() but this is often not
the case.
Ticket: ENT-8464
> ENT-8464: Use FQDN for cert path in distributed cleanup

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1025
> ENT-8523: Stopped loading Apache mod_deflate by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
This change is intended to better document and understand our use of Apache
modules in the default configuration.
- https://github.com/cfengine/buildscripts/pull/1039
> ENT-8554: Added in-line reasoning for use of Apache modules

- cfe_internal/enterprise/templates/httpd.conf.mustache
This change is intended to better document and understand our use of Apache
modules in the default configuration.
- https://github.com/cfengine/buildscripts/pull/1040
> ENT-8554: Added in-line reasoning for use of Apache modules (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
This change is intended to better document and understand our use of Apache
modules in the default configuration.
- https://github.com/cfengine/buildscripts/pull/1041
> ENT-8554: Added in-line reasoning for use of Apache modules (3.15)

- templates/federated_reporting/distributed_cleanup.py
cherry-picked from https://github.com/cfengine/masterfiles/pull/2358
> ENT-8494: Add hub interactively in distributed-cleanup.py - 3.18.x

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1042
> ENT-8598: Stopped loading Apache mod_authn_file by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1043
> ENT-8598: Stopped loading Apache mod_authn_file by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1044
> ENT-8598: Stopped loading Apache mod_authn_file by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1046
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1045
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/1047
> ENT-8599: Stopped loading Apache mod_authn_dbm by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1054
> ENT-8604: Stopped loading Apache mod_authz_user by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1055
> ENT-8604: Stopped loading Apache mod_authz_user by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1048
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1049
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1050
> ENT-8600: Stopped loading Apache mod_authn_anon by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1051
> ENT-8610: Stopped loading Apache mod_expires by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1052
> ENT-8610: Stopped loading Apache mod_expires by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1053
> ENT-8610: Stopped loading Apache mod_expires by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/file_change.cf
This change adds the postgresql.conf file used on Enterprise Hubs to the list of
files we report detailed changes on by default. This allows for better tracking
of alterations to the file over time.
> ENT-8618: Added Enterprise Hub postgresql.conf to files monitored for diffs by default

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
This change instruments tunables for `postgresql.conf` when Federated Reporting is
enabled.
The existing defaults for `shared_buffers`, `max_locks_per_transaction`, and
`log_lock_waits` have been exposed as `cfengine_enterprise_federation.postgres_config.shared_buffers`,
`cfengine_enterprise_federation.postgres_config.max_locks_per_transaction`, and
`cfengine_enterprise_federation.postgres_config.log_lock_waits` respectively.
Additionally, since the superhub common needs `checkpoint_timeout` and
`max_wal_size` adjusted, they have been added to the default
configuration with their default values and exposed as
`cfengine_enterprise_federation.postgres_config.checkpoint_timeout` and
`cfengine_enterprise_federation.postgres_config.max_wal_size` respectively.
> ENT-8617: Added PostgreSQL tunables for Federated Reporting

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1057
> ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
This change instruments tunables for postgresql.conf when Federated Reporting is
enabled.
The existing defaults for shared_buffers, max_locks_per_transaction, and
log_lock_waits have been exposed as cfengine_enterprise_federation.postgres_config.shared_buffers,
cfengine_enterprise_federation.postgres_config.max_locks_per_transaction, and
cfengine_enterprise_federation.postgres_config.log_lock_waits respectively.
Additionally, since the superhub common needs checkpoint_timeout and
max_wal_size adjusted, they have been added to the default
configuration with their default values and exposed as
cfengine_enterprise_federation.postgres_config.checkpoint_timeout and
cfengine_enterprise_federation.postgres_config.max_wal_size respectively.
> ENT-8617: Added PostgreSQL tunables for Federated Reporting (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1060
> ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
This change instruments tunables for postgresql.conf when Federated Reporting is
enabled.
The existing defaults for shared_buffers, max_locks_per_transaction, and
log_lock_waits have been exposed as cfengine_enterprise_federation.postgres_config.shared_buffers,
cfengine_enterprise_federation.postgres_config.max_locks_per_transaction, and
cfengine_enterprise_federation.postgres_config.log_lock_waits respectively.
Additionally, since the superhub common needs checkpoint_timeout and
max_wal_size adjusted, they have been added to the default
configuration with their default values and exposed as
cfengine_enterprise_federation.postgres_config.checkpoint_timeout and
cfengine_enterprise_federation.postgres_config.max_wal_size respectively.
> ENT-8617: Added PostgreSQL tunables for Federated Reporting (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1063
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1059
> ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1062
> ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/file_change.cf
This change adds the postgresql.conf file used on Enterprise Hubs to the list of
files we report detailed changes on by default. This allows for better tracking
of alterations to the file over time.
> ENT-8618: Added Enterprise Hub postgresql.conf to files monitored for diffs by default (3.18)

- cfe_internal/enterprise/file_change.cf
This change adds the postgresql.conf file used on Enterprise Hubs to the list of
files we report detailed changes on by default. This allows for better tracking
of alterations to the file over time.
> ENT-8618: Added Enterprise Hub postgresql.conf to files monitored for diffs by default (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1064
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1065
> ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs (3.15)

- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/apachectl.mustache
The stock apachectl does not wait to see if a signal had the desired effect. In
the case of stopping and restarting this can result in httpd processes being
left running preventing new configuration from taking effect.
This change renders a patched apachectl which is instrumented to briefly wait
for httpd to be fully terminated and takes more aggressive actions to ensure
httpd is fully stopped before exiting.
This script is part of the package but needs to also be handled by the MPF to
cover the case of upgrade where policy from the newer version is running before
binaries from the newer version are running.
> ENT-8823: Added policy to patch apachectl for more robust stopping on Enterprise Hubs

- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/apachectl.mustache
The stock apachectl does not wait to see if a signal had the desired effect. In
the case of stopping and restarting this can result in httpd processes being
left running preventing new configuration from taking effect.
This change renders a patched apachectl which is instrumented to briefly wait
for httpd to be fully terminated and takes more aggressive actions to ensure
httpd is fully stopped before exiting.
This script is part of the package but needs to also be handled by the MPF to
cover the case of upgrade where policy from the newer version is running before
binaries from the newer version are running.
> ENT-8823: Added policy to patch apachectl for more robust stopping on Enterprise Hubs (3.18)

- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/apachectl.mustache
The stock apachectl does not wait to see if a signal had the desired effect. In
the case of stopping and restarting this can result in httpd processes being
left running preventing new configuration from taking effect.
This change renders a patched apachectl which is instrumented to briefly wait
for httpd to be fully terminated and takes more aggressive actions to ensure
httpd is fully stopped before exiting.
This script is part of the package but needs to also be handled by the MPF to
cover the case of upgrade where policy from the newer version is running before
binaries from the newer version are running.
> ENT-8823: Added policy to patch apachectl for more robust stopping on Enterprise Hubs (3.15)

- tests/acceptance/17_packages/11_old/unsafe/package-inventory.cf
- tests/acceptance/17_packages/meta_skip.cf.sub
Need to generate package files.
Ticket: CFE-3992
> CFE-3992: Skip package-inventory test on aarch64 platform

- cfe_internal/enterprise/mission_portal.cf
It's not with the rest of the binaries, it's in $WORKDIR/httpd/bin
> ENT-8823: Fixed path to apachectl

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/distributed_cleanup.py
Added policy to install required dependencies: python3 and python3-urllib3
Added interactive option to distributed_cleanup.py to support automation
https://github.com/cfengine/system-testing/pull/438
https://github.com/cfengine/documentation/pull/2734
https://github.com/cfengine/masterfiles/pull/2403
> ENT-8832 Improve distributed_cleanup utility setup

- cfe_internal/update/update_policy.cf
This change is intended to improve the smoothness with respect to unscheduled
agent runs in relation to CMDB data update. Specifically so that the default 1
minute locking period does not prevent an unscheduled agent run from updating
it's CMDB data.
For example, when Trigger agent run button is clicked, a request is made for the
host to do an agent run. If there was an agent less than one minute ago the CMDB
data would not update because of the lock.
> ENT-8847: Made cmdb update ignore locks

- cfe_internal/update/update_policy.cf
This change is intended to improve the smoothness with respect to unscheduled
agent runs in relation to CMDB data update. Specifically so that the default 1
minute locking period does not prevent an unscheduled agent run from updating
it's CMDB data.
For example, when Trigger agent run button is clicked, a request is made for the
host to do an agent run. If there was an agent less than one minute ago the CMDB
data would not update because of the lock.
> ENT-8847: Made cmdb update ignore locks (3.18)

- modules/packages/vendored/apt_get.mustache
Previously we used distutils.LooseVersion but distutils is being
deprecated in newer Python versions, such as that available in Ubuntu 22,
so we must migrate to something else.
After looking around a bit and considering our use of LooseVersion it
seems a simple version of this check is all that is needed.
Assuming that apt-get -v always returns simple numeric versions
we compare versions as a list of integers.
(cherry picked from commit 34cfe809154280b1bb0fa8e1477d8b5c8ee6e8a0)
> CFE-3976 Use simple numeric comparison in apt_get package module (3.18)

- modules/packages/vendored/apt_get.mustache
Previously we used distutils.LooseVersion but distutils is being
deprecated in newer Python versions, such as that available in Ubuntu 22,
so we must migrate to something else.
After looking around a bit and considering our use of LooseVersion it
seems a simple version of this check is all that is needed.
Assuming that apt-get -v always returns simple numeric versions
we compare versions as a list of integers.
(cherry picked from commit 34cfe809154280b1bb0fa8e1477d8b5c8ee6e8a0)
> CFE-3976 Use simple numeric comparison in apt_get package module (3.15)

- CHANGELOG.md
- modules/packages/vendored/apt_get.mustache
assumption that `apt-get -v` returns faily simple version with integers separated by dots turned out to be wrong on Ubuntu 14. Let's revert it for now, because it might happen on other versions of Ubuntu, too
> CFE-3976 revert apt_get changes - 3.18.x

- .gitignore
Flycheck (Emacs syntax checker) generates temporary files in the course of it's
checking. They noise up the git status buffer unless they are ignored.
> Ignored flycheck temporary files

- modules/packages/vendored/apt_get.mustache
Relying on the version only having integers didn't work on an old ubuntu
which gave 1.1.1ubuntu2
> CFE-3976 Fix apt_get package module version comparison

- cfe_internal/enterprise/CFE_knowledge.cf
The recent change in default behavior for rxdirs caused Mission Portals
application log directory to lose it's execute bit. Without the execute bit
Mission Portal is unable to list the contents of the directory and fails to
create application log files. This change rectifies the condition.
Ticket: ENT-8908, CFE-951
> ENT-8908: Added execute bit for owner on httpd application log dir

- cfbs.json
I imagine this is most useful for testing or those who want to live on the edge.
Installing masterfiles directly prohibits cfbs upgrade functionality, commit sha
changing must be done manually.
> ENT-8915: Made it possible to cfbs add the masterfiles repository directly

- lib/files.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf.expected-result
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf.start
* https://github.com/cfengine/core/pull/4993
* https://github.com/cfengine/documentation/pull/2779
* new variable `edit.empty_before_use` in docs (http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-62/output/_site/reference-special-variables-edit.html#edit-empty_before_use)
** Cross referenced from `edit_defaults.empty_file_before_editing` (http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-62/output/_site/reference-promise-types-files.html#empty_file_before_editing)
http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-fast-build-and-deploy-docs-master-62/output/_site/reference-promise-types-files.html#empty_file_before_editing
The implementation …
> ENT-5866: Fixed set_line_based() for case when edit_defaults.empty_before_use is true

- standalone_self_upgrade.cf.in
In 3.18.0 sys.flavor on windows changed so that it includes the major OS version
as is the case for most other platforms. That change broke the expectation of
where to find software during self upgrade. This change simply re-aligns the
source directory used. Since we only build one package for each architecture we
keep using a single directory instead of a separate directory per windows version.
> ENT-9010: Fixed directory in which windows agents source packages for upgrade (3.18)

- modules/packages/vendored/apt_get.mustache
Relying on the version only having integers didn't work on an old ubuntu
which gave 1.1.1ubuntu2
(cherry picked from commit 9cdc23e7ea238f71c24374bcd16ba1e76f75be7e)
Conflicts:
modules/packages/vendored/apt_get.mustache
> CFE-3976: Fix apt_get package module version comparison (3.15)

- cfe_internal/enterprise/federation/federation.cf
We define a separate namespace for the FR policy in federation.cf
and the 'paths' bundle is in the default namespace.
Ticket: ENT-8817
> Use '$(default:paths.something)' in federation.cf

- controls/def.cf
- inventory/any.cf
- inventory/linux.cf
Raspberry Pi kernel has odd entries in /proc/cpuinfo: Model, Hardware, Revision
Also present is /proc/device-tree which generaly excludes the presence of usable dmi information from dmidecode.
Use device tree model, serial-number and compatible data for inventory and defining appropriate classes describing the host.
Ticket: ENT-8628
> ENT-8628: Add inventory for Raspberry Pi and DeviceTree devices

- modules/packages/vendored/apt_get.mustache
Relying on the version only having integers didn't work on an old ubuntu
which gave 1.1.1ubuntu2
(cherry picked from commit 9cdc23e7ea238f71c24374bcd16ba1e76f75be7e)
Conflicts:
modules/packages/vendored/apt_get.mustache
with https://github.com/cfengine/buildscripts/pull/1098
> CFE-3976: Fix apt_get package module version comparison (3.18)

- .travis.yml
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf
- tests/acceptance/lib/files/set_line_based_variable_values.cf
ENT-5866 fix for set_line_based() does not work when combined
with edit_defaults => empty was only back ported to 3.18.x.
Ticket: ENT-9028
> ENT-9028: Skip two tests on older platforms due to lack of fix there

- .travis.yml
- lib/files.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf
- tests/acceptance/lib/files/set_line_based_variable_values.cf
ENT-5866 fix for set_line_based() does not work when combined
with edit_defaults => empty was only back ported to 3.18.x.
Ticket: ENT-9028
(cherry picked from commit 636908732ff086d48cd59b861641b2d294ef6210)
> ENT-9028: Skip two tests on older platforms due to lack of fix there (3.18)

- controls/def.cf
- inventory/any.cf
- inventory/linux.cf
Raspberry Pi kernel has odd entries in /proc/cpuinfo: Model, Hardware, Revision
Also present is /proc/device-tree which generaly excludes the presence of usable dmi information from dmidecode.
Use device tree model, serial-number and compatible data for inventory and defining appropriate classes describing the host.
Ticket: ENT-8628
(cherry picked from commit 3f4ea452dc457d3e104a8d30bae0c23940b033cf)
Conflicts:
inventory/linux.cf
Had to include old /etc/os-release policy still in 3.18.x
with https://github.com/cfengine/masterfiles/pull/2440
> ENT-8628: Add inventory for Raspberry Pi and DeviceTree devices (3.18)

- tests/acceptance/17_packages/11_old/unsafe/package-inventory.cf
- tests/acceptance/17_packages/meta_skip.cf.sub
Need to generate package files for other distributions and architectures.
Ticket: CFE-3992
(cherry picked from commit ad3ffa0f9f4538d62e2159e562cfda8a1466449a)
> CFE-3992: Skip package-inventory test on all but redhat/debian on x86_64 (3.18)

- lib/files.cf
With the new feature being picked to 3.18, the implementation needed to handle the change in behavior between 3.18.2 and yet to be released 3.18.3.
> ENT-9028: Handled backport of core behavior change that added edit.empty_before_use 

- lib/files.cf
Follow up to https://github.com/cfengine/masterfiles/pull/2442
Related to set_line_based tests.
Ticket: ENT-9028
> ENT-9028: Fix typo in lib/files.cf class guard (3.18)

- lib/packages.cf
Thanks Cory Coager <cory.coager@cdphp.com> for suggesting this improvement.
Ticket: ENT-9057
> ENT-9057: Amazon Linux now uses --setopt-exit_on_lock=True in redhat_no_locking_knowledge

- controls/cf_serverd.cf
The default is defined in core/cf-serverd/server_tls.c:ServerTLSInitialize().
Ticket: ENT-9018
> Fix the default value of 'allowciphers' and improve the comment a bit

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8609: Stopped loading Apache mod_dbd on Enterprise Hubs by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-8609
(cherry picked from commit d872f617e07204f9570b14b0f58be3ee15e6b02c)
> ENT-8609: Stopped loading Apache mod_dbd on Enterprise Hubs by default (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-8609
(cherry picked from commit d872f617e07204f9570b14b0f58be3ee15e6b02c)
> ENT-8609: Stopped loading Apache mod_dbd on Enterprise Hubs by default (3.15)

- lib/packages.cf
Thanks @ccoager for suggesting this improvement.
Ticket: ENT-9057
(cherry picked from commit c1af045f0a338dda2b382ff4ae51d5002c4b215c)
> ENT-9057: Amazon Linux now uses --setopt-exit_on_lock=True in redhat_no_locking_knowledge (3.18)

- lib/packages.cf
Thanks @ccoager for suggesting this improvement.
Ticket: ENT-9057
(cherry picked from commit c1af045f0a338dda2b382ff4ae51d5002c4b215c)
> ENT-9057: Amazon Linux now uses --setopt-exit_on_lock=True in redhat_no_locking_knowledge (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8602: Stopped loading Apache mod_authz_host on Enterprise Hubs by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-8706: Stopped loading Apache mod_authz_owner on Enterprise Hubs by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-8602
(cherry picked from commit 03f8d78110f786937c6c9543502a8916ec59cf66)
> ENT-8602: Stopped loading Apache mod_authz_host on Enterprise Hubs by default (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-8706
(cherry picked from commit f41b74e73b8ddc1f7c9e543023af29ce49a48026)
> ENT-8706: Stopped loading Apache mod_authz_owner on Enterprise Hubs by default (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-8706
(cherry picked from commit f41b74e73b8ddc1f7c9e543023af29ce49a48026)
> ENT-8706: Stopped loading Apache mod_authz_owner on Enterprise Hubs by default (3.15)

- inventory/linux.cf
In docker aarch64 containers /proc/device-tree exists
but files underneath are not present.
Ticket: ENT-9063
> ENT-9063: Make device-tree inventory quieter in containers

- inventory/linux.cf
In docker aarch64 containers /proc/device-tree exists
but files underneath are not present.
Ticket: ENT-9063
> Make device-tree inventory quieter in containers (typo fix)

- inventory/linux.cf
In docker aarch64 containers /proc/device-tree exists
but files underneath are not present.
Ticket: ENT-9063
(cherry picked from commit 9251b2ece72a1c70f98e2c696c9e0bba41f64b3f)
> ENT-9063: Make device-tree inventory quieter in containers (3.18)

- controls/cf_serverd.cf
The default is defined in core/cf-serverd/server_tls.c:ServerTLSInitialize().
Ticket: ENT-9018
(cherry picked from commit 92e6131db57b263a0d0ff6ca12afd4b5a414a628)
> [3.18.x] Fix the default value of 'allowciphers' and improve the comment a bit

- controls/cf_serverd.cf
The default is defined in core/cf-serverd/server_tls.c:ServerTLSInitialize().
Ticket: ENT-9018
(cherry picked from commit 92e6131db57b263a0d0ff6ca12afd4b5a414a628)
> [3.15.x] Fix the default value of 'allowciphers' and improve the comment a bit

- cfe_internal/enterprise/mission_portal.cf
The Apache pid file moved in CFEngine 3.15.5, 3.18.1 and 3.19.0. When new policy
is running on a version prior to having the pid file relocated this would result
in an error stopping apache. This change avoids that failure.
Ticket: ENT-9108
> ENT-9108: Avoided error stopping apache when no pid file exists

- lib/paths.cf
> CEF-4037: Added ssh in paths.cf so that policy writers can use $(paths.ssh)

- lib/paths.cf
Ticket: CFE-4037
(cherry picked from commit 770cd89929cce8768a3ba08cbf95328a531fe1bc)
> CFE-4037: Added ssh in paths.cf so that policy writers can use $(paths.ssh) (3.18)

- lib/paths.cf
Ticket: CFE-4037
(cherry picked from commit 770cd89929cce8768a3ba08cbf95328a531fe1bc)
> CFE-4037: Added ssh in paths.cf so that policy writers can use $(paths.ssh) (3.15)

- cfe_internal/enterprise/mission_portal.cf
The Apache pid file moved in CFEngine 3.15.5, 3.18.1 and 3.19.0. When new policy
is running on a version prior to having the pid file relocated this would result
in an error stopping apache. This change avoids that failure.
Ticket: ENT-9108
(cherry picked from commit 5452a2370191a0100a044422953240b9026aa02e)
Backport of #2477.
> [3.18.x] ENT-9108: Avoided error stopping apache when no pid file exists

- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
> ENT-9140: Disable more package tests on non x86_64 platforms

- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
Ticket: ENT-9140
(cherry picked from commit c19abd4bf6eeda3b184f3b8ea46611bd6604fcf0)
> ENT-9140: Disable more package tests on non x86_64 platforms (3.18)

- tests/Makefile.am
This Makefile target is only needed for files in tests/unit.
The existing target was causing tests/unit/Makefile.in to be modified
and causing tests/unit/Makefile to be re-created by config.status
which on some platforms fails due to automake version mismatch.
Ticket: ENT-9130
> ENT-9130: Make fix-python-hashbang more precise

- tests/Makefile.am
This Makefile target is only needed for files in tests/unit.
The existing target was causing tests/unit/Makefile.in to be modified and causing tests/unit/Makefile to be re-created by config.status which on some platforms fails due to automake version mismatch.
Ticket: ENT-9130
(cherry picked from commit b146ce374105f3d4f16ca7fc0d09a228e3023b93)
> ENT-9130: Make fix-python-hashbang more precise (3.18)

- standalone_self_upgrade.cf.in
(cherry picked from commit d728634e8cf77eb0200db61b2855ff444b236024)
> ENT-9206: Made self binary upgrade aware of Ubuntu 20 (3.18)

- .github/workflows/ci.yml
This should "just work" in several situations:
- pull requests which change github actions/workflows
- push activity which uses the pushed/merged code
> ENT-9162: Fixed up dependent github workflows

- standalone_self_upgrade.cf.in
Ticket: ENT-9210
(cherry picked from commit 12f170847f6be19be64fc3c51e0bc41f8e82a1e7)
> ENT-9210: Added self upgrade knowledge for debian 11 (3.18)

- standalone_self_upgrade.cf.in
Ticket: ENT-9209
(cherry picked from commit 3dd2f0388474117714b0d2f156e360ada0636722)
> ENT-9209: Added self upgrade knowledge for Suse 12, 15 and opensuse leap 15 (3.18)

- templates/cf-serverd.service.mustache
Reflecting the changes from cfengine/core@962bac57c2af.
(cherry picked from commit 7b43827a4cbefc5a1205d288b811cba616c2916d)
https://github.com/cfengine/core/pull/5070
https://github.com/cfengine/masterfiles/pull/2508
> [3.18.x] Adapt the cf-serverd.service template to the version from core

- MPF.md
- inventory/any.cf
Ticket: CFE-4056
Example stock:
```
[root@hub ~]# rm -f /var/cfengine/data/host_specific.json; cf-agent -K --show-evaluated-vars=default:cfe_autorun_inventory_proc | head 
Variable name                            Variable value                                               Meta tags                                Comment                                 
default:cfe_autorun_inventory_proc.basefiles  {"consoles","cpuinfo","modules","partitions","version"}     source=promise                                                                   
default:cfe_autorun_inventory_proc.console_count 2                                                            source=promise                                                                   
default:cfe_autorun_inventory_proc.console_idx …
```
> CFE-4056: Made proc inventory configurable via Augments

- controls/cf_execd.cf
Ticket: ENT-8107
(cherry picked from commit 6a7de8c4896183b72902302bdef38b62f22f0e71)
> ENT-8107: Removed stale reference to cf-twin (3.18)

- controls/cf_execd.cf
Ticket: ENT-8107
(cherry picked from commit 6a7de8c4896183b72902302bdef38b62f22f0e71)
> ENT-8107: Removed stale reference to cf-twin (3.15)

- lib/paths.cf
This change makes $(paths.date) available along with its associated classes when
the binary is present.
Ticket: CFE-4069
(cherry picked from commit 5df868aaea9a0c921518db3aca89080342fe7a49)
> CFE-4069: Added date to known paths for linux (3.18)

- lib/paths.cf
This change makes $(paths.date) available along with its associated classes when
the binary is present.
Ticket: CFE-4069
(cherry picked from commit 5df868aaea9a0c921518db3aca89080342fe7a49)
> CFE-4069: Added date to known paths for linux (3.15)

- cfe_internal/enterprise/CFE_knowledge.cf
The recent change in default behavior for rxdirs caused Mission Portals
application log directory to lose it's execute bit. Without the execute bit
Mission Portal is unable to list the contents of the directory and fails to
create application log files. This change rectifies the condition.
Ticket: ENT-8908, CFE-951
(cherry picked from commit 3ea0d6a6bac0451a056032eb28cb2224b7ebc9ac)
> ENT-8908: Added execute bit for owner on httpd application log dir (3.18)

- tests/Makefile.am
The change is OK now because the selection of the files is more careful
after a recent change, quoting @craigcomstock:
> before I added the search for name `*.py and mock_*` it was running
> `sed -ri` on every file under that dir.
Platforms which don't support it are AIX 5 and HP-UX.
(cherry-picked from commit https://github.com/Lex-2008/masterfiles/commit/8099f1a06e57ddae240a859dd5389c7736788897)
> Remove mindepth argument from find since not all platforms support it - 3.18.x

- cfe_internal/update/update_bins.cf
- standalone_self_upgrade.cf.in
- tests/unit/mock_lslpp_Lc
Solaris packages are no longer prefixed with 'cfengine.' and AIX packages are no
longer prefixed with 'CFE.'.
Ticket: ENT-9095
> ENT-9095: Updated filename conventions for AIX and Solaris packages

- tests/Makefile.am
The change is OK now because the selection of the files is more careful
after a recent change, quoting @craigcomstock:
> before I added the search for name `*.py and mock_*` it was running
> `sed -ri` on every file under that dir.
Platforms which don't support it are AIX 5 and HP-UX.
> Remove mindepth argument from find since not all platforms support it

- cfe_internal/update/windows_unattended_upgrade.cf
If the package upgrade fails, for example from trying to install a package that
was expected to be present but is missing, cf-execd will not be running, and the
host will not make further attempts to upgrade.
This change attempts to start cf-execd if it is not running after attempting the
package upgrade.
Ticket: ENT-9573
> ENT-9573: Added check to make sure cf-execd is running after attempting self upgrade on Windows

- cfe_internal/update/windows_unattended_upgrade.cf
If the package upgrade fails, for example from trying to install a package that
was expected to be present but is missing, cf-execd will not be running, and the
host will not make further attempts to upgrade.
This change attempts to start cf-execd if it is not running after attempting the
package upgrade.
Ticket: ENT-9573
(cherry picked from commit af290e0798f6313c3f1aadbd9d1e032545bf85d5)
> ENT-9573: Added check to make sure cf-execd is running after attempting self upgrade on Windows (3.15)

- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
Has issues with rpm -U --force behavior being
different than previous releases. As well as
possibly the same issues as rhel-8 had when we
chose to skip this test on rhel-8.
Fix this in CFE-4096
Ticket: ENT-8824
https://github.com/cfengine/buildscripts/pull/1137
https://github.com/cfengine/system-testing/pull/462
https://github.com/cfengine/masterfiles/pull/2529
https://github.com/cfengine/core/pull/5111
> ENT-8824: Skip great package test on RHEL-9

- cfe_internal/enterprise/templates/httpd.conf.mustache
- https://github.com/cfengine/buildscripts/pull/1160
As part of SSL minification we stopped building support for compression. Apache
won't validate the configuration when the library does not support the
setting so it must not be active.
Ticket: ENT-8933
> ENT-8933: Disabled explicit setting for SSLCompression for Mission Portal Apache

- cfe_internal/enterprise/CFE_knowledge.cf
Handled by a higher level ldap directory promise now.
Ticket: ENT-9697
> ENT-9697: Removed no longer needed settings.ldap.php permissions promise

- cfe_internal/enterprise/CFE_knowledge.cf
Cycling permissions were introduced with ENT-9693 enforcing root:root 440 on ldap dir recursively.
Ticket: ENT-9697
(cherry picked from commit 0160045f572beec2af88187d5e3df2eb84b9b1b6)
> ENT-9697: Added exception for ldap directory perms for settings.ldap.php (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
Change due to ENT-8447 (Changed the default mode for directories from 755 to 700).
Ticket: ENT-9703
> ENT-9703: Added needed permissions for php/runalerts-stamp directories

- CHANGELOG.md
- ENT-9703 merged after changelog prepared.
- ENT-9693 needed whitespace fixup
> Changelog fixups for 3.21.0

- cfe_internal/enterprise/CFE_hub_specific.cf
Default dir perms of 700 caused problems for policy analyzer.
Ticket: ENT-8447
> ENT-8447: Adjusted permissions for policy analyzer dir

- .github/workflows/ci.yml
We will now test on master, 3.21.x and 3.18.x
3.15.x testing will stop as that series is EOL
Ticket: ENT-9433
> ENT-9433: Adjust github workflows(ci) after 3.21.0 release

- cfe_internal/enterprise/CFE_knowledge.cf
- templates/cf-runalerts.service.mustache
Without /. a file will be created. Without create => true no action is promised.
Ticket: ENT-9711
together:
https://github.com/cfengine/masterfiles/pull/2564
https://github.com/cfengine/core/pull/5136
> ENT-9711: Updated reference to explicitly create runalerts-stamp directory

- cfe_internal/enterprise/CFE_knowledge.cf
- templates/cf-runalerts.service.mustache
together:
https://github.com/cfengine/buildscripts/pull/1188
https://github.com/cfengine/masterfiles/pull/2569
https://github.com/cfengine/core/pull/5149
> ENT-9711: runalerts-stamp directory fixes (3.18)

- lib/files.cf
This change accounts for windows in the system_owned perms body.
Note: There is a limitation not being able to set file ownership to users other
than the executing user, so this would be expected to generate errors if
cf-agent is not run by Administrator.
Ticket: ENT-9778
> ENT-9778: Fixed body perms system_owned to account for Windows

- lib/files.cf
This change accounts for windows in the system_owned perms body.
Note: There is a limitation not being able to set file ownership to users other
than the executing user. Since users report said errors when this targets
Administrator or SYSTEM, the owner for Windows is explicitly excluded.
> ENT-9778: Fixed body perms system_owned to account for Windows (3.21)

- lib/files.cf
This change accounts for windows in the system_owned perms body.
Note: There is a limitation not being able to set file ownership to users other
than the executing user. Since users report said errors when this targets
Administrator or SYSTEM, the owner for Windows is explicitly excluded.
> ENT-9778: Fixed body perms system_owned to account for Windows (3.18)

- controls/def.cf
This changes the guard for setting runagent socket ownership (which uses ACLs)
for the case when the list of runagent socket users is not an empty list. This
allows for disablement by simply setting an empty list via augments.
Ticket: ENT-9535
> ENT-9535: Prevented management of runagent socket users when no users are listed

- controls/def.cf
This changes the guard for setting runagent socket ownership (which uses ACLs)
for the case when the list of runagent socket users is not an empty list. This
allows for disablement by simply setting an empty list via augments.
> ENT-9535: Prevented management of runagent socket users when no users are listed (3.21)

- controls/def.cf
This changes the guard for setting runagent socket ownership (which uses ACLs)
for the case when the list of runagent socket users is not an empty list. This
allows for disablement by simply setting an empty list via augments.
Ticket: ENT-9535
(cherry picked from commit c8de0d254345c8bb37c22caacd13ae812c527c62)
> ENT-9535: Prevented management of runagent socket users when no users are listed (3.18)

- inventory/any.cf
This change adds inventory for the policy version as defined in body common
control. It's helpful to be able to easily look up what policy version something
is running (assuming a user has not modified the value set during release).
(cherry picked from commit 77db7732d1cd00f63d8933986477c7a50d0983ae)
> ENT-9806: Added Inventory for Policy Version (3.21)

- inventory/any.cf
This change adds inventory for the policy version as defined in body common
control. It's helpful to be able to easily look up what policy version something
is running (assuming a user has not modified the value set during release).
(cherry picked from commit 77db7732d1cd00f63d8933986477c7a50d0983ae)
> ENT-9806: Added Inventory for Policy Version (3.18)

- promises.cf.in
I don't think that the fact that this was tested on 3.5.x at some point is
really useful. In fact, at this point reading a random snippet it sends me down
a thought path that the policy is quite old, perhaps from the 3.6 era. So, I
think it's best to simply redact this.
> Redacted old, useless comment

- promises.cf.in
I don't think that the fact that this was tested on 3.5.x at some point is
really useful. In fact, at this point reading a random snippet it sends me down
a thought path that the policy is quite old, perhaps from the 3.6 era. So, I
think it's best to simply redact this.
(cherry picked from commit 48e4ee55c61e80125db857bb65002e447a3c7ec7)
> Redacted old, useless comment (3.18)

- modules/promises/cfengine.py
- tests/acceptance/30_custom_promise_types/append_promises.py
- tests/acceptance/30_custom_promise_types/bodies.py
- tests/acceptance/30_custom_promise_types/copy_always_info.py
- tests/acceptance/30_custom_promise_types/copy_promises.py
- tests/acceptance/30_custom_promise_types/json_insert.py
- tests/acceptance/30_custom_promise_types/multiline_insert.py
- tests/acceptance/30_custom_promise_types/noop_promises.py
Updated in its upstream repo: cfengine/modules@ba6bae35b8493b0dc8 and the new version adds the 'meta' attribute for
validate/evaluate_promise() that we need to add to all our modules in tests.
> Update the cfengine.py library

- tests/acceptance/30_custom_promise_types/24_expireafter.cf
- tests/acceptance/30_custom_promise_types/24_expireafter.cf.sub
- tests/acceptance/30_custom_promise_types/slow_append_promises.py
Test that expireafter works with custom promise types.
Merge with:
- https://github.com/cfengine/core/pull/5080
> CFE-3435: Test expireafter works with custom promise types

- MPF.md
> ENT-9924: Added cf-hub to the list of components documented as being influenced by mpf_augments_control_enabled

- MPF.md
Ticket: ENT-9924
(cherry picked from commit dadfb77087a383a49ad8a9a3e27b0c0ea9eb0aea)
> ENT-9924: Added cf-hub to the list of components documented as being influenced by mpf_augments_control_enabled (3.18)

- MPF.md
Ticket: ENT-9924
(cherry picked from commit dadfb77087a383a49ad8a9a3e27b0c0ea9eb0aea)
> ENT-9924: Added cf-hub to the list of components documented as being influenced by mpf_augments_control_enabled (3.21)

- lib/packages.cf
- promises.cf.in
This version specific handling of windows package module handling from 3.14 and
prior is no longer relevant as they are no longer supported and were not
supported at the time of this series release.
Ticket: ENT-9948
> ENT-9948: Removed specific old CFEngine version package module handling for windows

- lib/packages.cf
- promises.cf.in
This version specific handling of windows package module handling from 3.14 and
prior is no longer relevant as they are no longer supported and were not
supported at the time of this series release.
> ENT-9948: Removed specific old CFEngine version package module handling for windows (3.21)

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
When a PR is merged a push event occurs and workflows are triggered.
At this time an empty ref: will default to master instead of the appropriate branch.
So include github.base_ref and github.ref as fallbacks.
Ticket: ENT-10172
> ENT-10172: Fixed workflow refs for push events

- controls/def.cf
We have observed this file growing quite large without bound, it needs to be managed.
> ENT-10192: Added ssl_request_log to list of hub log files (3.21)

- controls/def.cf
We have observed this file growing quite large without bound, it needs to be managed.
> ENT-10192: Added ssl_request_log to list of hub log files (3.18)

- cfe_internal/enterprise/federation/federation.cf
- cfe_internal/update/update_policy.cf
- lib/bundles.cf
`regline()` may throw an error in the event that the probed file does not exist,
as observed in CI in 3.18.x `error: In function "regline", error reading from file. (getline: No such file or directory)`
To avoid those errors this change guards against use of `regline()` in case of a
nonexistent at a high level. This instrumentation was not made deep inside
`edit_line` bundles as it may be useful to surface the potential error in some cases.
Ticket: ENT-9933
> ENT-9933: Added guards against using regline() in cases where a file may not exist (3.18)

- MPF.md
- lib/packages.cf
This change makes the number of minutes to wait between package cache updates
for some package_method bodies configurable via augments.
The package_method bodies affected by this include:
- body package_method pip(flags)
- body package_method npm(dir)
- body package_method npm_g
- body package_method brew(user)
- body package_method apt
- body package_method apt_get
- body package_method apt_get_permissive
- body package_method apt_get_release(release)
- body package_method dpkg_version(repo)
- body package_method rpm_version(repo)
- body package_method yum
- body package_method yum_rpm
- body package_method yum_rpm_permissive
- body package_method yum_rpm_enable_repo(repoid)
- body package_method yum_group
- body package_method rpm_filebased(path)
- body package_method ips
- body …
> CFE-4178: Made package cache refresh for common_knowledge.list_update_ifelapsed configurable

- MPF.md
- lib/packages.cf
This change makes the number of minutes to wait between package cache updates
for some package_method bodies configurable via augments.
The package_method bodies affected by this include:
- body package_method pip(flags)
- body package_method npm(dir)
- body package_method npm_g
- body package_method brew(user)
- body package_method apt
- body package_method apt_get
- body package_method apt_get_permissive
- body package_method apt_get_release(release)
- body package_method dpkg_version(repo)
- body package_method rpm_version(repo)
- body package_method yum
- body package_method yum_rpm
- body package_method yum_rpm_permissive
- body package_method yum_rpm_enable_repo(repoid)
- body package_method yum_group
- body package_method rpm_filebased(path)
- body package_method ips
- body …
> CFE-4178: Made package cache refresh for common_knowledge.list_update_ifelapsed configurable (3.21)

- MPF.md
- lib/packages.cf
This change makes the number of minutes to wait between package cache updates
for some package_method bodies configurable via augments.
The package_method bodies affected by this include:
- body package_method pip(flags)
- body package_method npm(dir)
- body package_method npm_g
- body package_method brew(user)
- body package_method apt
- body package_method apt_get
- body package_method apt_get_permissive
- body package_method apt_get_release(release)
- body package_method dpkg_version(repo)
- body package_method rpm_version(repo)
- body package_method yum
- body package_method yum_rpm
- body package_method yum_rpm_permissive
- body package_method yum_rpm_enable_repo(repoid)
- body package_method yum_group
- body package_method rpm_filebased(path)
- body package_method ips
- body …
> CFE-4178: Made package cache refresh for common_knowledge.list_update_ifelapsed configurable (3.18)

- templates/federated_reporting/dump.sh
It was found that with larger numbers of hosts and inventory data even with improvements to update_inventory() procedure in cfdb schema (change in nova) concurrency problems could still occur.
--serializable-deferrable option seems to help as well to cause pg_dump to wait for a consistent state in the database before proceeding with the dump.
Ticket: ENT-10214
> ENT-10214: Improved federated reporting dump concurrency with database

- templates/federated_reporting/dump.sh
It was found that with larger numbers of hosts and inventory data even with improvements to update_inventory() procedure in cfdb schema (change in nova) concurrency problems could still occur.
--serializable-deferrable option seems to help as well to cause pg_dump to wait for a consistent state in the database before proceeding with the dump.
Ticket: ENT-10214
(cherry picked from commit e9fe60941ccaea513c7e607d64fcf6d46e4d3b40)
> ENT-10214: Improved federated reporting dump concurrency with database (3.21)

- templates/federated_reporting/dump.sh
It was found that with larger numbers of hosts and inventory data even with improvements to update_inventory() procedure in cfdb schema (change in nova) concurrency problems could still occur.
--serializable-deferrable option seems to help as well to cause pg_dump to wait for a consistent state in the database before proceeding with the dump.
Ticket: ENT-10214
(cherry picked from commit e9fe60941ccaea513c7e607d64fcf6d46e4d3b40)
> ENT-10214: Improved federated reporting dump concurrency with database (3.18)

- prepare.sh
This makes it easier to "fix" masterfiles modules with wrong
version numbers. Can for example happen if there is something
non-standard with tags or .CFVERSION files. In such cases,
these env vars can be set from CFEngine Build steps, when
running the prepare.sh script, to force the correct version number.
> prepare.sh: Enabled setting release and version via env vars

- inventory/linux.cf
- inventory/redhat.cf
- promises.cf.in
Before, only redhat or redhat_derived systems were having package_inventory defined. This caused no software inventory to be reported to an enterprise hub for suse systems.
Previously a check was added for the yum package module written in python that the python version must be 3.x or greater than 2.4.
In this change we have refactored to check the python version for all linux cases of package_inventory.
This check seems sufficient for apt_get, yum and zypper, the three package modules written in python.
Ticket: ENT-10248
(cherry picked from commit 4ef65dec482fc4fe29cea7d0a04a1474d90eed4e)
> ENT-10248: Fixed suse package_inventory defaults (3.21)

- templates/federated_reporting/dump.sh
If the dump procedure happens to run either via cf-execd or via manual cf-agent -KI runs more often than the superhub attempts to import the ln command could fail.
In this case, adding -f (force) makes sense as the end result is the same and what we want: the feeder dump is linked to the proper place for each superhub.
Ticket: ENT-10274
(cherry picked from commit 1877e9a694c7e4525fb8bfec85221dbd191173e8)
> ENT-10274: Adjusted dump.sh for multiple runs in between superhub imports (3.18)

- templates/federated_reporting/dump.sh
If the dump procedure happens to run either via cf-execd or via manual cf-agent -KI runs more often than the superhub attempts to import the ln command could fail.
In this case, adding -f (force) makes sense as the end result is the same and what we want: the feeder dump is linked to the proper place for each superhub.
Ticket: ENT-10274
> ENT-10274: Adjusted dump.sh for multiple runs in between superhub imports

- prepare.sh
These changes make the cfbs build result for masterfiles align with the
masterfiles tarball that is part of the release.
> ENT-10345: Aligned module build result with release artifact (3.18)

- CHANGELOG.md
- CHANGELOG.md: Removed heading
- CHANGELOG.md: Fixed inconsistent use of tabs and spaces
- CHANGELOG.md: Fixed various typos
> Changelog cleanups

- promises.cf.in
Every time I look at the promises.cf, the uneven indentation of the comments in promises.cf triggers my OCD. :wink:
> Fix indentation in promises.cf.in

- .github/workflows/valgrind.yml
(cherry picked from commit ee456bdb8e6f629f5482f77c9bbcb9a544588447)
> GH actions: Fixed valgrind typo (valgring) (3.18)

- cfe_internal/update/update_policy.cf
If you build CFEngine with --enable-fhs then sys.bindir is going to be /usr/bin
and cleaning up the cfengine selected python symlink that could have been left
would result in cleaning up the system python symlink instead. This change
scopes the cleanup down to only when sys.bindir is /var/cfengine/bin.
Ticket: CFE-4146
> CFE-4146: Avoided deleting python symlink when sys.bindir is not /var/cfengine/bin

- cfe_internal/recommendations.cf
Misspelled `policies` in `cfengine_internal_purge_polices` in the report message.
> cfengine_internal_purge_policies typo.

- inventory/any.cf
Before, the cache file was not created because the variable in the regcmp was not readable.
$(response[content][version]) was not working for me.
cfe_autorun_inventory_aws_ec2_metadata_cache writes $(response[content]) to the cache file and
in cfe_aws_ec2_metadata_from_cache readjson is used to consume the cache file.
So I added a parsejson and now it is working and the cache file get's created.
> CFE-4221: fix cfe_autorun_inventory_aws_ec2_metadata_cache

- inventory/any.cf
Before, the cache file was not created because the variable in the regcmp was
not referenceable. default:cfe_autorun_inventory_aws_ec2_metadata_cache.response
is a data container. It's content key is a string, as such, it's not possible to
dereference $(response[content][version]) directly. $(response[content]) must be
extracted into a data container which can be referenced.
Changelog: Fixed cfe_autorun_inventory_aws_ec2_metadata_cache file creation
Ticket: CFE-4221
Signed-off-by: Andreas Gerler <baron@bundesbrandschatzamt.de>
(cherry picked from commit 142468448d1c2b113e7a3ff2a498102d2d600db9)
> CFE-4221: Fixed cfe_autorun_inventory_aws_ec2_metadata_cache (3.21)

- inventory/any.cf
Before, the cache file was not created because the variable in the regcmp was
not referenceable. default:cfe_autorun_inventory_aws_ec2_metadata_cache.response
is a data container. It's content key is a string, as such, it's not possible to
dereference $(response[content][version]) directly. $(response[content]) must be
extracted into a data container which can be referenced.
Changelog: Fixed cfe_autorun_inventory_aws_ec2_metadata_cache file creation
Ticket: CFE-4221
Signed-off-by: Andreas Gerler <baron@bundesbrandschatzamt.de>
(cherry picked from commit 142468448d1c2b113e7a3ff2a498102d2d600db9)
> CFE-4221: Fixed cfe_autorun_inventory_aws_ec2_metadata_cache (3.18)

- cfe_internal/recommendations.cf
Misspelled `policies` in `cfengine_internal_purge_polices` in the
report message.
(cherry picked from commit 2adb02c926f41b98aae71e39783fec59e51c58b9)
> CFE-4224: cfengine_internal_purge_policies typo. (3.21)

- cfe_internal/recommendations.cf
Misspelled `policies` in `cfengine_internal_purge_polices` in the
report message.
(cherry picked from commit 2adb02c926f41b98aae71e39783fec59e51c58b9)
> CFE-4224: cfengine_internal_purge_policies typo. (3.18)

- cfe_internal/update/update_policy.cf
As $(sys.bindir) might point to /usr/bin filtering it can lead to missing an available python executeable.
The orginal reason to do so was to avoid a self referential link (https://github.com/cfengine/masterfiles/commit/d37c6d1929913d8cb9b269ce02ec823ade29b440)
Since the symlink is now named `cfengine-selected-python` (https://github.com/cfengine/masterfiles/commit/a864d5cced81b37cf0f0ed9e61d392bd6ed96194) it is not matched by the regex anymore and therefor not an issue.
> CFE-4223: do not filter $(sys.bindir) from python path

- inventory/any.cf
CFEngine 3.10 and 3.11 are long out of support, no need to carry this
considerations forward.
Ticket: CFE-4222
> CFE-4222: Removed considerations for old versions from bundle agent cfe_autorun_inventory_aws_ec2_metadata_cache

- inventory/any.cf
CFEngine 3.10 and 3.11 are long out of support, no need to carry this
considerations forward.
Ticket: CFE-4222
(cherry picked from commit c42cce1215e5684a28920f2c19fbda8c6ec6793b)
> CFE-4222: Removed considerations for old versions from bundle agent cfe_autorun_inventory_aws_ec2_metadata_cache (3.21)

- inventory/any.cf
CFEngine 3.10 and 3.11 are long out of support, no need to carry this
considerations forward.
Ticket: CFE-4222
(cherry picked from commit c42cce1215e5684a28920f2c19fbda8c6ec6793b)
> CFE-4222: Removed considerations for old versions from bundle agent cfe_autorun_inventory_aws_ec2_metadata_cache (3.18)

- cfe_internal/update/update_policy.cf
As $(sys.bindir) might point to /usr/bin filtering it can lead to missing
an avaiable python executable. The filter was originally in place to avoid
creation of a self-referential link where /var/cfengine/bin/python would link to
itself. That symlink name has since been changed to
/var/cfengine/bin/cfengine-selected-python so it is no longer a concern
Ticket: CFE-4223
(cherry picked from commit de5e41cbc7fe39feb9c441b40253f97313625916)
> CFE-4223: Stopped filtering $(sys.bindir) from dynamically determined python path (3.21)

- cfe_internal/update/update_policy.cf
As $(sys.bindir) might point to /usr/bin filtering it can lead to missing
an avaiable python executable. The filter was originally in place to avoid
creation of a self-referential link where /var/cfengine/bin/python would link to
itself. That symlink name has since been changed to
/var/cfengine/bin/cfengine-selected-python so it is no longer a concern
Ticket: CFE-4223
(cherry picked from commit de5e41cbc7fe39feb9c441b40253f97313625916)
> CFE-4223: Stopped filtering $(sys.bindir) from dynamically determined python path (3.18)

- .github/workflows/ci.yml
We don't have easy visibility on the results of these events which only occur after we merge pull requests.
We use /merge refs in pull requests so running the actions again on push events (after the merge) don't really provide any additional information.
Pushes/commits to pull requests are handled by the pull_request event so no change there.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Ticket: ENT-10428
> ENT-10428: Removed push event handling in github actions workflow 

- .github/workflows/ci.yml
We don't have easy visibility on the results of these events which only occur after we merge pull requests.
We use /merge refs in pull requests so running the actions again on push events (after the merge) don't really provide any additional information.
Pushes/commits to pull requests are handled by the pull_request event so no change there.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Ticket: ENT-10428
(cherry picked from commit 030afdc99d8dd3fc6de18290a63095d00a929815)
Conflicts:
.github/workflows/ci.yml
But nothing significant in the conflict, the branches were different but we are removing the entire push event handler.
> ENT-10428: Removed push event handling in github actions workflow (3.18)

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
We control the code, so no need to be "careful" here.
Ticket: ENT-10442
> ENT-10442: Switch together-javascript-action to main to avoid dependency update work

- MPF.md
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
This change adds the ability to extend the default list of filename patterns to
copy during policy update. Prior to this you could only re-define the list of
filename patterns which adds a maintenance burden of tracking the upstream
defaults through policy framework upgrades.
> ENT-10480: Added ability to extend without overriding filename patterns to copy during policy update

- MPF.md
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
This change adds the ability to extend the default list of filename patterns to
copy during policy update. Prior to this you could only re-define the list of
filename patterns which adds a maintenance burden of tracking the upstream
defaults through policy framework upgrades.
> ENT-10480: Added ability to extend without overriding filename patterns to copy during policy update (3.21)

- MPF.md
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
This change adds the ability to extend the default list of filename patterns to
copy during policy update. Prior to this you could only re-define the list of
filename patterns which adds a maintenance burden of tracking the upstream
defaults through policy framework upgrades.
> ENT-10480: Added ability to extend without overriding filename patterns to copy during policy update (3.18)

- lib/testing.cf
Though one issue remains: testing_todo() and testing_skip()
don't quite act correctly. They should report ok|not ok followed
by # SKIP or # TODO at the end of the test point line.
https://testanything.org/tap-version-14-specification.html
see https://northerntech.atlassian.net/browse/CFE-4246
Ticket: CFE-4245
> CFE-4245: Fixed lib/testing.cf tap output

- lib/testing.cf
- Removed jq dependency in lib/testing.cf and fixed tap output
- Fixed lib/testing.cf tap output
> CFE-4245/CFE-4242: Fix lib/testing.cf jq dep and tap output (3.18)

- inventory/any.cf
On a centos-6 PV instance in Amazon EC2 I see /sys/hypervisor/uuid exists
-r--r--r-- 1 root root 4096 Sep  1 14:30 /sys/hypervisor/uuid
but is not readable even though permissions seem to be ok.
cat: /sys/hypervisor/uuid: No such file or directory
While SELinux is enforced it doesn't seem to be involved since this is a special sysfs filesystem and there are no entries for the failure in the audit log.
> ENT-9931: Guard against /sys/hypervisor/uuid not being readable

- inventory/any.cf
- Guard against /sys/hypervisor/uuid not being readable
- can squash this one, use isreadable() if available
> ENT-9931: Guard against /sys/hypervisor/uuid not being readable (3.18)

- inventory/any.cf
On a centos-6 PV instance in Amazon EC2 I see /sys/hypervisor/uuid exists
-r--r--r-- 1 root root 4096 Sep  1 14:30 /sys/hypervisor/uuid
but is not readable even though permissions seem to be ok.
cat: /sys/hypervisor/uuid: No such file or directory
While SELinux is enforced it doesn't seem to be involved since this is a special sysfs filesystem and there are no entries for the failure in the audit log.
(cherry picked from commit 612323d74dfde4d9d3b319a218f835f45a011cb6)
> ENT-9931: Guard against /sys/hypervisor/uuid not being readable (3.21)

- inventory/any.cf
This will only occur in pre 3.22.0 versions of CFEngine.
In 3.22.0 and after the isreadable() function is used.
Problem found with our no-noise-test showing the output of the uuid.
(cherry picked from commit 38c4ff3072208bfd27cfda09dfdf0ad493408cfc)
> ENT-9931: Redirected all output when checking /sys/hypervisor/uuid with cat (3.18)

- inventory/any.cf
This will only occur in pre 3.22.0 versions of CFEngine.
In 3.22.0 and after the isreadable() function is used.
Problem found with our no-noise-test showing the output of the uuid.
(cherry picked from commit 38c4ff3072208bfd27cfda09dfdf0ad493408cfc)
> ENT-9931: Redirected all output when checking /sys/hypervisor/uuid with cat (3.21)

- inventory/any.cf
The 2>&1 and >/dev/null were in the wrong order.
(cherry picked from commit e23a185e4495b7fab0b548e16692fa1809644447)
> ENT-9931: Fixed /sys/hypervisor/uuid is readable test for pre 3.22.0 versions (3.21)

- tests/acceptance/30_custom_promise_types/24_expireafter.cf
> ENT-10623: Marked 30_custom_promise_types/24_expireafter as flakey fail for aarch64 debian_11

- tests/acceptance/17_packages/12_new/timed/installed-list-cached.cf
> ENT-9601: Added flakey fail for 17_packages/12_new/timed/installed-list-cached.cf test on aarch64.debian_11

- inventory/any.cf
The @else and other nice macros were not available in 3.12, so to protect
against erroring on a file that is sometimes not readable we switched to a
combination of @if minimum_version and class guards.
Ticket: ENT-10639
> ENT-10639: Made protection against unreadable uuid compatible to 3.12 (3.18)

- tests/acceptance/17_packages/12_new/timed/installed-list-cached.cf
Ticket: ENT-9601
(cherry picked from commit 46ac75658a6130924a8dca098100c492cbfaf5ac)
> ENT-9601: Added flakey fail for 17_packages/12_new/timed/installed-list-cached.cf test on aarch64.debian_11 (3.21)

- tests/acceptance/17_packages/12_new/timed/installed-list-cached.cf
Ticket: ENT-9601
(cherry picked from commit 46ac75658a6130924a8dca098100c492cbfaf5ac)
> ENT-9601: Added flakey fail for 17_packages/12_new/timed/installed-list-cached.cf test on aarch64.debian_11 (3.18)

- CHANGELOG.md
- cfe_internal/enterprise/mission_portal.cf
This change ensures that a manual change to httpd.conf is reverted as long as
the staged template render is still valid and that httpd gets re-started as
necessary to ensure it's running with the expected configuration.
Ticket: ENT-9686
(cherry picked from commit 6ce87ef79c1b44f062f85e83db04abe90980320e)
> ENT-9698: Ensured manual edits to httpd.conf are reverted (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
The condition was inverted. It should be enabled by default unless the class to
disable it is defined.
Ticket: ENT-10672
> ENT-10672: Fixed apache listening on port 80 by default

- cfe_internal/enterprise/templates/httpd.conf.mustache
The condition was inverted. It should be enabled by default unless the class to
disable it is defined.
Ticket: ENT-10672
(cherry picked from commit 19f113cc747e0fb9d253dbef5d0c8e02a9a128b7)
> ENT-10672: Fixed apache listening on port 80 by default (3.21)

- cfe_internal/enterprise/templates/httpd.conf.mustache
The condition was inverted. It should be enabled by default unless the class to
disable it is defined.
Ticket: ENT-10672
(cherry picked from commit 19f113cc747e0fb9d253dbef5d0c8e02a9a128b7)
> ENT-10672: Fixed apache listening on port 80 by default (3.18)

- standalone_self_upgrade.cf.in
CFEngine uses arm_64 instead of aarch64 to identify 64 bit arm builds. Without
this change arm64 client's look for their packages in the wrong directory.
Ticket: ENT-10816
> ENT-10816: Fixed self-upgrade for Debian and Ubuntu aarch64 clients

- standalone_self_upgrade.cf.in
CFEngine uses arm_64 instead of aarch64 to identify 64 bit arm builds. Without
this change arm64 client's look for their packages in the wrong directory.
Ticket: ENT-10816
(cherry picked from commit 8d3a327510ac2cfd7bdf2b2e19f6f54f128dc658)
> ENT-10816: Fixed self-upgrade for Debian and Ubuntu aarch64 clients (3.21)

- standalone_self_upgrade.cf.in
CFEngine uses arm_64 instead of aarch64 to identify 64 bit arm builds. Without
this change arm64 client's look for their packages in the wrong directory.
Ticket: ENT-10816
(cherry picked from commit 8d3a327510ac2cfd7bdf2b2e19f6f54f128dc658)
> ENT-10816: Fixed self-upgrade for Debian and Ubuntu aarch64 clients (3.18)

- inventory/os.cf
Prior to this change an Amazon Linux 2 host would have OS set to Unknown Unknown
since both sys.os_name_human and sys.os_version_major resolved to Unknown.
Ticket: ENT-10817
> ENT-10817: Fixed OS inventory for Amazon Linux 2

- standalone_self_upgrade.cf.in
Prior to this change two things did not work:
- The hub would not download the el7 package to an amazon linux 2 directory
- Clients tried to get the package from AmazonLinux_<arch>
With this change:
- The hub downloads the el7 package to the amazon_2_<arch> directory
- The client looks for the package in amazon_2_<arch>.
Ticket: ENT-10820
> ENT-10820: Added self upgrade support for Amazon Linux 2

- standalone_self_upgrade.cf.in
Prior to this change two things did not work:
- The hub would not download the el7 package to an amazon linux 2 directory
- Clients tried to get the package from AmazonLinux_<arch>
With this change:
- The hub downloads the el7 package to the amazon_2_<arch> directory
- The client looks for the package in amazon_2_<arch>.
Ticket: ENT-10820
(cherry picked from commit 7d93ed1851c2da5a1aa922ecbf5e34cdcf86edf9)
> ENT-10820: Added self upgrade support for Amazon Linux 2 (3.21)

- standalone_self_upgrade.cf.in
Prior to this change two things did not work:
- The hub would not download the el7 package to an amazon linux 2 directory
- Clients tried to get the package from AmazonLinux_<arch>
With this change:
- The hub downloads the el7 package to the amazon_2_<arch> directory
- The client looks for the package in amazon_2_<arch>.
Ticket: ENT-10820
(cherry picked from commit 7d93ed1851c2da5a1aa922ecbf5e34cdcf86edf9)
> ENT-10820: Added self upgrade support for Amazon Linux 2 (3.18)

- MPF.md
- cfe_internal/recommendations.cf
- https://github.com/cfengine/core/pull/5357
- https://github.com/cfengine/documentation/pull/3102
> ENT-9402: Added policy to facilitate migration of ignore_interfaces.rx from inputdir to workdir

- templates/cf-apache.service.mustache
- templates/cf-execd.service.mustache
- templates/cf-hub.service.mustache
- templates/cf-monitord.service.mustache
- templates/cf-postgres.service.mustache
- templates/cf-runalerts.service.mustache
- templates/cf-serverd.service.mustache
WantedBy=cfengine3.service was removed from systemd service templates for individual components. It was un-necessary as cfengine3.service already wants the individual services.
https://github.com/cfengine/core/pull/5362
Ticket: CFE-3982
Changelog: commit
(cherry picked from commit 4e490e71683a81d8aae8bccb8b16d1b183a4bdd2)
> [3.21.x] Aligned systemd service templates with core

- templates/cf-apache.service.mustache
- templates/cf-execd.service.mustache
- templates/cf-hub.service.mustache
- templates/cf-monitord.service.mustache
- templates/cf-postgres.service.mustache
- templates/cf-runalerts.service.mustache
- templates/cf-serverd.service.mustache
WantedBy=cfengine3.service was removed from systemd service templates for individual components. It was un-necessary as cfengine3.service already wants the individual services.
https://github.com/cfengine/core/pull/5362
Ticket: CFE-3982
Changelog: commit
(cherry picked from commit 4e490e71683a81d8aae8bccb8b16d1b183a4bdd2)
> [3.18.x] Aligned systemd service templates with core

- MPF.md
- cfe_internal/CFE_cfengine.cf
- cfe_internal/recommendations.cf
This change restricts the policy from running for CFEngine versions where
ignore_interfaces.rx can not be read from WORKDIR.
Ticket: ENT-9402
> ENT-9402: Refactored ignore_interfaces.rx policy for backport

- cfe_internal/CFE_cfengine.cf
Prior to this change the bundles were not found and run as expected.
Ticket: ENT-10915
(cherry picked from commit e0fe4e5c58deaa0a214811376ab4d93037c921c4)
> ENT-10915: Fixed execution of recommendation policy (3.18)

- cfe_internal/recommendations.cf
This change makes the policy look in the correct place for the configuration
file and limits reports. No longer printing the full postgresql.conf and only
printing settings that we have derived recommendations for.
Ticket: ENT-10916
> ENT-10916: Fixed recommendation policy for postgresql.conf in CFEngine Enterprise

- cfe_internal/recommendations.cf
This change makes the policy look in the correct place for the configuration
file and limits reports. No longer printing the full postgresql.conf and only
printing settings that we have derived recommendations for.
Ticket: ENT-10916
(cherry picked from commit 362e2092f108a8c2617564fcc211b475d8c637d0)
> ENT-10916: Fixed recommendation policy for postgresql.conf in CFEngine Enterprise (3.21)

- cfe_internal/recommendations.cf
This change makes the policy look in the correct place for the configuration
file and limits reports. No longer printing the full postgresql.conf and only
printing settings that we have derived recommendations for.
Ticket: ENT-10916
(cherry picked from commit 362e2092f108a8c2617564fcc211b475d8c637d0)
> ENT-10916: Fixed recommendation policy for postgresql.conf in CFEngine Enterprise (3.18)

- MPF.md
This simply adds the versions it was back-ported to.
Ticket: ENT-10917
> ENT-10917: Fixed history for default:def.cfe_enterprise_mission_portal_apache_sslprotocol

- MPF.md
This simply adds the versions it was back-ported to.
Ticket: ENT-10917
(cherry picked from commit 0e537cfe323d516f2b1707c39580b030096cf622)
> ENT-10917: Fixed history for default:def.cfe_enterprise_mission_portal_apache_sslprotocol (3.21)

- MPF.md
This removes the reference for 3.22.3 which never existed and sets 3.21.3 appropriately.
Ticket: ENT-10917
(cherry picked from commit 0e537cfe323d516f2b1707c39580b030096cf622)
> ENT-10917: Fixed history for default:def.cfe_enterprise_mission_portal_apache_sslprotocol (3.18)

- cfe_internal/update/update_policy.cf
- modules/mustache/README.md
- https://github.com/cfengine/documentation/pull/3110
With this change mustache templates found in modules/mustache (relative to the
root of the policy set) are rendered to $(sys.workdir)/modules using datastate()
from the update.cf policy entry.
Ticket: ENT-10793
> ENT-10793: Added rendering of custom mustache templates to $(sys.workdir)/modules

- cfe_internal/enterprise/federation/federation.cf
This change let's rocky 9 and redhat 9 hosts know which package contains
semanage so that it can be automatically installed for managing permissions in
federated reporting.
Ticket: ENT-10918
> ENT-10918: Fixed support for automatically installing semanage on el9 for federated reporting

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
This change let's rocky 9 and redhat 9 hosts know which package contains
semanage so that it can be automatically installed for managing permissions in
federated reporting.
> ENT-10918: Fixed support for automatically installing semanage on el9 for federated reporting (3.21)

- templates/federated_reporting/dump.sh
- templates/federated_reporting/import.sh
If an environment has SET commands in psqlrc or ~/.psqlrc then output can include the SET response and break parsing.
Ticket: ENT-10904
> ENT-10904: Added --quiet to psql commands where needed in federated reporting scripts

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
Saves full log in /var/cfengine/outputs
TODO: clean up old /var/cfengine/outputs/*-schema-attach-*.log files
Ticket: ENT-10789
> ENT-10921: Improved failure logging during federated reporting schema import

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
This change more specifically includes the hubs ip address in the default acl, allowconnects and allowallconnects.
sys.policy_hub/16 remains the default for def.acl, but new _derived suffixed variables which are used in the final configuration have been added.
Previously, setting acl, allowconnects, or allowallconnects and omitting the policy server would prevent the policy server from accessing it's own resources. Recovery from this mistake was tedious. Now, the policy server ip address is joined with the configured values for acl, allowconnects, and allowallconnects in the new _derived suffixed variables so that the policy servers IP is always included unless a class disabling the behavior is defined.
> ENT-10951: Automatically include $(sys.policy_hub) in acl, allowconnects, allowallconnects

- cfe_internal/enterprise/federation/federation.cf
Previously we did not check if the cftransport ssh fcontext was already added.
Now we check before trying to add this fcontext.
Also split up the management of the fcontext from  applying the changes with restorecon.
Ticket: ENT-10959
with https://github.com/cfengine/system-testing/pull/514
> ENT-10959: Improved federation policy handling of cftransport selinux configuration

- cfe_internal/enterprise/federation/federation.cf
Previously we did not check if the cftransport ssh fcontext was already added.
Now we check before trying to add this fcontext.
Also split up the management of the fcontext from  applying the changes with restorecon.
Ticket: ENT-10959
(cherry picked from commit 2f7b1d8dac854c650845522d1c060e92b15be687)
> ENT-10959: Improved federation policy handling of cftransport selinux configuration (3.21)

- cfe_internal/enterprise/federation/federation.cf
Previously we did not check if the cftransport ssh fcontext was already added.
Now we check before trying to add this fcontext.
Also split up the management of the fcontext from  applying the changes with restorecon.
Ticket: ENT-10959
(cherry picked from commit 2f7b1d8dac854c650845522d1c060e92b15be687)
> ENT-10959: Improved federation policy handling of cftransport selinux configuration (3.18)

- cfe_internal/enterprise/federation/federation.cf
python3 and urllib3 module are only needed on superhub
(cherry picked from commit 13b60c5ba76ff37f9a5130a6a9824973a27fae5e)
(cherry picked from commit b83eaea0119bcaaaeb15beb58698925155502354)
> ENT-10960: Adjusted distributed cleanup dependencies policy to only superhub where it is needed (3.18)

- cfe_internal/enterprise/federation/federation.cf
python3 and urllib3 module are only needed on superhub
(cherry picked from commit 13b60c5ba76ff37f9a5130a6a9824973a27fae5e)
(cherry picked from commit b83eaea0119bcaaaeb15beb58698925155502354)
> ENT-10960: Adjusted distributed cleanup dependencies policy to only superhub where it is needed (3.21)

- cfe_internal/enterprise/federation/federation.cf
Only superhub needs distributed_cleanup_dependencies bundle run.
rhel-8 has special package name for python3, python36.
> ENT-10960: Fixed distributed_cleanup policy for feeders and rhel-8 superhubs 

- cfe_internal/enterprise/federation/federation.cf
Only superhub needs distributed_cleanup_dependencies bundle run.
rhel-8 has special package name for python3, python36.
Co-authored-by: Nick Anderson <nick@cmdln.org>
(cherry picked from commit 4d956c055a97fe0936fa345d96f862475f93d828)
Conflicts:
cfe_internal/enterprise/federation/federation.cf
3.18.x does not support rhel-9
> ENT-10960: Fixed distributed_cleanup policy for feeders and rhel-8 superhubs (3.18)

- cfe_internal/enterprise/federation/federation.cf
Only superhub needs distributed_cleanup_dependencies bundle run.
rhel-8 has special package name for python3, python36.
Co-authored-by: Nick Anderson <nick@cmdln.org>
(cherry picked from commit 4d956c055a97fe0936fa345d96f862475f93d828)
> ENT-10960: Fixed distributed_cleanup policy for feeders and rhel-8 superhubs (3.21)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-10900
(cherry picked from commit 4811105e71c5d509b242f04f1a0b36607669cf86)
> ENT-10900: Made enterprise federated reporting dump interval configurable via Augments (3.21)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-10900
(cherry picked from commit 4811105e71c5d509b242f04f1a0b36607669cf86)
> ENT-10900: Made enterprise federated reporting dump interval configurable via Augments (3.18)

- cfe_internal/enterprise/mission_portal.cf
We don't enable the cf-apache.service, it's started by the cfengine3 umbrella service as its (weak) dependency. So only the cfengine3 service is enabled normally.
Ticket: ENT-11130
> Check if cf-apache.service is active to see if it's systemd-managed

- cfe_internal/enterprise/mission_portal.cf
We don't enable the cf-apache.service, it's started by the
cfengine3 umbrella service as its (weak) dependency. So only the
cfengine3 service is enabled normally.
Ticket: ENT-11130
(cherry picked from commit 21c698ab09075038838328b549e5e166fa95fe50)
> ENT-11130: Check if cf-apache.service is active to see if it's systemd-managed (3.21)

- cfe_internal/enterprise/mission_portal.cf
We don't enable the cf-apache.service, it's started by the
cfengine3 umbrella service as its (weak) dependency. So only the
cfengine3 service is enabled normally.
Ticket: ENT-11130
(cherry picked from commit 21c698ab09075038838328b549e5e166fa95fe50)
> ENT-11130: Check if cf-apache.service is active to see if it's systemd-managed (3.18)

- cfe_internal/enterprise/federation/federation.cf
Multiple issues discovered and fixed. Plus one piece of polishing.
> Fixes for FR policy fixing up SELinux context of ~cftransport/.ssh

- cfe_internal/enterprise/federation/federation.cf
Now that whitespaces are preserved in the `arglist` attribute of the `commands` promises, we no longer need to use extra quotes. In fact, these quotes become a part of the argument, causing some methods to fail in the MPF.
Merge together with:
- https://github.com/cfengine/core/pull/5378
- https://github.com/cfengine/enterprise/pull/775
> CFE-2724: Removed quotes from `arglist` attribute in `commands` promises

- cfe_internal/enterprise/mission_portal.cf
See also: https://github.com/cfengine/buildscripts/pull/1345
Ticket: ENT-11096
> ENT-11096: Policy now manages Mission Portals httpd.conf ownership and permissions

- Makefile.am
Should be run after CFEngine is installed but before running or developing policy.
Installing stdlib as this does will aid in local non-priv development/checking of policy.
Ticket: none
> Added an initial non-priv-install target for masterfiles

- lib/packages.cf
Using opensuse leap 15 I get only the opensuse class.
In order to use default package_method generic we must add the opensuse class guard there.
Other policy in lib/packages.cf has been adjusted in a similar way.
Ticket: none
> Added opensuse class to lib/packages.cf policy

- inventory/any.cf
This change aims to fix policy compatibility between 3.18.x and 3.15.x by
guarding the policy with a macro to prevent agents older than 3.18.0 from
evaluating policy which uses features the agent is not capable of.
While 3.15.x has been out of support since December 31st 2022 we strive to minimize
any pain in upgrading. The change that introduced this issue extended ec2
metadata to support and prefer imdsv2 uses a function, validjson() and an
attribute, content which were first introduced in 3.16.0.
Ticket: ENT-11178
> ENT-11178: Fixed policy compatibility with 3.15.x, disabled aws ec2 inventory for versions less than 3.18.0 (3.18.x)

- lib/packages.cf
Using opensuse leap 15 I get only the opensuse class.
In order to use default package_method generic we must add the opensuse class guard there.
Other policy in lib/packages.cf has been adjusted in a similar way.
Ticket: none
(cherry picked from commit 482bb20141078e65c6bf904ff206c093f4cf89a4)
> Added opensuse class to lib/packages.cf policy (3.18)

- lib/packages.cf
Using opensuse leap 15 I get only the opensuse class.
In order to use default package_method generic we must add the opensuse class guard there.
Other policy in lib/packages.cf has been adjusted in a similar way.
Ticket: none
(cherry picked from commit 482bb20141078e65c6bf904ff206c093f4cf89a4)
> Added opensuse class to lib/packages.cf policy (3.21)

- lib/common.cf
> Clarify that if_ok classes body is defined if promise is kept or repaired (not could be repaired)

- cfe_internal/core/main.cf
These have not been working due to missing `reports:` after the `@endif`. @nickanderson says we might as well remove them, since they are unnecessary.
Backport to:
> main.cf: Removed `reports` promises from `mpf_augments_control` bundle

- cfe_internal/core/main.cf
These have not been working due to missing `reports:` after the `@endif`. @nickanderson says we might as well remove them, since they are unnecessary.
Backported from https://github.com/cfengine/masterfiles/pull/2825
> main.cf: Removed `reports` promises from `mpf_augments_control` bundle (3.21.x)

- cfe_internal/core/main.cf
These have not been working due to missing `reports:` after the `@endif`. @nickanderson says we might as well remove them, since they are unnecessary.
Backported from https://github.com/cfengine/masterfiles/pull/2825
> main.cf: Removed `reports` promises from `mpf_augments_control` bundle (3.18.x)

- MPF.md
- lib/packages.cf
- promises.cf.in
see discussion here -> https://groups.google.com/g/help-cfengine/c/jzDzekirYTY
the changes made here enables the package inventory for yum/rpm packages in aix through augments, but there are some unwanted inventory files beside the working ones created in the state directory. this needs to be reviewed by some cfengine expert, as i am unable to figure out whats the reason behind this.
files used for testing:
https://github.com/flynn1973/cfengine_aix_yum
> CFE-3612: enable yum package inventory in aix

- lib/services.cf
On FreeBSD service commands only work if a service has been enabled in
/etc/rc.conf. If it has not been enabled then a services promise with a
service_policy of "start" or "stop" results in a failure to change the system
state during each agent execution. Switching to "one" prefixed commands, e.g.
onestatus, onestop, and onestart allows services that are not enabled to still
be managed and does not interfere with services that have been enabled in
/etc/rc.conf.
Ticket: CFE-4323
> CFE-4323: FreeBSD service management now uses one prefixed service commands

- CHANGELOG.md
- MPF.md
This file is shown in our docs and could use a cleanup.
Went over this file trying to fix as many obvious / easy inconsistencies as I could:
* Removed the use of h1, h5 and h6 headings.
* Added JSON highlighting to code blocks.
* Fixed invalid JSON (trailing commas, missing colons).
* Fixed inconsistent indentation / formatting of code blocks.
* Fixed capitalization of several headers to use sentence case.
* Fixed capitalization of CFEngine, HTTP, HTTPS, etc. in a few places.
* Added monospace font for binaries; cf-serverd, etc.
* Fixed inconsistent markdown syntax (especially what should be bold and which symbols to use for bulleted lists).
* Fixed small typos / grammer mistakes.
* Renamed some headings to make them easier to understand.
Ticket: ENT-11371
> ENT-11371 MPF.md: Fixed many inconsistencies

- cfe_internal/core/watchdog/templates/watchdog.mustache
Ticket: CFE-4335
Changelog: AIX watchdog now handles stale pids
Code uses /proc opportunistically only if it exists; this improves
accuracy for systems with /proc and doesn't affect other systems.
(Turns out this doesn't matter as the template is only for AIX which
does have /proc)
This leaves in place a race condition if many watchdog processes are
started in very short succession, since the pidfile is not atomically
checked and updated.  For purposes of the watchdog this is probably good
enough.  (See https://stackoverflow.com/a/688365/5419599 for more on
this.)
(cherry picked from commit f53436b11d12573ec7c49dc677c68fbecbcfc2d3)
> CFE-4335: Made AIX watchdog ignore stale pidfiles (3.21)

- MPF.md
This has been available since 3.21.2 as well.
> ENT-11396: Fixed history for default:def.control_common_tls_min_version

- MPF.md
This has been available since 3.21.2
Ticket: ENT-11395
> ENT-11395: Fixed history for default:def.control_common_tls_ciphers

- MPF.md
This has been available since 3.21.2
Ticket: ENT-11395
(cherry picked from commit 1f7faf06c784847ec3086e52a0f94fdb2d43587a)
> ENT-11395: Fixed history for default:def.control_common_tls_ciphers (3.21)

- inventory/os.cf
https://github.com/cfengine/core/pull/5460
https://github.com/cfengine/masterfiles/pull/2850
> CFE-4342: When failing to detect platform, inventory attribute "OS" now defaults to PRETTY_NAME from os-release as a fallback

- modules/packages/vendored/apt_get.mustache
Starting with python 3.12 using backslashes generate warnings and will be escalated to errors in a future release.
https://docs.python.org/3/library/re.html
> Regular expressions use the backslash character ('\') to indicate special forms or to allow special characters to be used without invoking their special meaning. This collides with Python’s usage of the same character for the same purpose in string literals; for example, to match a literal backslash, one might have to write '\\\\' as the pattern string, because the regular expression must be \\, and each backslash must be expressed as \\ inside a regular Python string literal. Also, please note that any invalid escape sequences in Python’s usage of the backslash in string literals now generate a …
> CFE-4359: Update regex strings to raw to squelch warnings introduced with python 3.12

- cfe_internal/recommendations.cf
This change switches from the warn_only action body to the policy(p) action body
so that the PostgreSQL recommendation checks are consistent and not appearing to
flap being checked only once an hour (since the warn_only action body sets
ifelapsed to 60). This also aligns with other recommendation policies.
Ticket: ENT-11480
> ENT-11480: Removed hour delay between CFEngine Enterprise PostgreSQL recommendation checks

- cfe_internal/recommendations.cf
This change switches from the warn_only action body to the policy(p) action body
so that the PostgreSQL recommendation checks are consistent and not appearing to
flap being checked only once an hour (since the warn_only action body sets
ifelapsed to 60). This also aligns with other recommendation policies.
Ticket: ENT-11480
(cherry picked from commit a5e6213efa7937acf983e6fd3be09defc1e56af2)
> ENT-11480: Removed hour delay between CFEngine Enterprise PostgreSQL recommendation checks (3.21)

- cfe_internal/recommendations.cf
This change switches from the warn_only action body to the policy(p) action body
so that the PostgreSQL recommendation checks are consistent and not appearing to
flap being checked only once an hour (since the warn_only action body sets
ifelapsed to 60). This also aligns with other recommendation policies.
Ticket: ENT-11480
(cherry picked from commit a5e6213efa7937acf983e6fd3be09defc1e56af2)
> ENT-11480: Removed hour delay between CFEngine Enterprise PostgreSQL recommendation checks (3.18)

- promises.cf.in
When autorun is in use, lexical order is applied for bundle actuation. This
change applies lexical ordering to the list of policy files that are found and
included in inputs. Sorting the files explicitly ensures more predictable
behavior and can assist in debugging.
Ticket: CFE-4364
> CFE-4364: Made autorun inputs sort in lexical order

- lib/autorun.cf
This change uses nested function calling to avoid definition of a variable that
is otherwise unused.
Ticket: CFE-4365
> CFE-4365: Cleaned up unnecessary temporary variable

- MPF.md
- cfe_internal/CFE_cfengine.cf
- cfe_internal/recommendations.cf
This change introduces a reports promise (`R: Note: Recommendations can be disabled by defining 'default:cfengine_recommendations_disabled'`) that is activated if any of the existing recommendations are emitted.
For example:
```
root@hub:~/cfbs# cf-agent -Kf update.cf; cf-agent -K
warning: edit_line warning promised: - #shared_buffers = 128MB                 # min 128kB
warning: edit_line warning promised: - #effective_cache_size = 4GB
warning: Should edit file '/var/cfengine/state/pg/data/postgresql.conf', but only warning promised
warning: Warnings encountered when actuating files promise '/var/cfengine/state/pg/data/postgresql.conf'
R: CFEngine Recommended Settings:
R: shared_buffers = 4850MB
R: effective_cache_size = 13590MB
warning: Method 'postgresql_conf_recommendations' invoked …
```
> ENT-11523: Improved instructions for disabling recommendations

- cfe_internal/enterprise/mission_portal.cf
- templates/cf-apache.service.mustache
In our CI system deployment tests we go through test steps quickly.
Fairly often the apache config is updated by policy and a restart is initiated.
By changing to apachectl graceful we should avoid some of the server availability during tests problems we have been seeing.
Ticket: ENT-11526
with https://github.com/cfengine/core/pull/5480
> ENT-11526: Changed mission-portal apache restart to graceful to minimize service interruptions

- controls/def.cf
The arguments to isgreaterthan() were reversed. With 0 being the first argument, it won't ever be greater than the length of the list.
Ticket: CFE-4374
> CFE-4374: Fixed comparison that caused control_executor_mailfilter_*_configured to never be set

- controls/def.cf
The arguments to isgreaterthan() were reversed. With 0 being the first argument,
it won't ever be greater than the length of the list.
Ticket: CFE-4374
(cherry picked from commit e3718ef3e141ae3c0477f35035f97c82ae40fa83)
> CFE-4374: Fixed comparison that caused control_executor_mailfilter_*_configured to never be set (3.21)

- modules/packages/vendored/apt_get.mustache
(cherry picked from commit c5bc6798b63d9cf8e951df2c81257d4ae92d1ca0)
> CFE-4359: Update regex strings to raw to squelch warnings introduced with python 3.12 (3.21)

- lib/files.cf
The set_user_filed bundle does not escape the user parameter, which could cause
undesired behavior if the input contains special characters (like a period) and
is not escaped. This change introduces a variant of set_user_field which does
automatically escape the user parameter.
Ticket: CFE-4377
> CFE-4377: Added set_escaped_user_field complementing set_user_field

- lib/files.cf
This change simply aims to fix links in the rendered documentation.
(cherry picked from commit fd0a7ac0bbc4f9c1b8a84a360404f16f1c50d5ea)
> Updated see also references (3.21)

- lib/files.cf
The set_user_filed bundle does not escape the user parameter, which could cause
undesired behavior if the input contains special characters (like a period) and
is not escaped. This change introduces a variant of set_user_field which does
automatically escape the user parameter.
Ticket: CFE-4377
(cherry picked from commit 7918afb15db94d3067d2db2dbd849f77986ea31e)
> CFE-4377: Added set_escaped_user_field complementing set_user_field (3.21)

- modules/packages/vendored/yum.mustache
- modules/packages/vendored/zypper.mustache
Same as https://github.com/cfengine/masterfiles/pull/2853, for yum and zypper
> CFE-4359: Update regex strings to raw to squelch python 3.12 warnings (yum and zypper)

- cfe_internal/enterprise/mission_portal.cf
- templates/cf-apache.service.mustache
In our CI system deployment tests we go through test steps quickly.
Fairly often the apache config is updated by policy and a restart is initiated.
By changing to apachectl graceful we should avoid some of the server availability during tests problems we have been seeing.
Ticket: ENT-11526
(cherry picked from commit f4de8811c58bec4ddd445727fecd2d6b373cc0ff)
with https://github.com/cfengine/core/pull/5482
> Changed mission-portal apache restart to graceful to minimize service interruptions (3.21)

- cfe_internal/enterprise/mission_portal.cf
- templates/cf-apache.service.mustache
In our CI system deployment tests we go through test steps quickly.
Fairly often the apache config is updated by policy and a restart is initiated.
By changing to apachectl graceful we should avoid some of the server availability during tests problems we have been seeing.
Ticket: ENT-11526
(cherry picked from commit f4de8811c58bec4ddd445727fecd2d6b373cc0ff)
with https://github.com/cfengine/core/pull/5481
> Changed mission-portal apache restart to graceful to minimize service interruptions (3.18)

- MPF.md
- controls/cf_execd.cf
- services/autorun/README.md
> ENT-11807: Fixed documentation

- .github/workflows/valgrind.yml
- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/federation/federation.cf
Since version 3.24.0, the inventory view is automatically refreshed by
cf-reactor whenever inventory is updated. Hence, there is no need to do
this in policy.
Ticket: ENT-11763
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
Merge together with https://github.com/cfengine/nova/pull/2233
**TODO:**
> ENT-11763: Inventory view is now refreshed in cf-reactor instead of through policy

- inventory/os.cf
(cherry picked from commit a9f916f3ef01a1ea5464d1b6345b0ed7156c3453)
> CFE-4342: When failing to detect platform, inventory attribute "OS" now defaults to PRETTY_NAME from os-release as a fallback (3.21)

- cfe_internal/enterprise/federation/federation.cf
We need to make sure both `semanage fcontext -a` and `restorecon`
are done before we run `ssh-keygen`. Otherwise `ssh-keygen` may
be blocked by SELinux when trying to save/write the generated
key at first and only succeeds in a later agent run.
Ticket: ENT-11136
Changelog: Federated reporting policy fixes SELinux context of
the ~cftransport/.ssh directory and its contents in a
single agent run.
(cherry picked from commit ff392a9587ebc6bad4511750c6b01198e214208d)
> ENT-11136: Refactor and improve policy fixing up SELinux context on FR SSH files (3.21)

- templates/federated_reporting/distributed_cleanup.py
This enables an administrator to setup a single feeder.
/opt/cfengine/federation/bin/distributed_cleanup.py --setup-feeder feederhostname
Ticket: ENT-11844
> Added setup-feeder option to distributed cleanup script

- templates/federated_reporting/distributed_cleanup.py
This enables an administrator to setup a single feeder.
/opt/cfengine/federation/bin/distributed_cleanup.py --setup-feeder feederhostname
Ticket: ENT-11844
(cherry picked from commit d60cc27afefc8423462e665983a9123a7a7cb522)
> Added setup-feeder option to distributed cleanup script (3.21)

- .github/workflows/valgrind.yml
- modules/packages/vendored/apt_get.mustache
- modules/packages/vendored/yum.mustache
- modules/packages/vendored/zypper.mustache
This back port is needed for Ubuntu 24 to pass CI (see ENT-11309)
Back ported from https://github.com/cfengine/masterfiles/pull/2873
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10885)](https://ci.cfengine.com/job/pr-pipeline/10885/)
> CFE-4359: Update regex strings to raw to squelch warnings introduced with python 3.12 (3.18)

- .github/workflows/style_check.yml
- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
- templates/federated_reporting/distributed_cleanup.py
This enables an administrator to setup a single feeder.
/opt/cfengine/federation/bin/distributed_cleanup.py --setup-feeder feederhostname
Ticket: ENT-11844
(cherry picked from commit d60cc27afefc8423462e665983a9123a7a7cb522)
> Added setup-feeder option to distributed cleanup script (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
- https://github.com/cfengine/buildscripts/pull/1440
> ENT-10646: Squashed common error logged by Apache related to IPv6

- cfe_internal/enterprise/templates/httpd.conf.mustache
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
> ENT-10646: Squashed common error logged by Apache related to IPv6 (3.21)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Apache often logs errors related to IPv6, e.g.:
No route to host: AH00056: connect to listener on [::]:80
Specifying IPv4 when listening on port 80 prevents this excessive noise.
Ticket: ENT-10646
(cherry picked from commit b936079c03621b556ac800181e886cf4feb95033)
> ENT-10646: Squashed common error logged by Apache related to IPv6 (3.18)

- promises.cf.in
A previous fix to add package inventory for AIX and adding ability to influence default package manager and inventory via augments introduced this bug.
The commit was: 87292179415a0d4770281715a850ef49d2991842
There was a typo that used the class cfe_yum_package_module_supported instead of cfe_python_for_package_modules_supported.
The first class is undefined anywhere in policy. The second class it the correct one.
Ticket: ENT-11850
> Fixed missing software inventory on RedHat based systems

- promises.cf.in
A previous fix to add package inventory for AIX and adding ability to influence default package manager and inventory via augments introduced this bug.
The commit was: 87292179415a0d4770281715a850ef49d2991842
There was a typo that used the class cfe_yum_package_module_supported instead of cfe_python_for_package_modules_supported.
The first class is undefined anywhere in policy. The second class it the correct one.
Ticket: ENT-11850
(cherry picked from commit 8bbae0248c52cbfd63332636823d05c5ed0267f8)
> Fixed missing software inventory on RedHat based systems (3.18)

- templates/federated_reporting/nova_api.py
If urllib3 is v2.0 and greater then errors are produced when no subjectAltName is in the certificate. For less than v2.0 we want to silence the SubjectAltNameWarning exception.
Ticket: ENT-11875
with https://github.com/cfengine/buildscripts/pull/1454
> Added check for SubjectAltNameWarning exception in distributed_cleanup.py

- templates/federated_reporting/nova_api.py
If urllib3 is v2.0 and greater then errors are produced when no subjectAltName is in the certificate.
For less than v2.0 we want to silence the SubjectAltNameWarning exception.
Ticket: ENT-11875
(cherry picked from commit f6d21787b57ce831b59a36a4d9b9fa245caa8b1d)
> Added check for SubjectAltNameWarning exception in distributed_cleanup.py (3.18)

- templates/federated_reporting/nova_api.py
If urllib3 is v2.0 and greater then errors are produced when no subjectAltName is in the certificate.
For less than v2.0 we want to silence the SubjectAltNameWarning exception.
Ticket: ENT-11875
(cherry picked from commit f6d21787b57ce831b59a36a4d9b9fa245caa8b1d)
> Added check for SubjectAltNameWarning exception in distributed_cleanup.py (3.21)

- modules/packages/vendored/nimclient.mustache
CFE-4415
(cherry picked from commit aa6861607396db946f9efd91e72708070d5002de)
> CFE-4415: Fix shell typo in nimclient module script (3.21)

- cfe_internal/update/update_policy.cf
With findfiles returning proper back-slashed paths this policy was broken due to _vendored_dir and _override_dir being used with mixed slashed path and used as a replacement string.
Ticket: ENT-11959
> ENT-11959: Fixed modules_presence bundle for Windows agents

- lib/files.cf
This is just a small change so that a user doesn't have to hunt down the valid
options to know what's available.
Ticket: CFE-4426
> CFE-4426: Added inline docs showing valid values for method (field_operation) in body edit_field quoted_var

- lib/files.cf
This is just a small change so that a user doesn't have to hunt down the valid
options to know what's available.
Ticket: CFE-4426
> CFE-4426: Added inline docs showing valid values for method (field_operation) in body edit_field quoted_var (3.24)

- lib/files.cf
This is just a small change so that a user doesn't have to hunt down the valid
options to know what's available.
Ticket: CFE-4426
> CFE-4426: Added inline docs showing valid values for method (field_operation) in body edit_field quoted_var (3.21)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>
(cherry picked from commit b99e9a3cd4da10917e288ff1f1c5b2b2ad3a95ec)
> ENT-11472: Added CSP HTTP Header to MP apache config (3.24)

- cfe_internal/update/update_bins.cf
- standalone_self_upgrade.cf.in
The trailing /. is how we can explicitly indicate that a directory is desired in
CFEngine. Without a trailing ./ CFEngine could get confused and create a single
file instead of a directory.
Ticket: ENT-12116
> ENT-12116: Added trailing /. to files promises targeting local_software_dir

- cfe_internal/update/update_bins.cf
- standalone_self_upgrade.cf.in
The trailing /. is how we can explicitly indicate that a directory is desired in
CFEngine. Without a trailing ./ CFEngine could get confused and create a single
file instead of a directory.
Ticket: ENT-12116
> ENT-12116: Added trailing /. to files promises targeting local_software_dir (3.24)

- cfe_internal/update/update_bins.cf
- standalone_self_upgrade.cf.in
The trailing /. is how we can explicitly indicate that a directory is desired in
CFEngine. Without a trailing ./ CFEngine could get confused and create a single
file instead of a directory.
Ticket: ENT-12116
> ENT-12116: Added trailing /. to files promises targeting local_software_dir (3.21)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>
(cherry picked from commit b99e9a3cd4da10917e288ff1f1c5b2b2ad3a95ec)
>  ENT-11472: Added CSP HTTP Header to MP apache config (3.21)

- MPF.md
- cfe_internal/update/update_policy.cf
This change clarifies the need to specify the namespace when defining a custom policy update bundle both in documentation in reports emitted by policy.
If namespace is not specified the bundle will not be found and will be unable to run.
> CFE-4442: Clarified need to specify namespace when defining custom policy update bundle

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-4400: Allowed blob image-src in the Mission Portal CSP rules

- cfe_internal/enterprise/templates/httpd.conf.mustache
Highchart export requires it
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 4070af34edfecd70621b9a214826f4e09bc69de8)
> ENT-4400: Allowed blob image-src in the Mission Portal CSP rules (3.21.x)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Highchart export requires it
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 4070af34edfecd70621b9a214826f4e09bc69de8)
> ENT-4400: Allowed blob image-src in the Mission Portal CSP rules (3.24.x)

- cfe_internal/update/systemd_units.cf
When enabling systemd unit management with the augment, e.g.:
```
{
"classes": {
"default:mpf_enable_cfengine_systemd_component_management": {
"regular_expressions": [ "any" ]
}
}
}
```
There were errors like failed to open /dev/tty no such device.
Providing --no-ask-password solves the issue.
Ticket: CFE-4445
> Fixed failed to open /dev/tty errors when using systemd unit management

- cfe_internal/update/systemd_units.cf
When enabling systemd unit management with the augment, e.g.:
{
"classes": {
"default:mpf_enable_cfengine_systemd_component_management": {
"regular_expressions": [ "any" ]
}
}
}
There were errors like failed to open /dev/tty no such device.
Providing --no-ask-password solves the issue.
Ticket: CFE-4445
(cherry picked from commit 1763475f45a095c350d480851bd51220666636e1)
> Fixed failed to open /dev/tty errors when using systemd unit management (3.24)

- cfe_internal/update/systemd_units.cf
When enabling systemd unit management with the augment, e.g.:
{
"classes": {
"default:mpf_enable_cfengine_systemd_component_management": {
"regular_expressions": [ "any" ]
}
}
}
There were errors like failed to open /dev/tty no such device.
Providing --no-ask-password solves the issue.
Ticket: CFE-4445
(cherry picked from commit 1763475f45a095c350d480851bd51220666636e1)
> Fixed failed to open /dev/tty errors when using systemd unit management (3.21)

- lib/paths.cf
- lib/services.cf
On AIX the default will use AIX System Resource Controller commands to manage service state.
```
bundle agent main
{
services:
"sendmail"
service_policy => "start";
}
```
service_policy options supported are: start, stop and reload.
Ticket: CFE-4447
> Added support for AIX System Resource Controller services promises

- lib/paths.cf
- lib/services.cf
On AIX the default will use AIX System Resource Controller commands to manage service state.
bundle agent main
{
services:
"sendmail"
service_policy => "start";
}
service_policy options supported are: start, stop and reload.
Ticket: CFE-4447
(cherry picked from commit 6f559dd18d436077af8716ec7d67428de8ab3575)
> Added support for AIX System Resource Controller services promises (3.24)

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-12151: Added possibility to configure Mission Portal web server ports

- controls/cf_serverd.cf
I believe this has no functional difference, but it's an important hint at least
to the policy reader that it is a directory.
Unlike other access rules I left off the condition to only add the access rule
if the directory exists so that if it is created there will not be a window of
time for which clients would be able to get files from the directory.
If the directory does not exist there are info level logs that are emitted, but
that seems acceptable since we do not log info from cf-serverd by default. There
is apparently no issue making an access promise for a directory that does not
exist, I see it listed in the cf-serverd access summary from verbose logging.
Ticket: CFE-4453
> CFE-4453: Added missing trailing slash to .no-distrib directory in MPF

- .github/workflows/valgrind.yml
- modules/packages/vendored/yum.mustache
- tests/unit/test_package_module_yum
- Fixed issue with yum package module regarding packages with epoch not validating
- Black formatting for yum package module python script
> Fixed issue with yum package module regarding packages with epoch not validating (3.21)

- .github/workflows/valgrind.yml
- modules/packages/vendored/yum.mustache
- tests/unit/test_package_module_yum
- Fixed issue with yum package module regarding packages with epoch not validating
- Black formatting for yum package module python script
> Fixed issue with yum package module regarding packages with epoch not validating (3.24)

- cfe_internal/enterprise/templates/httpd.conf.mustache
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
Merge together: https://github.com/cfengine/buildscripts/pull/1562
> ENT-12531: Allowed images from raw.github.com

- cfe_internal/enterprise/templates/httpd.conf.mustache
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
(cherry picked from commit 7b77602ce9fe17d763b596cfa298ed6551b5beb5)
Merge together: https://github.com/cfengine/buildscripts/pull/1563
> ENT-12531: Allowed images from raw.github.com (3.24)

- cfe_internal/enterprise/templates/httpd.conf.mustache
README files in build module repos often contain images, sometimes those images
are served from raw.github.com. This change allows those images to be displayed
within the Build app in Mission Portal.
Ticket: ENT-12531
(cherry picked from commit 7b77602ce9fe17d763b596cfa298ed6551b5beb5)
Merge together: https://github.com/cfengine/buildscripts/pull/1564
> ENT-12531: Allowed images from raw.github.com (3.21)

- controls/def.cf
This probably should have changed when mission-portal was adjusted: https://github.com/cfengine/mission-portal/pull/312
Ticket: ENT-12556
> Fixed location of Mission Portal application logs for log_dir cleanup

- controls/def.cf
This probably should have changed when mission-portal was adjusted: https://github.com/cfengine/mission-portal/pull/312
Also changed from httpd/logs/application to httpd/logs since several other logs are in that directory as well.
Ticket: ENT-12556
(cherry picked from commit c1078c1a3b98020a08e9696e8314238328736c21)
> Fixed location of Mission Portal application logs for log_dir cleanup (3.21)

- lib/paths.cf
These hardware related commands - whose locations differ slightly between distros - are often used by CMDB discovery tools. By adding them to paths.cf, we make it easy to template out a sudoers file.
> ENT-12560: Add paths for the dmsetup, fdisk, and lshw commands

- lib/paths.cf
These hardware related commands - whose locations differ slightly
between distros - are often used by CMDB discovery tools. By adding
them to paths.cf, we make it easy to template out a sudoers file.
Ticket: ENT-12560
> ENT-12560: Added paths for the dmsetup, fdisk, and lshw commands (3.24)

- lib/paths.cf
These hardware related commands - whose locations differ slightly
between distros - are often used by CMDB discovery tools. By adding
them to paths.cf, we make it easy to template out a sudoers file.
Ticket: ENT-12560
> ENT-12560: Added paths for the dmsetup, fdisk, and lshw commands (3.21)

- controls/def.cf
allowallconnects should be for allowing parallel connections.
Let's see if this is really necessary, since cf-agent should
reuse an open connection and this shouldn't be needed, at least
by default.
> CFE-2528: Changed the default for allowallconnects

- cfe_internal/enterprise/CFE_hub_specific.cf
> Added case if http/2(php-fpm binary present) no need for php_version variable for httpd.conf template

- .gitignore
- cfe_internal/enterprise/mission_portal.cf
```
max_children: 60% of available RAM / average memory taken by php-fpm process
max_spare_servers: cpu cores number * 4
min_spare_servers: cpu cores number * 2
start_servers: (max_spare_servers + min_spare_servers) / 2
```
Ticket: ENT-12957
> Aligned PHP-FPM config based on system resources

- MPF.md
- controls/def.cf
- controls/update_def.cf.in
- promises.cf.in
- standalone_self_upgrade.cf.in
- update.cf.in
This change implements easy configuration of protocol_version in body common control for the standard MPF entries.
Ticket: CFE-4543
> CFE-4543: Made protocol_version configurable via Augments

- MPF.md
- controls/def.cf
- controls/update_def.cf.in
- promises.cf.in
- standalone_self_upgrade.cf.in
- update.cf.in
This change implements easy configuration of `protocol_version` in body common control for the standard MPF entries.
Ticket: CFE-4543
> CFE-4543: Made protocol_version configurable via Augments (3.24)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
> Added exception for Ubuntu-24 to accept our test gpg key which is "weak" (rsa1024)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
Ticket: ENT-13066
(cherry picked from commit 03c533399dc85d020a8a1a897cb0382e999ab201)
> Added exception for Ubuntu-24 to accept our test gpg key which is "weak" (rsa1024) (3.21)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
edit_defaults does not have an effect when the content attribute is in use.
> ENT-13066: Removed edit_defaults attribute that does not have effect with content attribute (3.21)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
edit_defaults does not have an effect when the content attribute is in use.
> ENT-13066: Removed edit_defaults attribute that does not have effect with content attribute (3.24)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
edit_defaults does not have an effect when the content attribute is in use.
> ENT-13066: Removed edit_defaults attribute that does not have effect with content attribute

- lib/paths.cf
> ENT-12988: Added dmidecode to well known paths for Red Hat (3.21)

- lib/paths.cf
> ENT-12987: Fixed path to lsof on Red Hat 7 and greater (3.24)

- lib/paths.cf
> ENT-12987: Fixed path to lsof on Red Hat 7 and greater (3.21)

- cfe_internal/enterprise/CFE_knowledge.cf
Sync of share/GUI to docroot was already changed to disabled by default. This
bring this one off promise from the same source to the same destination into
alignment with that.
Ticket: ENT-13173
> ENT-13173: Stopped mirroring .htaccess from share/GUI to Mission Portal docroot

- cfe_internal/enterprise/CFE_hub_specific.cf
This aligns the editing of this file to only when we are explicitly syncing
docroot from share/GUI.
Ticket: ENT-13175
> ENT-13175: Disabled sync of Mission Portal config from share/GUI unless explicitly enabled

- inventory/linux.cf
We have received reports of slow policy execution on hosts with many
nfs mounts (hundreds). Part of this expense has to do with the fact that the
promise re-defined the itself on each pass of the policy.
This change prevents that additional un-necessary processing and re-definition
by restricting the promise only to when inventory_linux.nfs_servers is not
already defined. This single change reduced processing time in one case by ~70
seconds (from ~90 seconds to ~20 seconds).
Ticket: ENT-13210
(cherry picked from commit f7d106a795ad5d61760ca9eadecb0fc641a2d8fe)
> ENT-13210: Prevented nfs server inventory from doing unnecessary extra work (3.21)

- inventory/linux.cf
We have received reports of slow policy execution on hosts with many
nfs mounts (hundreds). Part of this expense has to do with the fact that the
promise re-defined the itself on each pass of the policy.
This change prevents that additional un-necessary processing and re-definition
by restricting the promise only to when inventory_linux.nfs_servers is not
already defined. This single change reduced processing time in one case by ~70
seconds (from ~90 seconds to ~20 seconds).
Ticket: ENT-13210
> ENT-13210: Prevented nfs server inventory from doing unnecessary extra work (3.24)
