cfengine/masterfiles

- lib/3.6/packages.cf
- lib/3.7/packages.cf
This package method interacts with SmartOS pkg_add to install from local or remote repositories. It is slightly different than the FreeBSD `pkg_add`.
This example installs `perl5` from a remote repository.
packages:
"perl5"
package_policy   =>  "add",
package_method   =>  smartos_pkg_add("http://pkg.example.com/packages/");
This example installs `perl5` from a local package cache.
packages:
"perl5"
package_policy   =>  "add",
package_method   =>  smartos_pkg_add("/opt/custom/packages");
> Add package method for SmartOS pkg_add

- cfe_internal/CFE_hub_specific.cf
- cfe_internal/cfengine_processes.cf
- controls/cf_execd.cf
- update.cf
- update/update_bins.cf
- update/update_policy.cf
- update/update_processes.cf
This commit changes most occurances of `/var/cfengine` with `$(sys.workdir)` and `/var/cfengine/bin` with `$(sys.bindir)`. This helps make the default policy set more useful when users compile cfengine with alternate workdir paths.
> Make workdir relocatable.

- inventory/any.cf
- tests/acceptance/17_packages/unsafe/package-inventory.cf
We don't need to install the package, we only need to make sure that
the package list as been generated. However, we want to include the
package manager name, so that the list of packages is named correctly.
Hence the "<mgr> --help ; /bin/true".
> Redmine #6865: Fix broken package promise as a result of inventory.

- lib/3.5/paths.cf
- lib/3.6/paths.cf
Fix path[ping] for FreeBSD 9.3, 10.x, 11.x
(cherry picked from commit c2f10044c4e78223835161fe00dc5ed5ed5e3660)
Conflicts:
lib/3.7/paths.cf Clearly not in the 3.6 branch
> Change: Update paths.cf

- lib/3.5/files.cf
- lib/3.6/files.cf
- lib/3.7/files.cf
This body allows selection of symlinks based on their target. This can be
useful if you want to make a promise about a symlink only if it points to a
specific location. For example deleting an old symlink.
> Add: Select files by symlink target

- lib/3.6/files.cf
Updating a self referential "see also" section to point to something useful.
> Improve inline documentation

- cfe_internal/CFE_hub_specific.cf
The policy to ensure the correct port is set if not 80 needed to be updated
after the appsettings.php file was updated.
Additionally this fixes a weak regular expression when setting the port in
httpd.conf
Ref: https://dev.cfengine.com/issues/6910
> Fix: Mission Portal Port Assignment from policy

- cfe_internal/CFE_cfengine.cf
- def.cf
- lib/3.5/cfe_internal.cf
- lib/3.6/cfe_internal.cf
- lib/3.7/cfe_internal.cf
cf-hub.
In case if not collecting the reports for extended period of time, they may
consume too much space, this policy will purge accumulated "diff" reports if
the exceed 50MB in total size. As the result, report history will become
inconcistent with next successful report collection and cf-hub will go for
rebase query (fetching full state next time). This cleanup apply only to diff
reports which include class, variable, promise execution, software installed,
software patch, lastseen reports.
Redmine: #1150
> Enterprsie reports are accumulated on the client till they are collected by

- lib/3.6/cfe_internal.cf
- lib/3.7/cfe_internal.cf
Diff state purging is only applicable when diff state files actually exist.
This adds a guard to ensure we only try to caclulate the size of the diff
state reports when there is something to calculate.
Ref: https://github.com/cfengine/masterfiles/issues/413
> Change: Avoid generating errors in logs

- inventory/any.cf
Tested on CentOS 6.
yum is run shortly after bootstrap and package installed & update inventory works.
yum is not run after that (yet) - has still not tested for 24h.
Please backport to 3.6.x if accepted.
> package inventory policy ran on every agent run

- inventory/any.cf
package inventory policy ran on every agent run (every 5 minutes), calling the package manager. We rather refresh it daily.
(cherry picked from commit 43b607e222d14495c9feb0307fb5d70dd3845893)
> Reduce package manager calls

- lib/3.6/files.cf
- lib/3.7/files.cf
Sometimes one thing must be found in a file before another.
I think this should be picked to 3.6 as well.
> Add: edit_line body to insert line before regular expression

- cfe_internal/CFE_cfengine.cf
May kill CFEngine processes inside containers.
Redmine: https://dev.cfengine.com/issues/6906.
This is a workaround, ideal solution is to have a way to filter process in the current namespace (zone/cgroup/etc.).
Consider backport to 3.6.x.
> turn off cleanup of several cf-execd and cf-monitord by default

- update/update_bins.cf
There is no need to have two package promises to upgrade Enterprise. I chose
to remove the package promises guarded by stopped_cfprocs because in order for
those promises to be activated the software must be downloaded from the hub,
and cfengine processes must be stopped within the same agent run. This creates
a brittle chain.
Ref: https://dev.cfengine.com/issues/6964
> Change: Remove redundant package promise

- def.cf
- lib/3.6/cfe_internal.cf
- lib/3.7/cfe_internal.cf
Hard coding time based classes makes it difficult to allow policy execution
outside of that window without modifying the policy. This preserves the same
functionality while increasing flexibility which can be useful especially when
troubleshooting.
Ref: https://dev.cfengine.com/issues/7010
> Change: Replace hard coded time based classes

- lib/3.5/bundles.cf
- lib/3.6/bundles.cf
- lib/3.7/bundles.cf
Previously it was only removing the contents of the directory.
Ref: https://dev.cfengine.com/issues/7009
> Fix: rm_rf_depth should also remove the named directory

- update/update_processes.cf
This will launch CFEngine using systemd when calling "cf-agent -f
update.cf" instead of launching them directly. This has the advantage
of bringing all daemons under systemd's control.
> Redmine #6401, #6402: Add systemd support to update_processes.cf.

- lib/3.5/files.cf
- lib/3.6/files.cf
- lib/3.7/files.cf
Classes defined as the result of a promise outcome are by default namespace
scoped. This causes the classes to live on beyond the individual bundle
activation, resulting in bad behaviour for classes being defined unexpectedly.
Ref: https://dev.cfengine.com/issues/7035
This should be picked to 3.6.x.
Let me know if you think this should be updated to include all classes defined in edit_line bundles or all classes defined using the always classes body in edit_line bundles.
> Change: Stop replace_or_add bundle from adding extra lines

- Makefile.am
- m4/tar.m4
Should fix "make dist" on RHEL4 and other old platforms.
Accompanies [buildscripts pull request 50](https://github.com/cfengine/buildscripts/pull/50) and [core pull request 2137](https://github.com/cfengine/core/pull/2137).
> Do not pass --hard-dereference to GNU tar if not supported

- lib/3.5/common.cf
- lib/3.6/common.cf
- lib/3.7/common.cf
Each attribute is checked individually, one attribute not being repaired says
nothing about another attributes potential outcome.
Perhaps in the future we could have a conveniance combined outcome or
"compliance" outcome, where classes could be defined if all promsie attributes
were kept or repaired. Or perhaps a $(this.attribute) variable that would
allow automatic identification of the attribute that had the specified
outcome.
Ref: https://dev.cfengine.com/issues/7022
> Remove: *_not_repaired classes are a misnomer

- update/update_bins.cf
Partially introduced by commit 9206e119e1af8a702495204b64d55729f3c0d054 to make workdir relocatable (https://github.com/cfengine/masterfiles/pull/396).
Please backport to 3.6.x if ok.
> Upgrade procedure is using c:\var\cfengine on Windows.

- lib/3.5/packages.cf
- lib/3.6/packages.cf
- lib/3.7/packages.cf
Please make this available in 3.6.6. All package operations in the 2014Q4 LTS SmartOS base, standard, minimal and multiarch images are affected.
Pkgin version 0.8.0 and later, when STDOUT is not a terminal separates
the package name/version from the description with a semi-colon. Prior
to 0.8.0 the description was separated by whitespace.
E.g.:
New behavior:
zsh-5.0.7nb1;The Z shell
Old behavior:
zsh-5.0.5nb1         The Z shell
This would cause cfengine to interpret the version as `5.0.7nb1;The`.
This backward compatible fix adjusts the package_version_regex for the
`smartos` package method to correctly match the version number.
This fix is demonstrated with the following pcretest session.
* The old regex form is demonstrated first.
* The new output from pkgin is matched incorrectly.
* …
> Fix package version parsing for pkgin-0.8.0.

- lib/3.6/def.cf
- lib/3.6/update_def.cf
- lib/3.7/def.cf
- lib/3.7/update_def.cf
Extra def.json in lib only adds extra complexity. It may make sense in the
future to merge def.json with something outside of masterfiles (like data
sourced from a CMDB) but for now it seems to add little.
3.6 has no yaml support, so probably it makes little sense for 3.6 agents to
download YAML. Besides it can be overridden in def.json now so even if a user
wants it, it wont require a change in policy.
> Remove: Extra def.json and yaml from 3.6 upate inputs

- services/file_change.cf
/etc/shadow contains sensitive information. While RBAC is used to
control which users have access to this information by default we should
not collect it.
Ref: https://dev.cfengine.com/issues/7083
> Change: Do not report diffs for shadow by default

- services/autorun.cf
It is nice to be able to predict the order in which bundles are activated and
at times necessary for class dependancies.
Ref: https://dev.cfengine.com/issues/7102
> Change: Lexicographically sort autorun bundles

- inventory/redhat.cf
Oracle Enterprise Linux hosts are not pure redhat and should be
excluded.
Ref: https://dev.cfengine.com/issues/7081
> Change: Exclude oracle hosts from redhat_pure

- inventory/any.cf
dmidecode is unreliable, sometimes it outputs very badly formated processer
version information, sometimes it cannot get processor information at all.
/proc/cpuinfo is a better source (at least on linux), and windows doesnt use
dmidecode, it uses another method but offers the data as if it were from
dmidecode.
This change abstracts cpuinfo into its own bundle. If /proc/cpuinfo is 
avaialable it uses that (based on parsing proc), and if only dmidecode is
available it will use that.
This does not completly detangle windows from dmidecode, it only detangles CPU
model name from being inventoried directly in the dmidecode bundle. This can
serve as initial work to continue detangling other information gathered in the
dmidecode bundle that is not actually from dmidecode.
Additionally there is …
> Change: Improve CPU info inventory

- inventory/any.cf
Previously this inventory came directly from the agent. However in order to
provide easier user selectable filtering it has moved to policy.
Ref: https://dev.cfengine.com/issues/7097
Should be merged with change to core:
https://github.com/cfengine/core/pull/2163
> Add: IPv4 address inventory

- inventory/linux.cf
Inform mode is supposed to be for changes that occur to the system. Printing
out the parsed contents of /etc/os-release does not really fit this ideal. I
have moved it to DEBUG|DEBUG_bundlename so policy maintainers can easily get
policy debug output as a whole or per bundle without also having other
additional inform or verbose agent output.
> Change: Class to guard linux inventory output

- inventory/any.cf
Hyperthreading detection was removed because it was deemed unreliable.
> Remove: Unnecessary debug report

- cfe_internal/CFE_cfengine.cf
- promises.cf
This fixes errors that reference bundles that are not loaded by core after
some refactoring to reduce unnecessary policy loading for 3.7.
Ref: https://dev.cfengine.com/issues/7189
> Fix: Errors loading policy from core

- lib/3.6/services.cf
- lib/3.7/services.cf
Inform mode is supposed to be for changes, previously a report was printed
each time the agent was run in inform mode even if there were no changes. This
guards the chkconfig report so that it is only printed under the same
conditions that trigger the command to be run.
Ref: https://dev.cfengine.com/issues/7196
> Fix: Superflous reporting about chkconfig usage

- cfe_internal/update/update_bins.cf
HPUX $(sys.flavour) includes a version that does not align with other software
update directories. Switch hpux to use $(sys.class)_$(sys.arch) and refactor
all platforms to use a common variable for the package dir for good hygiene.
> Change: Local software dir definition

- Makefile.am
- configure.ac
- modules/packages/Makefile.am
- modules/packages/apt_get
- modules/packages/yum
Tests will be in a separate commit.
This is a subset of https://github.com/cfengine/masterfiles/pull/465 which contains only the modules, not the tests. Work on making the tests pass will continue, but this will allow us to start building packages, and at least the Debian package module is already in a quite good state.
> Redmine #7121 and #7122: Add apt_get and yum package modules.

- promises.cf
> Fix broken or.

- CHANGELOG.md
- lib/3.6/services.cf
- lib/3.7/services.cf
- lib/3.8/services.cf
Previously if a service was not running and policy restart was specified the
service would not be restarted (and an inform level report would indicate that
it was). Now the service is restarted even if its not running.
Ref: https://dev.cfengine.com/issues/7258
> Fix: standard_services restart when service not running with chkconfig

- inventory/any.cf
We learned that there are package updates available that allow RHEL4 to be
used with the dmidecode inventory for redhat 4. Automatically detecting the
package condition is considered too complex compared to the value provided so
it is left for the user to adjust as necessary.
> Add: Comment about RHEL4 dmidecode based inventory

- CHANGELOG.md
- controls/3.7/update_def.cf
Ref: https://dev.cfengine.com/issues/7315
(cherry picked from commit 9eac03ebf32570765d4ab7642631c7621c635553)
Conflicts:
controls/3.8/update_def.cf
> Add: Support for class augmentation from def.json in update policy

- lib/3.7/autorun.cf
- promises.cf
Ref: https://dev.cfengine.com/issues/7317
(cherry picked from commit eadd416d240db867d5c12691e24901f64fb29450)
Conflicts:
lib/3.8/autorun.cf
> Change: autorun related verbose_mode class guards to DEBUG

- cfe_internal/enterprise/CFE_hub_specific.cf
- inventory/any.cf
Inform mode is supposed to inform you of changes to the system, debug is more
appropriate for these informational messages. Also not using the same class as
defined by the log level options to the agent allows us to not be overwhelemed
with output when doing policy debugging.
Ref: https://dev.cfengine.com/issues/7318
> Change: Inform guards to DEBUG

- cfe_internal/update/update_bins.cf
The path was very generic and has been found to conflict with other
vendor scripts in the wild.
Ref: https://dev.cfengine.com/issues/7344
> Change: Path to cf-upgrade related scripts

- CHANGELOG.md
- lib/3.7/stdlib.cf
This work is to facilitate more modular loading of inputs in the future.
(cherry picked from commit fa03aace91bd9925fe831f861fd24f7c43a6a7a1)
Conflicts:
lib/3.8/stdlib.cf
> Change: Switch stdlib inputs to classic arrays

- CHANGELOG.md
- controls/3.7/cf_execd.cf
- controls/3.7/def.cf
- example_def.json
This allows agent email to be easily disabled by augmenting def.json.
Ref: https://dev.cfengine.com/issues/7312
> Add: Negative class guard protecting agent email settings

- CHANGELOG.md
- cfe_internal/core/main.cf
- cfe_internal/core/watchdog/watchdog.cf
- controls/3.8/def.cf
- example_def.json
- lib/3.8/paths.cf
- promises.cf
- templates/cfengine_watchdog.mustache
Ref: https://dev.cfengine.com/issues/7324
> Add: Policy to configure external watchdog for cf-execd

- lib/3.5/processes.cf
- lib/3.6/processes.cf
see: https://dev.cfengine.com/issues/3009
(cherry picked from commit 5038696c37fcfbc5c4ec85915d44d13f5bdfb1bf)
Conflicts:
lib/3.7/processes.cf
lib/3.8/processes.cf
> Backport fix process_result logic to match the purpose of days_older_than().

- CHANGELOG.md
- cfe_internal/core/main.cf
This policy was originally disabled because it killed execds running inside of
containers. However it was keeping multiple cf-execds in check especially
after agent upgrades.
Ref: https://dev.cfengine.com/issues/7185
This needs picked to 3.7 and 3.6
> Change: Enable limit_robot_agents maintenance policy

- cfe_internal/CFE_cfengine.cf
This policy was originally disabled because it killed execds running inside of 
containers. However it was keeping multiple cf-execds in check especially 
after agent upgrades.
Ref: https://dev.cfengine.com/issues/7185
> Change: Manually backport enablement of limit_robot_agents

- CHANGELOG.md
- controls/3.7/def.cf
- controls/3.7/def_inputs.cf
- controls/3.8/def.cf
- controls/3.8/def_inputs.cf
- promises.cf
Ref: https://dev.cfengine.com/issues/7420
Supercedes: https://github.com/cfengine/masterfiles/pull/530
> def.cf: separate inputs into a secondary def_inputs.cf file

- modules/packages/apt_get
- modules/packages/yum
- tests/unit/test_package_module_apt_get
- tests/unit/test_package_module_yum
<pre>
commit 7092480966efee1872ef008beb36c2c3fcd681ba
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Fri Aug 14 11:10:01 2015
Redmine #7424: Fix package promise not removing dependant packages.
commit 9a0ec964221e6969ddb64cadfe7b276cf565b924
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Thu Aug 13 14:18:30 2015
Redmine #7421: Fix incorrect version detection in promise string.
Debian packages use "pkg_1.0.deb" format, not "pkg-1.0.deb", to encode
version. This made it impossible to install packages that had version
numbers in their name, such as virtualbox-5.0.
Changelog: Package promise: Fix inability to install certain packages
with numbers.
</pre>
> Package promise fixes

- cfe_internal/enterprise/ha/ha.cf
(cherry picked from commit 77b238f8d08a6f5cf693130bc929bdfc11f3c4d9)
> Fix syntax error in HA policy.

- cfe_internal/update/update_bins.cf
Ref: https://dev.cfengine.com/issues/7456
Changelog: Fix noise from internal policy to upgrade windows agents
(Redmine #7456)
> Change: Guard update_bins package promises with trigger_upgrade

- cfe_internal/enterprise/ha/ha.cf
- cfe_internal/enterprise/ha/ha_def.cf
- cfe_internal/enterprise/ha/ha_update.cf
- cfe_internal/update/update_processes.cf
- controls/3.7/def.cf
- controls/3.7/update_def.cf
- controls/3.8/def.cf
- controls/3.8/update_def.cf
In order to support environments with 3 HA nodes we need to
provide functionality allowing manual failover to 3rd HA node.
Idea is that 3rd node is used only as disaster-recovery node
and failover to that node will be manual.
CFEngine policy will limit manual steps to absolute minimum.
> Add support for failover to 3rd HA node located outside cluster.

- tests/acceptance/testall
The old approach has been found not to work under some circumstances,
however this approach has been tested and found to work.
> Fix POSIX shell detection on Solaris.

- controls/3.5/def_inputs.cf
- controls/3.5/update_def_inputs.cf
- controls/3.6/def_inputs.cf
- Missing inputs cause policy errors
Ref: https://dev.cfengine.com/issues/7549
> Fix: Policy errors for 3.5 and 3.6

- update.cf
This one slipped past my testing when re-unifying the version split policies.
> Fix: Path to update def controls

- cfe_internal/enterprise/ha/ha_update.cf
Fix duplicated handle and invalid hub keys location variable in HA policy.
Changelog: Fix broken HA policy for 3rd disaster-recovery node.
> Fix broken HA policy specific for disaster-recovery node.

- lib/paths.cf
This makes it possible for service promises to use the standard_services bundle on stock FreeBSD too.
> Add path to FreeBSD's service command.

- lib/3.6/services.cf
Manually backported commit 47ab7b0
Ref: https://dev.cfengine.com/issues/7663
> Change: Backport documentation fix in stdlib services

- controls/def.cf
- example_def.json
- Values do not resolve early enough for execd to make use of them
Ref: https://dev.cfengine.com/issues/7682
> Remove: Support for email settings from augments_file

- Makefile.am
Without this directory being deployed 3.7 agents running new policy will
error when running the policy.
Ref: https://dev.cfengine.com/issues/7680
> Change: Make sure that 3.7 lib dir gets deployed

- configure.ac
Without this lib/3.7 directory 3.7 agents running the latest masterfiles
will be unable to locate the stdlib. Since some version control systems
automatically stop tracking empty directories we have this README
present to explain the directories presence, and keep it around.
Ref: https://dev.cfengine.com/issues/7680
> Add: lib/3.7/README.md to install path

- lib/cfe_internal_hub.cf
Fix error messages while reading file during bootstrap.
> Redmine #7737: Error while reading cf-consumer.pid file.

- .travis.yml
Cross check masterfiles with 3.6.6 and 3.7.1 parser.
> Add travis CI config to check masterfiles syntax.

- controls/3.6/def.cf
- controls/3.7/def.cf
(cherry picked from commit 7838d8081756b54c1f3c4e8564a86cbc9b6f1ab5)
Changelog: Fix definition of classes from augments file
> Add missing override_classes to control/def.cf

- lib/paths.cf
- lib/vcs.cf
When using bundle agent git from the stdlib on repositories that are not
owned by root an error prevents action because cfengine does not inherit
the shell environment of the user it is executing as. We now set the
HOME variable when running git commands with dropped privledges.
@cdituri you might want to check this out.
> Change: Improve git drop user support

- lib/services.cf
This will add a minimalist `standard_services` method.
I have multiple service libraries and wanted to be explicit about which one I use. Alas, I couldn't do that with the `standard_services`. Only way to use it is to omit the `service_method` entirely. Attempting to use it directly and you end up with:
* `error: Undefined body standard_services with type service_method`
Don't know if you wan't this in libs as it can be confusing for users. This would imply that you could change the method in libs and reap the benefits even if you don't use `service_method => standard_services` explicitly. Didn't test that tho, might even work like that ;)
> services: allow explicit use of standard_services

- lib/packages.cf
- modules/packages/Makefile.am
- modules/packages/freebsd_ports
- tests/unit/Makefile.am
- tests/unit/harness_freebsd_ports
- tests/unit/mock_freebsd_pkg
- tests/unit/test_package_module_freebsd_ports
This is my initial stab at adding support for the FreeBSD ports system via a package module.
Nice things:
* It exists and it works – yay FreeBSD support!
* It has no dependencies outside of the FreeBSD base system (other than assuming a bootstrapped pkg, which I think is reasonable)
* It's tested
Areas that (might) need work that I know of:
* The Architecture is faked at the moment
* It can't install more than one package at a time – it wasn't clear to me from the docs if this is necessary
* My m4 knowledge is non-existent so the way I've crammed my tests in is probably not ideal
> Add FreeBSD ports package module and tests

- controls/def.cf
- controls/update_def.cf
So that variables defined from the augments_file wins, specific
variables that are defaulted in bundle agent def.cf have been guarded
with isvariable. Additionally if the agent is capable of parsing the
augments file directly, skip doing the work.
> Change: Guard policy parsing of augments_file

- controls/def.cf
Classes are supposed to be defined only if their restricitons match a
class. This is already done by the following promise:
have_augments_classes.!feature_def_json_preparse::
"$(augments_classes_data_keys)"
expression =>
classmatch("$(augments[classes][$(augments_classes_data_keys)])"),
meta => { "augments_class", "derived_from=$(augments_file)" };
> Remove: Definition of override_classes

- inventory/linux.cf
Found myself in the need to know the IP address of the interface routed to default gateway.
This should help others bumping in to the same.
Dunno if the inventory is the right place for this.
> debian: Provide our default gateway interface name in variable

- modules/packages/yum
Yum has some packages with a version string in the name, so we need to
allow that. An example is java-1.6.0-openjdk.
Changelog: Installing packages containing version numbers using yum
now works correctly.
> Redmine #7825: Allow installation of yum packages with versions.

- modules/packages/pkgsrc
Fixes #654, #656, #657.
```
$ echo File=mtr | ./pkgsrc get-package-data
PackageType=repo
Name=mtr
```
> masterfiles#654 pkgsrc package module sometimes matches wrong package

- lib/packages.cf
- modules/packages/pkg
I finally got over the hump of implementing Policy Framework on my testing network, which gave a chance to do real-world testing with the pkg module.  It needed some tweaking.
The changes to packages.cf are because the pkg command has replaced the entire pkg_* suite of tools for all supported versions of FreeBSD.
> Update FreeBSD package handling.

- controls/def.cf
> Add log rotation policy for state/classes.jsonl log.

- promises.cf
- update.cf
This was previously commented out because older agents did not
understand the syntax. All currently supported versions understand this
syntax now, so it is safe to uncomment and set to a specific protocol
version.
> Change: Specify Protocol Version

- lib/vcs.cf
If we don't check that we have defined $(repo_uid) when setting the
need_to_drop class we end up with one pass of the agent executing with
elevated privileges. This lean leave artifacts like .git/index with
elevated ownership interfering with subsequent commands executed with
dropped privileges.
> Fix: Problem with git not dropping privileges soon enough

- controls/3.6/def.cf
- controls/3.6/update_def.cf
- controls/update_def.cf
Classes are supposed to be defined only if their restricitons match
class. override_classes were being defined all the time. The proper way
to augment classes is like this:
have_augments_classes.!feature_def_json_preparse::
"$(augments_classes_data_keys)"
expression => classmatch("$(augments[classes][$(augments_classes_data_keys)])"),
meta => { "augments_class", "derived_from=$(augments_file)" };
> Change: Remove definition of override_classes

- promises.cf
- tests/acceptance/promises/autorun-def_json.cf
- tests/acceptance/promises/autorun.cf
Ref: CFE-2135
This includes changes to one test so that it is expected to fail if
services_autorun is defined from policy. This also includes a new test that
when services_autorun is defined from def.json it does what is expected similar
to the test when services_autorun is defined as a command line option.
> Fix: Only parse services/autorun/*.cf when services_autorun is defined

- lib/files.cf
- tests/acceptance/lib/files/set_config_values.cf
- tests/acceptance/lib/files/set_line_based_config_values.cf
- tests/acceptance/lib/files/set_line_based_variable_values.cf
- tests/acceptance/lib/files/set_variable_values.cf
Ref: https://tracker.mender.io/browse/CFE-1959
To prevent class collisions between editing two files with similar formats we
scope the internal implementation classes to bundle scope. By default classes
defined from classes bodies are namespace scoped, so editing two files with
similar formats using the same edit_line bundle can be troublesome.
All of the edit_line bundles are now using the results classes body
consistently.  The results body was chosen for clarity. Note that previous ifok
body usage now uses (_kept|_repaired).
> Scope edit_line bundle classes

- lib/3.6/packages.cf
- lib/packages.cf
Default 'package_list_update_ifelapsed' was set to 0 for OpenSUSE.
This meant that every time package promise was evaluated SUSE repositories
were checked for the new updates.
This should make the behavior unified with other package promises, where
cache is hit every 240 minutes.
> Fix hitting zypper cache for every package promise in the policy.

- lib/cfe_internal_hub.cf
Rather than restricting the database maintenance to specifically
the first 5 minutes of the midnight - 1AM hour, restrict it only
to some point within that hour, and use 'if_elapsed_day' to
prevent multiple runs in a single day.
With the default execution schedule and default splaytime, this
will be effectively the same as before, but this change will
make the DB maintenance promises more robust against execution
schedule changes.  (E.g. if CFEngine only runs every 20 minutes
with an splaytime to match, it may never run in the Min00_05
interval and thus never perform the DB maintenance needed.
This commit fixes that.)
> Make Database purge schedule more robust

- .travis.yml
3.9 won't be compatible with 3.6 so we need to remove 3.6 check from Travis.
> Remove sanity checking for 3.6 version

- inventory/any.cf
- promises.cf.in
From 3.9 on the new package promise is the default package promise
implementation used by CFEngine.
Changelog: Use new package promise as default package promise
implementation. (CFE-2332)
> CFE-2332 Use new package promise by default.

- inventory/any.cf
The order is vars followed by classes, so the class
'!disable_inventory_LLDP' expression will always be true on the first
iteration. Fix by using a positive class match instead.
> CFE-2358: Fix lldpctl error messages due to promise order.

- lib/services.cf
This change will limit the output to only the required systemd properties and report if service is unknown, see:
* https://tracker.mender.io/browse/CFE-2086
> cfengine functions chokes on output generated by systemctl.  

- lib/3.6/services.cf
This change will limit the output to only the required systemd properties and   report if service is unknown, see:
Ref: Jira #CFE-2806
(cherry picked from commit b77e153fc564d8a43f8af57c0c5439795c8ed642)
> Fix: Stop cfengine choking on systemctl output

- lib/3.6/services.cf
This commit brings the fix into the 3.6 tree of masterfiles. This allows
mixed environments to take advantage of the fix as well.
Ref: Jira #CFE-2806
(cherry picked from commit bfe0b4d2f067a92da92e8db8635381d52dc3e62f)
> Fix: CFEngine choking on standard services

- tests/acceptance/testall
This defines the testing_masterfiles_policy_framework class. This will
allow us to omit the plucked.cf.sub bundle when running the masterfiles
policy framework. Omitting the bundle allows us to test the framework
directly.
Ref: Jira #CFE-2331
> Change: Define testing_masterfiles_policy_framework

- controls/cf_serverd.cf
By default we are not accepting legacy connections any more.
This is just update of the comment in the masterfiles.
> Change 'allowlegacyconnects' comment to reflect latest changes.

- cfe_internal/enterprise/mission_portal.cf
cfengine was spelled wrong.
(cherry picked from commit df40d100d51bf45ad11891d12841b0a60ba732a7)
> Fix: Typos in class guard

- cfe_internal/enterprise/templates/httpd.conf.mustache
This helps to prevent potential man in the middle attacks.
(cherry picked from commit 76d7bf3b95c188de6c8f8bac4b9d0acd46cc10c9)
> Change: Enable strict transport security

- controls/3.6/cf_execd.cf
- controls/cf_execd.cf
The agent will automatically append ' -Dfrom_cfexecd' if it is not found
in exec_command. This causes unexpected behavior when the appended
option replaces any custom definitions.
Jira #CFE-2386
> Add: Definition of from_cfexecd for cf-execd initiated runs

- cfe_internal/enterprise/ha/ha_update.cf
These bundles cause duplicate definition errors if the stdlib is
included by the update policy and enterprise ha is enabled.
Jira#ENT-2753
- ha_no_backup_scp renamed to ha_update_ha_no_backup_scp
- recurse renamed to ha_update_recurse
- if_reparied renamed to ha_update_if_repaired
- ex_list renamed to ha_update_ex_list
- plain renamed to ha_update_plain
- no_backup_cp renamed to ha_update_no_backup_cp
> Change: Rename duplicate bodies in ha_update.cf

- lib/services.cf
Hosts using sysv init without chkconfig were not detecting their current
state and were not discriminating service state changes against the
currently detected state.
> CFE-2420 Fix: Services starting or stopping unnecessarily

- lib/services.cf
Hosts using sysv init without chkconfig were not detecting their current
state and were not discriminating service state changes against the
currently detected state.
Jira #CFE-2421
(cherry picked from commit a44d8af6614a241672c3c4b59fbf12bc01ddb7d8)
> Fix: Services starting or stopping unnecessarily

- controls/3.6/def.cf
- controls/3.7/def.cf
The debug report indicated a file was found even if the file didn't
exist.
(cherry picked from commit 1eb592d85098938cbc52a7aa2f5d09e033f205ea)
> Change: Guard debug report so as not to mislead

- cfe_internal/update/update_policy.cf
cf-promises -r was removed in core commit
464ced0d5b9d92e2780e5bc72c9d042ac6faeb74. The function has been noop
since Jan 2014 when other enterprise mongo dependancies were removed.
> Remove: Unnecessary promise

- cfe_internal/update/update_processes.cf
The systemd units do not currently cover all hub process maintanance.
This policy is still required for proper hub functioning.
> Change: re-enable hub process maintainance

- configure.ac
Autoconf 2.63 is lacking both m4_ifblank and m4_esyscmd_s, so work
around the former with m4_ifval (which has reversed semantics) and the
latter with m4_normalize.
Also bump the version requirement while we're at it. Although I don't
know if the new macros were introduced in 2.63, we at least know they
are present there. Bump to 2.63 because:
* 2.64 has been (secretly) required for a long time, since the macros
I replaced in this commit were only available in that version and
later. I doubt anyone is using anything older.
* 2.63 is already eight years old.
* At least 2.63 is tested, we don't know about the older ones.
* It doesn't affect tarballs.
> Adapt autoconf code to autoconf 2.63.

- cfe_internal/update/update_processes.cf
The systemd unit does not manage any of the agent components after
initial start. This re-enables self healing and management of the
various cfengine components.
Jira #CFE-2429
> Change: Enable agent component management policy on systemd hosts

- cfe_internal/enterprise/file_change.cf
This comment may appear in logs outside of CFEngine,
e.g. for node initialization reports, so it is important
to make it clear and free of errors.
> Fix typos and clarify comment

- modules/packages/nimclient
Passing un-double quoted $options to eval is not what was intended here.
The contents of "options" in the previous version will be subjected to split, glob, and then *again* split, glob.
> Fix double-parsing of options

- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
> Skip new package promise tests on CentOS 4, which is not supported.

- controls/cf_agent.cf
It was confusing because it said "ifelapsed" takes an interval, but it doesn't; it takes an integer.
> Clarify comment on "ifelapsed" in controls/cf_agent.cf

- modules/packages/apt_get
- tests/unit/test_package_module_apt_get
Commit can be cherry-picked cleanly into 3.7.x, 3.8.x, 3.9.x as well.
> CFE-2468: Pass package promise options to underlying apt-get call

- inventory/any.cf
This prevents inventorying an empty list of ports wich can happen if
monitord isnt running.
> ENT-150 Change: Only inventory ports if some values make sense

- .gitignore
- cfe_internal/update/update_bins.cf
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
@nickanderson Would like review on this. Some changes to make custom ports work for cf-serverd and cf-agent. Not sure if this is the best way, but it seems to be working.
Ref: cfengine/core#2699
> CFE-953 policy changes for custom ports.

- tests/acceptance/lib/files/set_config_values.cf
- tests/acceptance/lib/files/set_config_values.cf.finish
- tests/acceptance/lib/files/set_line_based_config_values.cf
- tests/acceptance/lib/files/set_line_based_config_values.cf.finish
- tests/style_check.sh
Changelog: Behaviour change: when used with CFEngine 3.10.0 or greater,
bundles set_config_values() and set_line_based() are appending a
trailing space when inserting a configuration option with empty value.
> CFE-2466: adapt tests for new behaviour

- cfe_internal/enterprise/templates/httpd.conf.mustache
Stapling is problematic with self signed certificates, and since we use
a self signed cert by default we disable it.
> ENT-3016: Disable ssl stapling by default

- lib/paths.cf
This will define $(paths.path[bhyvectl]) on FreeBSD
> Add path to bhyvectl on FreeBSD

- controls/def.cf
- example_def.json
Using the IP in policy is the fastest way to get this working. The only drawback is it will not change the ACL before policy is re-evaluated. This can in some cases (but not all) cause connections to be refused after the hostname policy server has changed IP. 
Note that if the hostname policy server is within the same ACL, for example 192.168.x.x, it should still work fine.
> Fixed ACLs for hostnames in cf-serverd (CFE-2495)

- lib/files.cf
In order to be able to select a section that contains some special
characters we need to escape it.
> CFE-2519: Fix ability to manage an INI section and select the end of region

- cfe_internal/update/update_bins.cf
The client package can not be updated as legacy package promise
is not comparing packages versions correctly.
Signed-off-by: Marcin Pasinski <marcin.pasinski@cfengine.com>
> Fix issue with upgrading from 3.7 to 3.10 on RHEL.

- cfe_internal/enterprise/mission_portal.cf
This is fixing error error:
Link '/var/cfengine/ssl/cert.pem' points to '
/var/cfengine/httpd/ssl/certs/localhost.cert' not
'/var/cfengine/httpd/ssl/certs/localhost.localdomain.cert',
not authorized to override
Signed-off-by: Marcin Pasinski <marcin.pasinski@cfengine.com>
> Fix issue with regenerating MP certificate.

- modules/packages/apt_get
This commit allows using the python3 executable when python
executable is not there, like in the default with Ubuntu 16.04
install. It also fixes some incompatibilities of the code with Python 3.
> Fixes CFE-2445: Make apt_get module compatible with Ubuntu 16.04

- modules/packages/apt_get
- tests/unit/mock_apt_get
- tests/unit/test_package_module_apt_get
Options for behaviour we expect have changed in newer versions of
apt-get. This makes it version aware so that the correct options are
used by default.
Modified-by: Kristian Amlie <kristian.amlie@cfengine.com>
* Adapted unit test to accept new "apt-get -v" calls.
> CFE-2360: Make apt_get package module version aware

- modules/packages/Makefile.am
@BasementTrix we forgot to add these to the Makefile so that they would
be shipped with the package.
> Add: missing pkg and nimclient package modules

- modules/packages/apt_get
Popen() returns a "bytes" object in python3 which fails to
split(). Passing the universal_newlines parameter makes it return a
string.
> Fix python3 incompatibility.

- cfe_internal/enterprise/CFE_knowledge.cf
If the ssl certificate is not readable then things like scheduled
reports may fail to generate or be accessible.
> ENT-3050: Ensure MP SSL Cert is readable

- cfe_internal/enterprise/CFE_knowledge.cf
If the ssl certificate is not readable then things like scheduled
reports may fail to generate or be accessible.
(cherry picked from commit f49911f56e0256ae14ad108d08d10d632def0a39)
> Backport ENT-3050: Ensure MP SSL Cert is readable

- controls/reports.cf
This change adds a default exclusion for any promise with handle
matching noreport_.*. Any promise with a matching handle will not have
its promise outcomes collected by enterprise reporting. This aligns with
the pre-existing exclusions for variables and classes using a noreport
meta tag.
> ENT-3061: Add default report collection exclusion based on promise handle

- cfe_internal/update/update_bins.cf
CoreOS has a read only filesystem there.
> ENT-3047: Do not symlink agents to /usr/local/bin on coreos

- cfe_internal/update/update_policy.cf
This change ensures that a promise failure while updating inputs does
not leave the remote agent with the impression that
cf_promises_validated is reflective of the current state.
> CFE-2587: Make stock policy update more resiliant

- cfe_internal/enterprise/file_change.cf
The restriction was causing these files (/etc/shadow) to never be
monitored since it was iterating over the wrong list of files.
> ENT-3040: Fix opportunistic monitoring of files

- controls/cf_serverd.cf
> CFE-528: changine cf-serverd's control to bind to interface :: for IPv6.

- inventory/redhat.cf
- promises.cf.in
> CFE-2602: Disable package inventory via modules on redhat like systems with unsupported python versions

- lib/3.7/bundles.cf
The prunetree bundle allws you to delete files and directories up to a
sepcified depth older than a specified number of days.
(cherry picked from commit 8e4b1f83fa7a723b04bc7ec89cf5cbf0f17ccc39)
(cherry picked from commit f1e1295046c8657172e4b88ed71d435d4171a6fc)
> CFE-2608: Backport prunetree bundle to stdlib

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
> CFE-2624: Configure networks allowed to initiate report collection (client initiated reporting) via augments

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
* CFE-2624: Configure networks allowed to initiate report collection (client initiated reporting) via augments
* Update MPF.md
(cherry picked from commit 3a3c9412dd2696dd55369b4b9d25d32c8354cff2)
> CFE-2624: Configure networks allowed to initiate report collection (client initiated reporting) via augments (#910)

- controls/def.cf
- lib/paths.cf
> Switch to POSIX compliant shell tool paths on Solaris 9 and 10.

- MPF.md
- controls/def.cf
- lib/cfe_internal.cf
> ENT-3161: Include previous_state and untracked reports when client clear a buildup of unreported data

- MPF.md
- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/main.cf
> ENT-3186: Add policy to track CFEngine Enterprise license utilization

- controls/def.cf
> ENT-3191: Add postgres.log to enterprise log file rotation

- controls/3.7/def.cf
> ENT-3191: Ensure postgresql.log is rotated

- controls/cf_serverd.cf
Note that this does not fix the issue, it's just a workaround on windows.
> Do not use bindtointerface on windows (CFE-2662)

- .travis.yml
- tests/acceptance/testall
> Fix Masterfiles travis failures

- Makefile.am
By default "make install" uses the user's umask for directories, so run
"umask 022" in the beginning of the "tar-package" make target.
Additionally in the same "tar-package" target, `mktemp -d` is setting
the root folder's permissions to 700, so change it manually to 755.
Fixes ENT-3295, ENT-3299.
> Fix permissions of directories in the ready-to-install tarball.

- lib/services.cf
The failed promise messages are likely to make it clear enough what is going on
without this extra report. It is nice to have in inform_mode and verbose_mode.
> CFE-2690: Be less noisy when a promised service is not found

- controls/reports.cf
This change allows cf-hub to query the loopback address (127.0.0.1) when
collecting reports from itself.
> ENT-3329: Allow hubs to collect from themselves over loopback

- cfe_internal/enterprise/ha/ha_update.cf
If localhost.pub or localhost.priv get into the directory of collected
keys they can clobber the identiy of the active hub. This change purges
those files when they are seen before the keys from standby hubs are
synced.
> ENT-3303: Ensure that agent trust synchronization does not clobber hub identity

- cfe_internal/enterprise/ha/ha_update.cf
The am_policy_hub state marker is created when a host is bootstrapped to an ip
found bound to one of its interfaces. When standby hubs are bootstrapped to the
primary this state file is not created automatically and standby hubs may be
unable to determine their hub status. This change ensures that any host that
finds the IP of an HA hub member will have an am_policy_hub marker found in
state.
> ENT-3328: Ensure HA standby hubs have am_policy_hub state marker

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
Supersedes https://github.com/cfengine/masterfiles/pull/960
> ENT-3375: Allow configuration of allowlegacyconnects from augments

- MPF.md
- cfe_internal/enterprise/CFE_hub_specific.cf
This change prevents logging of Enterprise license utilization more frequently
than desired. It was being logged on each agent run instead of waiting for the
expected period of time to pass before logging triggered again. The promiser
contains $(sys.date) which is different for each agent run making the promise
unique on each run and the lock useless. Locking was traded out for a persistent
class which is defined and communicates that logging has happened. When the
class expires the promise will actuate again and the resulting class will
persist guarding it until the class expires.
> ENT-3390: Fix to frequent logging of enterprise license utilization

- standalone_self_upgrade.cf.in
This PR brings fixes for standalone self upgrade on agents older than 3.7.4 and addes support for 32bit deb and rpm platforms.
> ENT-3368 and ENT-3377: Fixs to standalone self upgrade

- modules/packages/apt_get
> ENT-3438: make apt_get package module work with repositories containing spaces in the label

- lib/paths.cf
f704e39e broke systemctl path detection.
> CFE-2722: Fix systemctl path detection

- lib/paths.cf
f704e39 broke systemctl path detection, reverting to previous behavior.
(cherry picked from commit f15d39d813b98ba9647dba67d49f12d5e8dd9972)
> Fix systemctl path detection

- lib/files.cf
This simply adds a declarative alternative to the existing bundles in the
stdlib to ensure one or more lines is present. insert_lines, append_if_no_lines,
and append_if_no_line are now considered aliases (copies) of this bundle.
> Add lines_present edit_lines bundle

- cfe_internal/enterprise/CFE_hub_specific.cf
This fixes an error about unescaped spaces in commands promises.
> ENT-3530: Move arguments to args attribute

- cfe_internal/enterprise/CFE_knowledge.cf
It is handled explicitly in it's own bundle.
> ENT-3534: Exclude settings.ldap.php from general permissions

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/main.cf
This also introduces a change in how enterprise maintenance policies will be
run. Now cfe_internal_enterprise_maintenance will run bundles tagged with
"enterprise_maintenance". The maintenance bundles themselves can determine when
it is appropriate for the tag to be defined. Currently only the bundles to
handle events and inventory cache refresh for Mission Portal use this new
methodology.
> ENT-3537: Add maintenance policy to refresh events table on enterprise hubs

- templates/host_info_report.mustache
This adds a list of the enterprise maintenance bundles that are available
in the policy to the host info report.
For example a host info report (`cf-agent -KIb host_info_report`) from a
policy hub would include this:
```
default:cfe_internal_refresh_events_table
default:cfe_internal_refresh_inventory_view
```
> ENT-3537: Add enterprise maintenance bundles to host info report

- cfe_internal/enterprise/CFE_hub_specific.cf
In some versions of CFEngine Enterprise report assets from the asynchronous
query api and scheduled reports are deposited in api/static under the docroot
instead of tmp under the docroot.
This ensures cleanup of that directory.
> ENT-3558: Include scheduled report assets in self maintenance

- cfe_internal/enterprise/CFE_knowledge.cf
In some versions of CFEngine (3.7.3-5, 3.10.0) access to exported reports will
break if the ssl directory does not have read and execute bits for other users.
(cherry picked from commit 0a3b35a88ff5960ca6def2b602b0afe8f884dbf6)
> ENT-3572: Maintain access to exported CSV reports in older versions

- cfe_internal/update/update_bins.cf
In 3.6.6 CFEngine published packages began containing a platform
identifier (el4, el6) to identify which platform a package was optimized for.
This allowed for users to download packages into the same directory without
overwriting the same package for an older platform.
This change aligns the filename the self upgrade policy looks for to include
this platform identifier.
> ENT-3603 Fix self upgrade for rpm packages with default names

- cfe_internal/update/update_policy.cf
This change tightens the context for informing users when the user specified bundle for policy update is missing. This change restricts the report to when a custom policy update bundle is defined, and when it is unable to be found.
> ENT-3624: Improve context notifying user of missing policy update bundle

- lib/files.cf
- tests/acceptance/lib/files/insert_ini_section.cf
The first commit makes the tests more deterministic, the second commit makes the produced INI files potentially better readable.
> Sort indicies for insert_ini_section()

- MPF.md
- controls/def.cf
- controls/update_def.cf.in
- promises.cf.in
- update.cf
This change allows configuring ignore_missing_inputs and ignore_missing_bundles
body common control options via augments. Note it affects both update.cf and
promises.cf entry points.
Example Augments:
```
{
"vars": {
"control_common_ignore_missing_inputs": "true",
"control_common_ignore_missing_bundles": "true"
}
}
```
> CFE-2773: Configure ignore_missing_inputs and ignore_missing_bundles via augments

- cfe_internal/enterprise/ha/ha_update.cf
This fixes an issue where on an ha enabled hub the update policy errors because it was using a definition of the bundle from stdlib in the update policy which does not include the stdlib. To correct the error I copied the body locally and renamed it to ha_tidy.
> ENT-3659 Localize delete tidy in ha update policy

- cfe_internal/enterprise/ha/ha_update.cf
This fixes an issue where on an ha enabled hub the update policy errors because
it was using a definition of the bundle from stdlib in the update policy which
does not include the stdlib. To correct the error I copied the body locally and
renamed it to ha_tidy.
> ENT-3659 Localize delete tidy in ha update policy 3.10.x

- cfe_internal/enterprise/ha/ha_update.cf
This fixes an issue where on an ha enabled hub the update policy errors because
it was using a definition of the bundle from stdlib in the update policy which
does not include the stdlib. To correct the error I copied the body locally and
renamed it to ha_tidy.
> ENT-3659 Localize delete tidy in ha update policy 3.7.x

- MPF.md
- controls/cf_serverd.cf
This fixes an issue introduce by the addition of the ability to specify the bundlesequence cf-agent should use during a request made by cf-runagent.
3.10.x and greater needs an open cfruncommand specification so that it can append the arguments like no locks and remote bundles.
> CFE-2776 Fix cf-runagent during 3.7.x -> 3.10.x migration

- MPF.md
- cfe_internal/update/update_policy.cf
- controls/update_def.cf.in
This change makes it to override the path where policy updates bound for
`$(sys.inputdir)` come from by setting a variable via an augments file.
With an augments like this:
```
{ 
"vars": { 
"house": "Gryffindor",
"mpf_update_policy_master_location": "/srv/cfengine/$(sys.flavor)/$(def.house)"
}
}
```
A CentOS 7 host would copy policy from `/srv/cfengine/centos_6/Gryffindor` to
`$(sys.inputdir)` (commonly `/var/cfengine/inputs`).
> ENT-3692 The path to source policy updates is tunable via augments

- cfe_internal/update/update_processes.cf
This conf file variable was moved into another bundle as part of some
refactoring to enable a more plugable policy update model for users to override with their own.
> ENT-3730 Fix variable used for redis conf file

- cfe_internal/core/main.cf
Before this change, these state files were being written to
C:\var\cfengine\state when run on windows.
> ENT-3839 Fix augments control state paths to work on windows

- modules/packages/pkgsrc
The regex matching in `get_package_data()` is too loose. For instance, a promise to install the `gmp` package resulted in `gmp-api` being installed. Because:
```
$ pkgin -pP avail | grep ^gmp-                
gmp-6.1.2;Library for arbitrary precision arithmetic
gmp-api-38.0;Headers for developing Gecko Media Plugins
```
We now look for `Name-[0-9]` in the available package list. The regex can't be any tighter than that, as it seems pretty much any character is allowed in the version number. So `File-[0-9\.]*;` will miss packages like `gmpc-tagedit-11.8.16nb8`.
> make package name matching more accurate

- modules/packages/pkgsrc
(cherry picked from commit c6d7ecc3daa70a7646ae4bf00a35d9150e18e550)
Signed-off-by: Craig Comstock <craig.comstock@northern.tech>
> make package name matching more accurate (3.12.x)

- modules/packages/pkgsrc
(cherry picked from commit c6d7ecc3daa70a7646ae4bf00a35d9150e18e550)
Signed-off-by: Craig Comstock <craig.comstock@northern.tech>
> make package name matching more accurate (3.10.x)

- cfe_internal/enterprise/CFE_hub_specific.cf
3.7.x does not support nested function calls as well as newer versions.
In order for the policy to be backwards compatible this needs to be
separated into multiple promises.
> ENT-3907 Fix policy compatibility for 3.7.x

- cfe_internal/enterprise/CFE_hub_specific.cf
In newer versions of cfengine the promise to run the bundles would have been
skipped if there were no bundles to run. This makes that behavior explicit, and
compatible with 3.7.0 to avoid an error about trying to actuate a bundle
that does not exist.
> ENT-3910 Fix policy backward compatibility

- controls/update_def.cf.in
Using '--prefix' with './configure' allows masterfiles to be
installed to a different location than
/var/cfengine/masterfiles. This location should then be respected
in the installed MPF policy.
> Better support non-standard location of mastefiles

- cfe_internal/update/update_processes.cf
- lib/common.cf
If scope is not set to namespace, then info messages are emitted and the class
is automatically scoped to namespace. This change prevents annoying messages and
retains the same behavior.
> CFE-2860 Specify scope => "namespace" when using persistent classes

- MPF.md
- templates/cf-runalerts.service.mustache
This change simply synchronizes the override template provided for convenience with the unit provided by the package.
> ENT-3923 Sync cf-runalerts override unit template with package

- controls/def.cf
See https://tracker.mender.io/browse/ENT-3946
> log file should only be on hub, causing errors on windows

- modules/packages/apt_get
We ignore held packages (`--ignore-hold`) so that all package updates available
are listed. This makes package update listing compatible with debian 8 and
higher `apt list --upgradeable`.
> CFE-2855 apt_get package module includes held packages when listing updates

- lib/files.cf
- tests/acceptance/lib/files/insert_ini_section.cf
The order of the key-value pairs doesn't matter in INI files, but
they are easier to read if it they are sorted by key.
Also make sure indices are sorted in the insert_ini_section()
test. Otherwise they may be in arbitrary order.
Use reverse(sort()) to make sure the sections in the resulting
file are alphabetically ordered (in combination with how
insert_ini_section() works).
(cherry picked from commit 8f8966f3460cae6cbacfd7feddaf9ff231d82209)
> Sort indices in insert_ini_section()

- standalone_self_upgrade.cf.in
This is quite a tricky thing to figure out so let's note it down
before we forget about it.
Ticket: ENT-3972
> Explanation why stdout redirect fixes package operations on AIX

- standalone_self_upgrade.cf.in
For unknown reasons the package fails to complete a self upgrade if the
output is not re-directed.
(cherry picked from commit 906f2773b843b43f89027a93b37560ca9333a2d6)
> ENT-3972 Fix unattended self upgrade on AIX for 3.12.x

- standalone_self_upgrade.cf.in
For unknown reasons the package fails to complete a self upgrade if the
output is not re-directed.
> ENT-3972 Fix unattended self upgrade on AIX for 3.10.x

- modules/packages/zypper
When a package has an epoch, in order to install the precise version
with zypper, it is required to write the complete version `epoch:version`
and `version` alone is not understood.
But currently the installed package cache does not store the
epoch, and a package with an epoch in the version will never be considered
as present.
This commits adds the `${epoch}:` before the version of the package
in the installed package database, allowing to install and
properly detect the package.
> Store the epoch of packages in cache db with zypper

- lib/services.cf
As I commented on CFE-2690, the fact that it's missing
doesn't indicate a problem.  Actually, when the promise
is that the service should be stopped or disabled, the
fact that it's missing is (philosophically speaking) a
'KEPT' outcome of the promise.  When it's supposed to
be started or restarted then of course it has to be
present.
Especially in an environment where CFEngine is used for
security enforcement and there is a big list of obsolete
services (insecure) that should be disabled if found,
it's quite annoying to see the 'could not be found'
message every time you turn on inform mode.
> CFE-2690: Prevent noise when a service that to be disabled is missing

- MPF.md
- cfe_internal/CFE_cfengine.cf
- controls/cf_serverd.cf
- controls/def.cf
This change allows different lists of users to be authorized for cf-runagent for policy servers and non policy servers.
> ENT-4054 Users allowed to request execution via cf-runagent can be configured via augments

- cfe_internal/update/update_bins.cf
- inventory/any.cf
- lib/bundles.cf
- lib/packages.cf
- lib/paths.cf
- lib/services.cf
- promises.cf.in
- standalone_self_upgrade.cf.in
- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_absent.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_absent.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_file_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_file_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_versioned_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_versioned_pkg_upgrade.cf
- tests/acceptance/17_packages/packages-info.cf.sub
Added sles hardclass This is done because parsing the /etc/os-release results in the harclasses sles and sles_<version>. The suse and suse_<version> are only available on SLES 12 SP 3 or lower because they still have the /etc/SuSE-release. This has been removed in SLES 15.
> CFE-2897 Consider sles when considering suse

- cfe_internal/update/update_bins.cf
- inventory/any.cf
- lib/bundles.cf
- lib/packages.cf
- lib/paths.cf
- lib/services.cf
- promises.cf.in
- standalone_self_upgrade.cf.in
- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_absent.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_multi_pkg_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_absent.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_file_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_file_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_pkg_upgrade.cf
- tests/acceptance/17_packages/11_old/unsafe/named_versioned_pkg_present.cf
- tests/acceptance/17_packages/11_old/unsafe/named_versioned_pkg_upgrade.cf
- tests/acceptance/17_packages/packages-info.cf.sub
This is done because parsing the /etc/os-release results in the harclasses sles and
`sles_<version>`. The suse and `suse_<version>` are only available on SLES 12 SP 3 or
lower because they still have the /etc/SuSE-release. This has been removed in SLES 15.
I have added the new hardclass instead of replacing it. So it's compatible with CFEngine 3.10.x LTS and 3.12.x LTS
> Added sles hardclass

- standalone_self_upgrade.cf.in
The variables used to record the desired version were referencing the incorrect bundle name.
> ENT-4092 Prevent standalone self upgrade from triggering un-necessarily

- standalone_self_upgrade.cf.in
The cf-agent run that is executed after upgrade is not necessary, and in some cases can contribute to the agent upgrade failing.
> ENT-4116 Remove un-necessary agent run during self upgrade

- standalone_self_upgrade.cf.in
- update.cf
Noteably on windows the path to workdir commonly contains spaces. The execution fails if the path is not quoted or the spaces are not escaped.
> ENT-4117 Fix standalone self upgrade when path contains spaces

- inventory/any.cf
This inventories the actual physical memory of the machine. Currently only dmidecode is leveraged when present to derive this information.
The value is cached for 1 day.
> CFE-2896 Inventory Physical Memory MB when dmidecode is found

- lib/packages.cf
According to Debian versioning
policy (https://www.debian.org/doc/debian-policy/ch-controlfields.html,
omitted. This way version '9999999999' is actually '0:9999999999' which is lower
than '1:0.0.1'. Please see attached patch which should correct this problem by
replacing '9999999999' with '999999999:9999999999'.
Thanks Egor.
> CFE-1743 Fix package_latest detecting larger version in some cases

- inventory/any.cf
When the agent observes a file that is setuid it is logged to `$(sys.workdir)/cfagent.$(hostname -f).log`.
This change introduces inventory for these observed files. For each file in the log that is setuid inventory of that file is tagged with `setuid Files`. Additionally separate inventory is done for each root owned setuid file as `root owned setuid Files`. This policy also handles clearing of files that were once setuid but are no longer found or are no longer setuid from the log since there is no pre-existing automatic processes to clear entries from the log.
merge with https://github.com/cfengine/nova/pull/1270
> ENT-4158 Inventory Setuid Files

- cfe_internal/recommendations.cf
Because of pre-evaluation the agent attempts to parse the file and fill the variable. Guarding it will avoid generating un-necessary errors where the policy is not explicitly active.
> CFE-2922 Avoid trying to read /proc/meminfo when it doesnt exist

- cfe_internal/recommendations.cf
On hosts that this policy is not explicitly active on we see errors trying to
read the file because of pre-evaluation.
(cherry picked from commit df4d1ea59692834b28266b6d26035552fb7f5e7f)
> CFE-2922 Avoid trying to read /proc/meminfo when it doesn't exist

- lib/services.cf
Because non-native services have UnitFileState=bad we need an alternate way to detect if the service is enabled or not.
> CFE-2932 Detect systemd service enablement for non native services

- lib/services.cf
Because non-native services have UnitFileState=bad we need an alternate way to
detect if the service is enabled or not. Since systemctl is-enabled
logs the fact that the service is not native to stderr, the probe must
be run in a shell and the output must be redirected to /dev/null or the
agent will output the information.
(cherry picked from commit a3b4260b81dae8a48b3dee55589616d6d47a82d9)
> CFE-2932 Detect systemd service enablement for non native services 3.12.x

- lib/services.cf
Because non-native services have UnitFileState=bad we need an alternate way to
detect if the service is enabled or not. Since systemctl is-enabled
logs the fact that the service is not native to stderr, the probe must
be run in a shell and the output must be redirected to /dev/null or the
agent will output the information.
(cherry picked from commit a3b4260b81dae8a48b3dee55589616d6d47a82d9)
> CFE-2932 Detect systemd service enablement for non native services 3.10.x

- .travis.yml
- lib/3.7/services.cf
Because non-native services have UnitFileState=bad we need an alternate way to
detect if the service is enabled or not. Since systemctl is-enabled
logs the fact that the service is not native to stderr, the probe must
be run in a shell and the output must be redirected to /dev/null or the
agent will output the information.
(cherry picked from commit a3b4260b81dae8a48b3dee55589616d6d47a82d9)
> CFE-2932 Detect systemd service enablement for non native services 3.7.x

- inventory/any.cf
This inventory attribtue can be useful in identification of AWS EC2
systems, as well as providing an additional way for detecting duplicate host identity.
(cherry picked from commit 6935a10e2f5292929a45263e6ab6a1ec75d39796)
> CFE-2925 Add 'system-uuid' to default dmidecode inventory

- MPF.md
- inventory/any.cf
Want to inventory another dmidecode attribute?
Instead of modifying the vendored policy, define dmidefs in augments.
For example:
```
{
"vars": {
"cfe_autorun_inventory_dmidecode": {
"dmidefs": {
"bios-vendor": "BIOS vendor",
"bios-version": "BIOS version",
"system-serial-number": "System serial number",
"system-manufacturer": "System manufacturer",
"system-version": "System version",
"system-product-name": "System product name",
"system-uuid": "System UUID",
"bios-release-date": "Bios release date",
"chassis-serial-number": "Chassis serial number",
"chassis-asset-tag": "Chassis asset tag",
"baseboard-asset-tag": "Baseboard asset tag"
}
}
}
}
```
DEBUG run output:
```
[root@hub masterfiles]# cf-agent -KID DEBUG_cfe_autorun_inventory_dmidecode
R: DEBUG cfe_autorun_inventory_dmidecode: …
```
> CFE-2927 Override dmidecode inventory attributes via augments

- MPF.md
- inventory/any.cf
This change allows uses to override the default dmidecode attributes that are
inventoried via augments. Being able to extend the inventoried attributes allows
for more flexibility without having to maintain modifications to the vendored
policy.
> CFE-2927 Allow dmidefs inventory to be overridden via augments

- inventory/any.cf
This inventory is not present in 3.12.x. It belongs to the Security
inventory category that is first introduced in Mission Portal in 3.13.0.
> Remove call to undefined bundle

- modules/packages/yum
Example:
```
[root@hub vagrant]# nano
bash: /bin/nano: No such file or directory
[root@hub vagrant]# cat test.cf
body file control {
inputs => {"/var/cfengine/inputs/lib/stdlib.cf"};
}
bundle agent main {
packages:
"nano"
policy => "present",
package_module => yum,
architecture => "x86_64",
options => { "--setopt=tsflags=nodocs" };
}
[root@hub vagrant]# cf-agent -f ./test.cf -IC -K
info: Successfully installed package 'nano'
[root@hub vagrant]# man nano
No manual entry for nano
[root@hub vagrant]# 
```
> ENT-4177: Updated yum package module to take arbitrary options

- cfe_internal/update/update_policy.cf
Policy servers avoid making a local connection to cf-serverd during policy
updates. cf-serverd is not always running, so this allows policy updates for the
hub itself, even when cf-serverd is not available (like during bootstrap). For
testing it is desirable to be able to excercise network access over the local
network. With this change if the mpf_skip_local_copy_optimization class is
defined, then policy update will happen over the local network.
> CFE-2932 Update policy can now skip local copy optimization on policy servers

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/main.cf
This is exactly the same as PR #1235 but with the branch renamed and the changelog line added to the last commit message as per Nick Anderson's request.
> Ent 4190 hub license usage logging performance

- MPF.md
> Fix an example of setting control_hub_hub_schedule to be a valid JSON

- MPF.md
Otherwise it fails to parse.
(cherry picked from commit f60fb1535af53ebc26d5b219c139ca8cd2419002)
> [3.12.x] Fix an example of setting control_hub_hub_schedule to be a valid JSON

- controls/update_def.cf.in
This error prevents pulling policy updates from from def.mpf_update_policy_master_location:
if => isvariable( $(def.mpf_update_policy_master_location) );
should be:
if => isvariable( "def.mpf_update_policy_master_location" );
> CFE-2953 - fix isvariable syntax error in update_def.cf

- cfe_internal/enterprise/CFE_hub_specific.cf
This change causes the runalerts.php process to be killed if the script has been altered. There already exists a promise to start the service if appropriate.
If the service is not restarted, then the changes to the runalerts script will not be in effect, and Mission Portals ability to notify on alert conditions may be impaired.
> ENT-4273 Restart runalerts if modified

- cfe_internal/enterprise/templates/runalerts.php.mustache
These frequent log messages add up in large environments, we only want to log
information when there is a problem.
(cherry picked from commit a58188676ab42686cbe2c8e8be1c5929ad4ff249)
> ENT-4235 Make runalerts quiet during normal operation 3.12.x

- cfe_internal/enterprise/templates/runalerts.php.mustache
These frequent log messages add up in large environments, we only want to log
information when there is a problem.
> ENT-4235 Make runalerts quiet during normal operation 3.10.x

- cfe_internal/enterprise/CFE_hub_specific.cf
…ense utilization logging
This is a fixup of pull request #1248 which was already merged to master.
Prior to #1248, any CFEngine Hub which had license utilization logging
enabled would call the expensive "hostswithclass()" and "hostsseen()"
functions during every agent run, even though the results are only
needed once every 12 hours.
In #1248, I fixed things up so that a 12 hour persistent class would be
set to indicate that the logging had been done, so that the hub would
not make these expensive function calls.
However in reviewing this code in light of a recently observed
performance problem, I found that I made a mistake in #1248 such that
any enterprise hub where the license utilization logging was NOT
enabled, would, during every run, make the function calls to
"hostswithclass()" …
> ENT-4333 Prevent performance overhead on hubs that don't enable license utilization logging

- lib/cfe_internal_hub.cf
The status table name was reversed for the version of policy
> ENT-4331 Fix status table name

- cfe_internal/update/update_policy.cf
Fix MPF reporting both "found" and "missing" regarding the user-defined
update policy bundle.
The fix is to stop relying on negative knowledge (absense of "found"
class) and instead rely on positive knowledge only ("found" class
for if found; and "missing" class for if missing).
> Improve efficiency and resiliance configuring custom update policy

- cfe_internal/update/update_policy.cf
Fix MPF reporting both "found" and "missing" regarding the user-defined
update policy bundle.
First, note that
https://docs.cfengine.com/docs/3.10/reference-functions-some.html says:
> It's convenient to set a class to not => some(".*", mylist) in order to
> check if mylist is empty. Since some() returns as soon as possible, that
> is better than using length() or every() or none() which must traverse
> the entire list.
So I switched to some().
Second, let's stop relying on negative knowledge (absense of "found"
class) and instead rely on positive knowledge only ("found" class
for if found; and "missing" class for if missing).
(cherry picked from commit 26eb50bd827e88041fac2c90b026f781e79d9055)
> Improve efficiency and error handling of user specified policy update bundle

- lib/cfe_internal_hub.cf
Use a new cleanup_historical_data SQL function that keeps a specified number of items for a host
Superceeds #1307
> ENT-4365: Change cleanup consumer status SQL query

- lib/packages.cf
As it was part of a common bundle, it was executed everytime even when
not using old package promises. Furthermore, this simple yum command lead
to contact the server in some cases. As the option was introduced in RHEL 6.1,
use the RHEL version instead of dynamic detection.
> CFE-2993: Avoid calling yum at every agent run

- lib/cfe_internal_hub.cf
An issue with clocks, or client side database corruption can cause the
timestamps in the status table to become huge. This creates a problem patching
reports as the timestamps no longer reflect real ranges. This change ensures
that any timestamps for report collection status records that are in the future
will be purged, thus maintaining the ability to properly calculate deltas
between time ranges.
> ENT-4362 Purge collection status records from the future

- cfe_internal/enterprise/mission_portal.cf
Constrain vars promises in cfe_internal_enterprise_mission_portal_apache
to policy_server.enterprise_edition::, otherwise "cf-promises --show-vars"
includes a dump of the entire datastate from the "data" variable in
cfe_internal_enterprise_mission_portal_apache (line over 100K long).
> CFE-3011: guard vars promises in CFE Internal Mission Portal Apache

- inventory/redhat.cf
> CFE-3022: Fedora no longer defines redhat_pure

- inventory/redhat.cf
The agent defines the redhat class on fedora hosts. Fedora isn't really a
derivative of redhat, it's the other way around. But Fedora is definitely not
pure redhat.
(cherry picked from commit b72953241bd91c3f2226379a3fd267d3a33e8fd7)
> :CFE-3022: redhat_pure is no longer defined on Fedora hosts

- inventory/redhat.cf
The agent defines the redhat class on fedora hosts. Fedora isn't really a
derivative of redhat, it's the other way around. But Fedora is definitely not
pure redhat.
(cherry picked from commit b72953241bd91c3f2226379a3fd267d3a33e8fd7)
> CFE-3022: redhat_pure is no longer defined on Fedora hosts

- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/dump.sh
- templates/federated_reporting/filter.sed
- templates/federated_reporting/import.sh
- templates/federated_reporting/import_file.sh
- templates/federated_reporting/log.sh.mustache
- templates/federated_reporting/parallel.sh
- templates/federated_reporting/transport.sh
The configurable parts are only in the config.sh.mustache and
log.sh.mustache files, the other files just use the configuration
rendered by the policy with those two templates.
Ticket: ENT-4473
Changelog: Added scripts and templates for Federated Reporting
> Add scripts and templates for Federated Reporting

- controls/cf_serverd.cf
This change was prompted by a warning from a missing directory.
/var/cfengine/bin/cf-serverd --no-fork --info
info: Failed to canonicalise filename '/var/cfengine/templates' (realpath: No such file or directory)
info: Path does not exist, it's added as-is in access rules: /var/cfengine/templates
info: WARNING: this means that (not) having a trailing slash defines if it's (not) a directory!
> CFE-3024: Add trailing slash to access promises expecting directories

- controls/cf_serverd.cf
This change was prompted by a warning from a missing directory.
/var/cfengine/bin/cf-serverd --no-fork --info
info: Failed to canonicalise filename '/var/cfengine/templates' (realpath: No such file or directory)
info: Path does not exist, it's added as-is in access rules: /var/cfengine/templates
info: WARNING: this means that (not) having a trailing slash defines if it's (not) a directory!
(cherry picked from commit 2008e6a77c60b906fb4f3b000284ffa26cb9cad1)
> CFE-3024: Add trailing slash to access promises expecting directories (3.12.x)

- controls/cf_serverd.cf
This change was prompted by a warning from a missing directory.
/var/cfengine/bin/cf-serverd --no-fork --info
info: Failed to canonicalise filename '/var/cfengine/templates' (realpath: No such file or directory)
info: Path does not exist, it's added as-is in access rules: /var/cfengine/templates
info: WARNING: this means that (not) having a trailing slash defines if it's (not) a directory!
(cherry picked from commit 2008e6a77c60b906fb4f3b000284ffa26cb9cad1)
> CFE-3024: Add trailing slash to access promises expecting directories (3.10.x)

- update.cf
The desired version state data is written by standalone_self_upgrade.cf, which
is triggered when trigger_upgrade is defined and the running agent version does
not match the desired version.
The desired version defaults to the version of the MPF when it was built and can
be overridden via augments.
Once the agent was at the desired version, the standalone_self_upgrade.cf policy
would never trigger, because the running version would match the desired version
data. Since it would not run, it would not update the desired version data.
This change purges the desired version state data when it is older than the
standalone_self_upgrade.cf. This way, when the policy changes there will not be
stale data preventing upgrade.
(cherry picked from commit …
> ENT-4317 Fix standalone_self_upgrade not triggering because of stale data (3.12.x)

- update.cf
The desired version state data is written by standalone_self_upgrade.cf, which
is triggered when trigger_upgrade is defined and the running agent version does
not match the desired version.
The desired version defaults to the version of the MPF when it was built and can
be overridden via augments.
Once the agent was at the desired version, the standalone_self_upgrade.cf policy
would never trigger, because the running version would match the desired version
data. Since it would not run, it would not update the desired version data.
This change purges the desired version state data when it is older than the
standalone_self_upgrade.cf. This way, when the policy changes there will not be
stale data preventing upgrade.
(cherry picked from commit …
> ENT-4317 Fix standalone_self_upgrade not triggering because of stale data (3.10.x)

- lib/packages.cf
centos and redhat don't have exactly the same classes. For example, on centos
6.5 you will find centos, centos_6, centos_6_5, redhat, and redhat_derived
```
[root@hub ~]# cf-promises --show-classes | awk '/centos|redhat/ {print $1}'
centos
centos_6
centos_6_5
redhat
redhat_derived
```
(cherry picked from commit b561c38a99c49dc0f32fbbbd78c1fecd53dc07a5)
> Handle exit_on_lock for centos (3.10.x)

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that the files used by the asynchronous query API are
writable by the web server so that the status can be correctly updated. Without
being writable scheduled reports may hang and never complete.
> ENT-4551 Ensure that asynchronous query API semaphores are writable

- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/dump.sh
- templates/federated_reporting/pull_dumps_from.sh
- templates/federated_reporting/transport.sh
Making the superhub pull the dump files from the feeder hubs is a
better strategy than pushing the files from the feeder hubs to
the superhub. The superhub knows better when it has a capacity to
process the files and also, there's only one SSH private key that
has to be kept safe -- the superhub's key.
However, in some situations the push approach may be necessary so
let's not just delete the functionality. The transport.sh script
can easily support both modes.
Ticket: ENT-4499
> Add support for pull to FR/transport.sh

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that the files used by the asynchronous query API are
writable by the web server, so that the status can be correctly updated. Without
being writable scheduled reports may hang and never complete.
(cherry picked from commit 446b54e46f9dd804a8b5329eacb361009b568e1b)
> ENT-4551 Ensure that asynchronous query API semaphores are writable (3.12.x)

- cfe_internal/enterprise/CFE_knowledge.cf
This change ensures that the files used by the asynchronous query API are
writable by the web server, so that the status can be correctly updated. Without
being writable scheduled reports may hang and never complete.
(cherry picked from commit 446b54e46f9dd804a8b5329eacb361009b568e1b)
> ENT-4551 Ensure that asynchronous query API semaphores are writable (3.10.x)

- templates/federated_reporting/transport.sh
To make sure the dump files are not piling up in case of repeated
failures.
> FR: Remove dumps that failed to be transported

- cfe_internal/enterprise/CFE_knowledge.cf
The database user must be able to access the parent directory of where the
database is installed or it won't function.
> ENT-4601 Accounted for database needs in state permissions

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/enterprise/main.cf
statedir promises have been moved from bundle agent cfe_internal_setup_knowledge
which was only run on a hub to a bundle that executes on clients as well so that
we can be sure that client permissions are restrictive as well.
Ticket: ENT-4601
> ENT-4601: Refactored sys.statedir permission and ownership handling (3.10)

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/enterprise/main.cf
statedir promises have been moved from bundle agent cfe_internal_setup_knowledge
which was only run on a hub to a bundle that executes on clients as well so that
we can be sure that client permissions are restrictive as well.
Ticket: ENT-4601
(cherry picked from commit fe6d1fc39c6b179b84658ae87c037e9c51a620b6)
> ENT-4601: Account for database needs in state permissions (3.12)

- lib/cfe_internal_hub.cf
https://github.com/cfengine/nova/pull/1408/files
https://github.com/cfengine/masterfiles/pull/1384
> ENT-4588: Respect history_length_days when doing promise log cleanup

- cfe_internal/enterprise/main.cf
The "Permissions and Ownership" policy is only suitable for UNIX systems.
> ENT-4628: Could not look up name 'root' (LookupAccountName)

- cfe_internal/enterprise/main.cf
The "Permissions and Ownership" policy is only suitable for UNIX systems.
(cherry picked from commit 7e82bb814218bb6f7675994ccd2bab4e4e09b5b0)
> ENT-4628: Could not look up name 'root' (LookupAccountName) (3.10.x)

- cfe_internal/enterprise/main.cf
The "Permissions and Ownership" policy is only suitable for UNIX systems.
(cherry picked from commit 7e82bb814218bb6f7675994ccd2bab4e4e09b5b0)
> ENT-4628: Could not look up name 'root' (LookupAccountName) (3.12.x)

- modules/packages/zypper
It may not be installed on the system, and is not strictly necessary for
the package module.
> Avoid requiring rpm python module to check zypper version

- controls/cf_agent.cf
Not only when the mpf_control_agent_default_repository class is
defined.
> Always set files_single_copy from augments if available

- controls/cf_agent.cf
Not only when the mpf_control_agent_default_repository class is
defined.
Ticket: CFE-3064
(cherry picked from commit b8f0f0ddc29a2c46538c238dd853df2568723d4d)
> Always set files_single_copy from augments if available (3.12.x)

- controls/cf_agent.cf
Not only when the mpf_control_agent_default_repository class is
defined.
(cherry picked from commit b8f0f0ddc29a2c46538c238dd853df2568723d4d)
> Always set files_single_copy from augments if available (3.10.x)

- cfe_internal/enterprise/federation/federation.cf
> ENT-3734: fix dependency on transport_user when superhub not enabled

- controls/cf_serverd.cf
Not only when the mpf_control_agent_default_repository class is
defined.
Ticket: CFE-3064
(cherry picked from commit b8f0f0ddc29a2c46538c238dd853df2568723d4d)
> Set default access promises for directories only if directories exist (3.12.x)

- controls/cf_serverd.cf
In particular, /var/cfengine/templates does not exist by default. Running
cf-serverd with log level info emits messages noting the path does not exist.
info: Failed to canonicalise filename '/var/cfengine/templates/' (realpath: No such file or directory)
info: Path does not exist, it's added as-is in access rules: /var/cfengine/templates/
Instead of sending a user chasing to see if something is wrong, we now just
avoid providing access to paths that are not directories when we expect them to
be.
Ticket: CFE-3060
(cherry picked from commit 353169594ff6d1377350d56029fe60dd88677f40)
> Set default access promises for directories to only share if directory exists (3.10.x)

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
Refreshing inventory on a superhub with tens of thousands of
hosts can easily take a couple minutes and thus should not be
part of every agent run. It's also not necessary to refresh the
inventory on a superhub too often because reporting data only
changes when successfully imported from the feeder hubs.
Let's just refresh the inventory after a successfull data import
on the superhub.
Ticket: ENT-4527
> Refresh inventory after import on superhub

- tests/check_policy.sh
Can easily be used as a git hook (e.g. pre-commit).
> Add a simple script to check that the policy is correct

- cfe_internal/enterprise/CFE_hub_specific.cf
They all just fail because the DB is read-only on a passive HA
hub. Changes are done on the active one and replicated.
Ticket: ENT-4706
> Do not run DB maintenance tasks on a passive HA hub

- cfe_internal/enterprise/CFE_hub_specific.cf
They all just fail because the DB is read-only on a passive HA
hub. Changes are done on the active one and replicated.
Ticket: ENT-4706
(cherry picked from commit 704e262c54ff818d3bd622a48fe70d65d9bc5bf2)
> [3.12.x] Do not run DB maintenance tasks on a passive HA hub

- cfe_internal/enterprise/federation/federation.cf
Makes sure the file is accessible to MP after the first run.
Permissions were being fixed on the second run before.
> ENT-4724: Added explicit perms to setup-status.json

- cfe_internal/enterprise/federation/federation.cf
The host key is a good unique identifier of the feeder and will
help us to identify the partition/schema to insert the data into.
Ticket: ENT-4613
> Use the feeder's key digest in names of its dump files

- cfe_internal/enterprise/federation/federation.cf
Systems may have various restrictions for SSH key types they
use. Let's just leave it to the system configuration to
decide. One of the problematic cases here is RHEL 6 which has an
older version of SSH that doesn't support the specific key type
we were trying to use.
Because we no longer specify the key type, we need to specify the
key file name and then make sure it is being used (SSH only uses
the default-named keys like id_rsa, id_dsa,...).
> Do not require specific SSH key type for FR

- cfe_internal/enterprise/ha/ha.cf
Aligned explicit permissions for ha_enabled semaphore with default for htdocs
preventing continual permission repair.
Ticket: ENT-4715
(cherry picked from commit 49294d9ff01c10157838ce4af3d313036cb8004c)
> Fixed continual repair of permissions for ha_enabled semaphore in Enterprise edition

- cfe_internal/enterprise/federation/federation.cf
The imported_data promise needs to happen after ensure_feeders promise
now that we are using pull_over_rsync as default.
> ENT-4798: first import fails with pull_over_rsync

- cfe_internal/enterprise/federation/federation.cf
Together with the rest of the ETL process this should result in
data being refreshed on the superhub every ~30 minutes.
Also note that we don't have to change the interval on the
superhub because there we want to always try to get fresh dumps
and import them. Of course, normal promise locking rules apply so
an import will only start once the previous one is done.
Ticket: ENT-4806
> Dump data on feeders every 20 minutes not in every agent run

- templates/federated_reporting/parallel.sh
When waiting for the jobs to finish, we need to wait for one at a
time, check its exit code and record it in case of
failure. Waiting for all jobs at once just gives us an exit code
of a random one of them. So a failure can potentially be
ignored. 'xargs' and 'parallel' both handle this for us.
> Fix failure propagation in parallel.sh when using background jobs

- MPF.md
- cfe_internal/core/main.cf
Previously, we relied only on the presence of the am_policy_hub state file for
classification. This change regularly checks to see if the executing host is
bootstrapped to an ip found on itself, and if so it ensures the state file is
present. This helps to avoid accidental declassification from the accidental
removal of the state file. It uses the same logic that is used during bootstrap.
Ticket: CFE-3073
> CFE-3073: Added continual checking for policy_server state (master)

- lib/cfe_internal_hub.cf
To aid in determining performance of postgresql and specifically
Federated Reporting superhubs.
> ENT-4753: Added monitoring for postgresql lock acquisition times.

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
- templates/federated_reporting/import_file.sh
Added __inventory table to whitelist of tables to import.
Rely on feeders for __inventory data instead of running large
update on superhub.
merge with https://github.com/cfengine/nova/pull/1461
> ENT-4842: partitioned __inventory table for federated reporting

- cfe_internal/enterprise/federation/federation.cf
SSH generates host keys of multiple types in modern systems. We
need to make sure all host keys from each feeder are trusted by
the superhub because only the mutual negotiation between the
superhub and each feeder determines which type of the key is used
(and thus needs to be trusted).
Ticket: ENT-4917
Changelog: Made keys of all types from feeder hubs trusted on a superhub
> Make sure superhub trusts all SSH keys provided by its feeders

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/psql_wrapper.sh
- templates/federated_reporting/psql_wrapper.sh.mustache
On systems which have other versions of psql binary earlier
in $PATH psql_wrapper will likely fail to connect to database.
> ENT-4912: psql_wrapper needed full path to psql binary

- modules/packages/yum.in
Process output in Python 3 is of type 'bytes' which cannot be
treated as string. It first needs to be decoded into a (unicode)
string. In Python 2 it is a string which can be decoded into a
unicode object. So in both cases it is safe to do
`output.decode("utf-8")` to get a valid string-like object.
Changelog: Fixed Python 3 incompatibility in yum package module
> Fix Python 3 incompatibility in yum package module

- cfe_internal/enterprise/federation/federation.cf
- lib/paths.cf
On Centos6 the agent was unable to generate a key with
ssh-keygen due to mismatched contexts on cftransport .ssh
dir.
> ENT-4906: added ssh_home_t type to cftransport .ssh dir

- cfe_internal/enterprise/federation/federation.cf
- lib/paths.cf
Reverts cfengine/masterfiles#1479
The PR broke the FR tests.
> Revert "ENT-4906: added ssh_home_t type to cftransport .ssh dir"

- inventory/any.cf
This change suppresses output on stderr during lldpctl inventory when using
lldpctl from an expected path. When lldpctl is inventoried by the executable
identified by def.lldpctl_json (a user supplied value, likely defined via
augments) we do not execute with shell.
> CFE-3109 Suppressed stderr output from lldpctl when using nonstandard path

- Makefile.am
- configure.ac
- modules/packages/yum.in
- tests/Makefile.am
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
- tests/unit/test_package_module_apt_get
- tests/unit/test_package_module_yum
Required for us to be able to run tests on RHEL 8.
https://github.com/cfengine/core/pull/3813
https://github.com/cfengine/masterfiles/pull/1492
https://github.com/cfengine/buildscripts/pull/612
> Python 3 support in pkg modules and their unittests

- CONTRIBUTING.md
Link target was renamed in cfengine/core@57a6fe96.
> CONTRIBUTING.md: Fixed links to core documentation

- modules/packages/pkgsrc
In the package module: pkgsrc read -r -u 0 is used.
-u 0 doesn't work on Solaris or NetBSD. Because of this the pkgsrc modules doesn't work on these platforms.
-u 0 dictates to read from STDIN, that is the default. Becuase of this is harmless to remove the -u 0 parameter. I have tested in Solaris 11 using the pkgsrc module.
> pkgsrc: read -u 0 doesn't work on Solaris/NetBSD

- MPF.md
- cfe_internal/update/update_processes.cf
A small typo prevented non-default systemd unit management to fail.
By default MPF doesn't manage systemd units. This must be enabled
in cfe_internal/update/update_processes.cf. After this the standard
disabling mechanism works: https://docs.cfengine.com/docs/3.12/reference-masterfiles-policy-framework.html#enable-or-disable-cfengine-components
> Fixed agent disabling on systemd systems

- MPF.md
- cfe_internal/update/update_processes.cf
Reverts cfengine/masterfiles#1513 because deployment tests are broken
> Revert "CFE-3416/3.12.x: Fixed agent disabling on systemd"

- MPF.md
- cfe_internal/update/update_processes.cf
Reverts cfengine/masterfiles#1514 because deploy tests are failing
> Revert "CFE-3146/3.10: Fix agent disablement on systemd systems"

- inventory/any.cf
Ticket: ENT-4987
This change adds separate inventory for IPv6 addresses (excluding the loopback
::1, to align with the exclusion of 127.0.0.1 already in place for IPv4
addresses).
- The bundle name was changed from `cfe_autorun_inventory_ipv4_addresses` to
`cfe_autorun_inventory_ip_addresses` to better describe the fact that ipv6
inventory is also handled.
- Promisee/Stakeholders were added to better document history
> ENT-4987/master: Added OOTB inventory for IPv6 addresses (sans ::1 loopback)

- modules/packages/freebsd_ports
Something I had sitting around in my own version of this package, doing some spring cleaning :)
Provide a meaningful error message if the `whereis` check returns nothing (i.e. port not found) rather than a meaningless message from make.
> Check if port exists before attempting to uninstall it on FreeBSD

- MPF.md
- cfe_internal/core/main.cf
This change implements support for avoiding the policy to limit robot agent
daemons without having to modify vendord policy. Useful in testing, and in
environemnts where you might expect to find multiple agent daemon proceses
when looking at a hosts process table (cfengine running inside containers
for example).
Ticket: CFE-3161 Changelog: Title
(cherry picked from commit 19bec84cdf4f6f5f7188341a9cacf38f97c82e7b)
> CFE-3161/3.12.x: Added ability to avoid limiting robot agents

- MPF.md
- cfe_internal/core/main.cf
This change implements support for avoiding the policy to limit robot agent
daemons without having to modify vendord policy. Useful in testing, and in
environemnts where you might expect to find multiple agent daemon proceses
when looking at a hosts process table (cfengine running inside containers
for example).
Ticket: CFE-3161 Changelog: Title
(cherry picked from commit 19bec84cdf4f6f5f7188341a9cacf38f97c82e7b)
(cherry picked from commit bd5557a47319ddbdb289d849d6c5e78f9b374da4)
> CFE-3161/3.10.x: Added ability to avoid limiting robot agents

- lib/paths.cf
(cherry picked from commit ffd47c6ac1580af42575a90cdc3cf1e16282431a)
> 3.10.x: lib/paths.cf: Add usermod path for redhat systems

- lib/cfe_internal_hub.cf
This promise to purge timestamps from the future was not adjusted with the
change in name of the status table in ENT-4331. It results in this error being
emitted once a day.
```
error: Finished command related to promiser '/var/cfengine/bin/psql cfdb -c
"DELETE FROM status WHERE to_timestamp(ts::bigint) > (now() + interval '2
days')::timestamp;"' – an error occurred, returned 1
notice: Q: "...e/bin/psql cfdb": ERROR: unrecognized configuration parameter
"rbac.filter"
error: Method 'cfe_internal_database_cleanup_consumer_status' failed in some
repairs
```
> ENT-4992/master Fixed cleanup of future timestamps from status table

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
- standalone_self_upgrade.cf.in
The self upgrade policy previously fetched from a fully qualified path. This is
problematic when the hub does not use the standard WORKDIR (/var/cfengine). This
change implements a shortcut for the directory so that only the hub is required
to know the full path and switches copy_from to use paths relative to the
shortcut. Additionally, the path can be customized via augments.
> ENT-4953/master: Added and transitioned to using master_software_updates shortcut

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
- standalone_self_upgrade.cf.in
The self upgrade policy previously fetched from a fully qualified path. This is
problematic when the hub does not use the standard WORKDIR (/var/cfengine). This
change implements a shortcut for the directory so that only the hub is required
to know the full path and switches copy_from to use paths relative to the
shortcut. Additionally, the path can be customized via augments.
Ticket: ENT-4953
(cherry picked from commit 21ab5b938ef40f4967871dd934f6f51dcc8f5b9d)
> ENT-4953/3.12.x: Added and transitioned to using master_software_updates shortcut

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
- standalone_self_upgrade.cf.in
The self upgrade policy previously fetched from a fully qualified path. This is
problematic when the hub does not use the standard WORKDIR (/var/cfengine). This
change implements a shortcut for the directory so that only the hub is required
to know the full path and switches copy_from to use paths relative to the
shortcut. Additionally, the path can be customized via augments.
Ticket: ENT-4953
(cherry picked from commit 21ab5b938ef40f4967871dd934f6f51dcc8f5b9d)
> ENT-4953/3.10.x: Added and transitioned to using master_software_updates shortcut

- lib/cfe_internal_hub.cf
This promise to purge timestamps from the future was not adjusted with the
change in name of the status table in ENT-4331. It results in this error being
emitted once a day.
```
error: Finished command related to promiser '/var/cfengine/bin/psql cfdb -c
"DELETE FROM status WHERE to_timestamp(ts::bigint) > (now() + interval '2
days')::timestamp;"' – an error occurred, returned 1
notice: Q: "...e/bin/psql cfdb": ERROR: unrecognized configuration parameter
"rbac.filter"
error: Method 'cfe_internal_database_cleanup_consumer_status' failed in some
repairs
```
Ticket: ENT-4992
(cherry picked from commit f5a38bfc89d05383702b4007546eb1c586c9d74d)
> Fixed cleanup of future timestamps from status table

- modules/packages/zypper.in
The current package modules in cfengine hide all errors which make it quite bothersome to debug. Since the package module API offers a way to report errors, I did a small change to the zypper package module to make it reports if anything is prompted on stderr while calling the module.
It does not report on which item is causing the error since it is optional and would need way more changes in the module. Moreover, in most of the case, the error messages are explicit enough to find out the root issue.
> Enhance zypper package module error logs

- standalone_self_upgrade.cf.in
This fixes a typo so that the DEBUG report to show the used curl commands for
bulk downloading enterprise binaries will work correctly.
> ENT-5006/master: Fixed typo in DEBUG report

- standalone_self_upgrade.cf.in
CFEngine version classes use '_' as a separator between major,
minor and patch version numbers. '.' in a class expression means
logical "and".
Ticket: CFE-3182
Changelog: Fixed the CFEngine 3.7.x class guard in standalone_self_upgrade.cf
> Fix the CFEngine 3.7.x class guard in standalone_self_upgrade.cf

- update.cf
While prepping for a client upgrade, we found this to be too noisy. Before an upgrade attempt, at_desired_version was never set so this never triggered. Once a host upgraded and the standalone_self_upgrade created the json file that provided a defnition for this variable, we see it every time we run update.cf in inform mode.
As a workaround, we changed the code to only provide the report if the trigger_upgrade class is set AND at_desired_version
Mike Weilgart and Aleksey Tsalolikhin asked me to submit this change as an upstream pull request
> Only report on skipped upgrade if trigger_upgrade is set

- travis-scripts/valgrind.sh
This test failed 2/5 times in the recent master builds,
because cf-serverd didn't exit in time. Increasing the
sleep from 30 to 40 seconds, to see if this helps.
We could probably work on a system which sleeps 10
seconds at a time, and checks if the process is
still alive.
> Travis: Sleep 10 more seconds after killing cf-serverd

- travis-scripts/valgrind.sh
Fixed a minor error where stderr would be piped to stdout, instead of to
/dev/null in the while loop in `wait_for_pid()`.
Order is significant when redirecting file-descriptors in Bash. In general, the
original line:
while [ $i -gt 0 ] && ps -p $1 2>&1 > /dev/null ; do
Its intention is to redirect stderr and stdout to /dev/null, however, what
really happens is that stderr is first redirected to where stdout is currently
pointing (the tty), and then stdout is redirected to /dev/null. The problem is
that stderr is still pointing at the tty, so the error output will not be
ignored.
The correct way of doing it is by changing the order (although it looks somewhat
backwards), is by doing it in the other order, like so:
while [ "$i" -gt 0 ] && ps -p "$1" > /dev/null 2>&1; do
Then stdout is …
> Pipe stderr to /dev/null along with stdout in wait_for_pid()

- travis-scripts/valgrind.sh
Follow up of the previous PR...
Same fixups, be sure to write stderr to where ( I think it is intended). Be sure to look it over though. Also, why are we appending to /dev/null?
> Fixed issues where stderr are piped to stdout instead of /dev/null

- controls/cf_serverd.cf
An easy way to let people know this configuration option exists,
what the default is and what to do if CFEngine in versions older
than 3.7.0 needs to be supported.
The default was changed to TLS 1.1 in
cfengine/core@959aa35ce6987a96c18bb2da9c61deab624e88c5.
Ticket: ENT-4616
https://github.com/cfengine/core/pull/3936
https://github.com/cfengine/masterfiles/pull/1574
> Add commented out default 'allowtlsversion' value

- lib/paths.cf
Confirmed correct path on rhel 5 and centos 6 and 7.
Ticket: ENT-5060
> ENT-5060: Fixed path for restorecon on redhat systems to /sbin/restorecon

- cfe_internal/enterprise/CFE_hub_specific.cf
- promises.cf.in
The federated reporting in CFEngine Enterprise leverages features that are
unavailable in versions older than 3.12.0. This change prevents the federation
policy from being parsed and generating errors on older versions. 3.10.x was not
targeted for support because Federated Reporting was targeted for supported use
starting in 3.15.0 as 3.10.x ended it's standard support life.
> CFE-3193/master: Excluded Enterprise federation policy parsing on incompatible versions

- cfe_internal/enterprise/CFE_hub_specific.cf
- promises.cf.in
The federated reporting in CFEngine Enterprise leverages features that are
unavailable in versions older than 3.12.0. This change prevents the federation
policy from being parsed and generating errors on older versions (both from
including policy containing features not present, and from specifying a bundle
that is not present when the federation policy is not parsed.
3.10.x was not targeted for support because Federated Reporting was targeted for
supported use starting in 3.15.0 as 3.10.x ended it's standard support life.
> CFE-3193/3.12.x: Excluded Enterprise federation policy parsing on incompatible versions

- cfe_internal/enterprise/CFE_knowledge.cf
In CFEngine Enterprise alerts can be based off of observations in the
infrastructure. When these alerts change state a custom action script can be
triggered in response. This change ensures that the directory where custom
action scripts are stored is available and writeable by the webserver. If this
directory is not present and writeable by the webserver, then Mission Portal
users will not be able to upload custom action scripts.
Ticket: ENT-5070
> ENT-5070/master: Ensured directory for custom action scripts is present

- cfe_internal/enterprise/CFE_knowledge.cf
In CFEngine Enterprise alerts can be based off of observations in the
infrastructure. When these alerts change state a custom action script can be
triggered in response. This change ensures that the directory where custom
action scripts are stored is available and writeable by the webserver. If this
directory is not present and writeable by the webserver, then Mission Portal
users will not be able to upload custom action scripts.
Ticket: ENT-5070
(cherry picked from commit 9ebceafa1a1497ced389d87779c69dd96f97639e)
> ENT-5070/3.12.x: Ensured directory for custom action scripts is present

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/dump.sh
If hub is 3.12* version we assume that inventory is in a materialized view
named m_inventory and dump this data as INSERTs into an __inventory table
as 3.15+ superhub will expect it.
Ticket: ENT-5071
merge with https://github.com/cfengine/system-testing/pull/266
> ENT-5071: Added m_inventory dumping to __inventory for 3.12.x feeders

- cfe_internal/core/watchdog/templates/watchdog.mustache
This change extends the watchdog installed when
cfe_internal_core_watchdog_enabled is defined on AIX hosts.
Previously, the watchdog would check that cf-execd was running. If it was not
running, it would start it. Now in addition to starting cf-execd if it is not
found running other symptoms of pathology are considered.
The following additional conditions are now considered
- More than one cf-execd process running
- `cf-execd: timeout waiting for output from agent` exists in outputs
- This is logged when exec_command as defined in body executor control has not
communicated back to cf-execd in agent_expireafter minutes.
- cf-agent process running for more than 5 minutes
- More than 3 concurrent cf-agent processes
- `cf-check diagnose $(sys.statedir)/*.lmdb` returns non-zero (indicating …
> ENT-4995/3.12.x: Extended watchdog for AIX

- CHANGELOG.md
> ENT-4995/3.12.x: Added missing changelog entry for extended aix watchdog

- controls/cf_serverd.cf
Promises not kept when HA slave hub tries to synchronize configuration from
master.
- Fixed access promise path to `application/config/appsettings.php`, should
come from live config, not share/GUI
- Added missing access promise to share `application/config/config.php`
- Added missing access promsie to share `ldap/config/settings.php`
- Added missing access promsie to share `api/config/config.php`
This is a follow-up to a previous fix that has yet to be released. No changelog
entry needed.
Ticket: ENT-4944
> [3.12.x] Fixed access promises sharing configuration with HA hubs

- controls/cf_serverd.cf
Promises not kept when HA slave hub tries to synchronize configuration from
master.
- Added missing access promsie to share `ldap/config/settings.php`
- Added missing access promsie to share `api/config/config.php`
- Fixed access promise path to `application/config/appsettings.php`, should
come from live config, not share/GUI
- Added missing access promise to share `application/config/config.php`
This is a follow-up to a previous fix that has yet to be released. No changelog
entry needed.
Ticket: ENT-4944
> ENT-4944/master: Fixed access promises sharing configuration with HA hubs

- templates/federated_reporting/10-base_filter.sed
- templates/federated_reporting/config.sh.mustache
This table was dropped in 3.15.0 (and thus on the superhub), see
the commit mentioned below for details.
Ticket: ENT-5052
(backported from commit c60889a4352fb901537ead8e7be665d4eb700e60)
> Do not dump __lastseenhostslogs in FR dumps

- cfe_internal/enterprise/CFE_hub_specific.cf
- templates/federated_reporting/10-base_filter.sed
- templates/federated_reporting/config.sh.mustache
ChangeLog: Changed CFEngine versions to execute policy that clears last seen hosts log. Only 3.12.x, 3.13.x and 3.14.x are allowed.
Removed __lastseenhostslogs from federation config.
Ticket: ENT-5052
Merge together: 
https://github.com/cfengine/mission-portal/pull/931
https://github.com/cfengine/nova/pull/1543
> Changed policies related to __lastseenhostslog

- cfe_internal/update/update_policy.cf
The owners of the '/var/cfengine/state' directory are
root:cfpostgres. So unless we set the group for the pg_ctl
process, it cannot access the '/var/cfengine/state' directory and
thus also '/var/cfengine/state/pg/data'.
> Set group to cfpostgres when running pg_ctl

- cfe_internal/enterprise/federation/federation.cf
Otherwise the promise is not kept and blocks the setup from being
completed even if SELinux is disabled and the 'semanage' package
is not actually needed at all.
Ticket: ENT-5124
> Only check the 'semanage' package if SELinux is enabled (in FR)

- cfe_internal/enterprise/federation/federation.cf
Otherwise the promise is not kept and blocks the setup from being
completed even if SELinux is disabled and the 'semanage' package
is not actually needed at all.
Ticket: ENT-5124
(cherry picked from commit c675089496194e42cbbb78ea3a6f86380007def1)
> [3.12.x] Only check the 'semanage' package if SELinux is enabled (in FR)

- MPF.md
- controls/cf_hub.cf
- controls/def.cf
Variable `control_hub_query_timeout`.
https://github.com/cfengine/core/pull/3964
https://github.com/cfengine/masterfiles/pull/1601
https://github.com/cfengine/nova/pull/1560
> ENT-3153: cf-hub query timeout can now be set from augments

- controls/cf_hub.cf
This change broke upgrade because older hubs won't understand
this new attribute.
> Added minimum version macro to query timeout

- standalone_self_upgrade.cf.in
- Errors:
- *Missing description*
- Source location: ` =in library=../masterfiles/standalone\_self\_upgrade.cf =(66)=
- Triggered by: =../documentation/reference/masterfiles-policy-framework/standalone_self_upgrade.markdown= (20)
- Errors:
- *Missing description*
- Source location: ` =in library=../masterfiles/standalone\_self\_upgrade.cf =(231)=
- Triggered by: =../documentation/reference/masterfiles-policy-framework/standalone_self_upgrade.markdown= (20)
- Errors:
- *Missing description*
- Source location: ` =in library=../masterfiles/standalone\_self\_upgrade.cf =(262)=
- Triggered by: =../documentation/reference/masterfiles-policy-framework/standalone_self_upgrade.markdown= (20)
- Errors:
- *No documentation*
- Source location: ` =in library=../masterfiles/standalone\_self\_upgrade.cf …
> Added missing docs for standalone self upgrade

- templates/federated_reporting/import_file.sh
The pipe to gzip the log was masking the failed exit code from psql.
Ticket: ENT-5040
> Modified import_file.sh to catch errors in psql run

- cfe_internal/enterprise/federation/federation.cf
This change alters the federation policy so that it is no longer able to be run
does not include it's dependencies. It can no longer be run directly as a policy
entry.
This was dropped because it prevents us from rendering the json representation
of the policy in the documentation build.
Ticket: ENT-5124
> ENT-5124/master: Stopped including inputs from federation policy

- cfe_internal/enterprise/federation/federation.cf
(cherry picked from commit 4f262e094f433140a37f8c5ce8a3bc3d5da9a4cb)
> ENT-5168 FR: Don't require SELinux Makefile for running semanage / restorecon (3.15)

- cfe_internal/enterprise/federation/federation.cf
Locking the promise actually running dump.sh means dumps will
only be produced once in a specified interval. Rendering the file
is unrelated to this.
> Use promise locking for running FR dump.sh not rendering it

- cfe_internal/enterprise/federation/federation.cf
Locking the promise actually running dump.sh means dumps will
only be produced once in a specified interval. Rendering the file
is unrelated to this.
(cherry picked from commit 019f362c046ea50d44e868f3466b4090b74cc7c1)
> [3.15.x] Use promise locking for running FR dump.sh not rendering it

- cfe_internal/update/update_policy.cf
This bundle is called only on debian and redhat. Without the deep guard, the
vars promises cause warnings on windows.
```
Administrator@WIN-NTO7O3L97A9 C:\>"\Program Files\Cfengine\bin\cf-agent.exe" -KIf update.cf
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23] …
```
> ENT-5187/3.15.x: Guarded policy to create python symlink to debain and redhat

- cfe_internal/update/update_policy.cf
This bundle is called only on debian and redhat. Without the deep guard, the
vars promises cause warnings on windows.
```
Administrator@WIN-NTO7O3L97A9 C:\>"\Program Files\Cfengine\bin\cf-agent.exe" -KIf update.cf
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23]
warning: Non-absolute path in findfiles(), skipping: C/python
warning: Non-absolute path in findfiles(), skipping: C/python[23] …
```
> ENT-5187/master: Guarded policy to create python symlink to debain and redhat

- modules/packages/apt_get.in
list_installed check the state of a package for package action
hold/install. If the package state is installed, half-installed or
half-configured is considered as "installed". So we can also delete this
packages  with cfengine
Ticket: CFE-3233
> CFE-3233/master: apt_get package module now check package state

- cfe_internal/enterprise/federation/federation.cf
Must be shared by transport_user and clean_when_off bundles.
Without this change target_state to "off" cleanup will not work completely.
Ticket: none
> Move 'selinux_enabled' class to config bundle and namespace scope it

- cfe_internal/enterprise/federation/federation.cf
Must be shared by transport_user and clean_when_off bundles.
Without this change target_state to "off" cleanup will not work completely.
Ticket: none
(cherry picked from commit e854d0964ddabbf3a4e88ea22e817c0084a3e024)
> [3.15.x] fix selinux enabled for FR disabled

- cfe_internal/enterprise/federation/federation.cf
Must be shared by transport_user and clean_when_off bundles.
Without this change target_state to "off" cleanup will not work completely.
Ticket: none
(cherry picked from commit e854d0964ddabbf3a4e88ea22e817c0084a3e024)
> [3.12.x] fix selinux enabled for FR disabled

- controls/cf_serverd.cf
This attribute was added in 63bd3217083f15db22148c5c7d0ae99b6767f998
(with whitespace fix and issue reference in b29783ed33cb58b1ea1e3559451a971354e4c85a).
Then in 57594018fcb6d16501e57142d01443224714b665 the attribute
was restricted to non-Windows hosts only, however this was done
by *moving* the attribute (to use implicit context) rather than
setting the context explicitly.  As a result, the context was incorrectly
changed (implicitly) in 8fba99bc342bb1ca6851a4a62c7303f73810264e
to limit the ipv6 binding to CFEngine 3.7 hosts only.  (!!)
Then the attribute was removed entirely in 9dc25201c8e03caa98a3b5f47fa83cf0442393c7
for no apparent reason, except that it probably looked like it was part of the
same code block, since it was (incorrectly) using the same context line
implicitly.
This …
> Re-fix CFE-528 by adding back bindtointerface attribute

- lib/files.cf
- tests/acceptance/lib/files/manage_variable_values_ini.cf
- tests/acceptance/lib/files/manage_variable_values_ini.cf.finish3.10.x
- tests/acceptance/lib/files/manage_variable_values_ini.cf.start
- tests/acceptance/lib/files/set_variable_values_ini.cf
- tests/acceptance/lib/files/set_variable_values_ini.cf.finish
- tests/acceptance/lib/files/set_variable_values_ini.cf.start
- Added test that leading whitespace on the RHS is not removed
Ticket: CFE-3221
----
#
> CFE-3221/master: Made set_variable_values_ini prefer whitespace around =

- controls/cf_serverd.cf
Trying to bind to "::" (IPV6_ANY) fails on RHEL/CentOS 5.
> Do not bind to "::" on RHEL/CentOS 5 by default

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/main.cf
This change adds inventory of CFEngine Enterprise license utilization based on
knowledge from cf-hub. Because of an issue where cf-hub --show-license returns
non-zero when no license is installed, a return code of 1 is currently
interpreted as a promise kept. After ENT-5279 is resolved, the inventory will
result in a promise not kept if a license is installed, but not valid.
https://github.com/cfengine/nova/pull/1577
https://github.com/cfengine/masterfiles/pull/1649
> ENT-5089/master: Added inventory for CFEngine Enterprise License Utilization

- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/main.cf
This change adds inventory of CFEngine Enterprise license utilization based on
knowledge from cf-hub. It introduces 5 new inventory items on hosts with cf-hub.
New inventory attributes:
- CFEngine Enterprise license file
- CFEngine Enterprise license utilization
- CFEngine Enterprise license expiration date
- CFEngine Enterprise licenses allocated
- CFEngine Enterprise licenses status
Because of an issue where cf-hub --show-license returns non-zero when no license
is installed, a return code of 1 is currently interpreted as a promise kept.
After ENT-5279 is resolved, the inventory will result in a promise not kept if a
license is installed, but not valid.
Ticket: ENT-5089
(cherry picked from commit 040f2794f72e495d54e7a94417631ea5090e65dc)
> ENT-5089/3.15.x: Added inventory for CFEngine Enterprise License information

- cfe_internal/enterprise/CFE_hub_specific.cf
Ticket: ENT-5235
(cherry picked from commit 37a7f3a23a4ce941ac553b551524e5aeca6aee00)
> ENT-5235/3.15.x: Fixed permission flip flop when policy analyzer is enabled

- inventory/any.cf
The commands promise /bin/true is used to delay execution of url_get until the
bundle is explicitly called (so that it doesn't get called and cached during
pre-eval). This change suppresses the useless inform output on versions 3.15.0
and later yet maintains backwards compatibility with 3.12 and 3.10 (where the
inform output can not be suppressed).
Ticket: ENT-5233
> ENT-5233/master: Suppress useless inform output from /bin/true in ec2 inventory

- inventory/any.cf
The commands promise /bin/true is used to delay execution of url_get until the
bundle is explicitly called (so that it doesn't get called and cached during
pre-eval). This change suppresses the useless inform output on versions 3.15.0
and later yet maintains backwards compatibility with 3.12 and 3.10 (where the
inform output can not be suppressed).
Ticket: ENT-5233
(cherry picked from commit e99c234110d14c876231073d88f9568450a4b969)
> ENT-5233/3.15.x: Suppress useless inform output from /bin/true in ec2 inventory

- inventory/any.cf
Changelog: Fixed system UUID inventory for certain VMWare VMs where dmidecode gives UUID bytes in wrong order.
Changelog: Fixed dmi inventory to prefer sysfs to dmidecode for most variables for improved performance and to handle e.g. CoreOS hosts that don't have dmidecode.
Using sysfs has two advantages over using dmidecode:
1. It's faster; no need to start a process (actually two processes,
sh -c 'dmidecode -s ...' and the dmidecode process itself)
for each value we want to collect.
2. It makes it possible to collect DMI info on hosts without
dmidecode, such as CoreOS hosts.
When present (it's not present e.g. on RHEL 5 hosts),
sysfs is at least as reliable as using dmidecode directly.
However, the UUID is returned incorrectly on some VMWare VMs
(those with hardware version 13) - the …
> Change logic for dmi inventory to prefer sysfs, except for UUID

- cfe_internal/enterprise/CFE_hub_specific.cf
This change restricts the workaround for bad return code from cf-hub
--show-license when no license is installed. Now it targets only the affected
versions.
Ticket: ENT-5279
> Removed workaround for ENT-5279

- cfe_internal/enterprise/CFE_hub_specific.cf
This change restricts the workaround for bad return code from cf-hub
--show-license when no license is installed. Now it targets only the affected
versions.
Ticket: ENT-5279
(cherry picked from commit 92a80d18ff584d4e65982dfd106b420af5528c39)
> Removed workaround for ENT-5279 (3.15)

- cfe_internal/enterprise/federation/federation.cf
'pg_ctl --mode smart restart' tries to wait for running
operations to finish and for open connections to be
closed. However, if there are some long-time connections (like
the notify handler added to cf-hub in cfengine/nova#1584), the
restart fails. In such cases we need to do 'pg_ctl --mode fast'
which terminates the remaining open connections gracefully. Doing
'--mode smart' first should provide a good grace period for other
(short-time) connections to finish all the operations.
Also let's use self-documenting long options instead of short
options with comments.
Ticket: ENT-4864
> Fall back to '--mode fast' when restarting PostgreSQL in FR policy

- lib/files.cf
- tests/acceptance/lib/files/manage_variable_values_ini.cf
- tests/acceptance/lib/files/manage_variable_values_ini.cf.finish
- tests/acceptance/lib/files/manage_variable_values_ini.cf.finish3.10.x
- tests/acceptance/lib/files/manage_variable_values_ini.cf.start
- tests/acceptance/lib/files/set_variable_values_ini.cf
- tests/acceptance/lib/files/set_variable_values_ini.cf.finish
- tests/acceptance/lib/files/set_variable_values_ini.cf.start
Updated with the fix added to `set_variable_values_ini` as well.
> CFE-3244: Tolerate whitespace before key in manage_variable_values_ini and set_variable_values_ini 

- inventory/any.cf
If cf-monitord is not running, or is simply unable to resolve these variables,
then they are inventoried as is. Instead of confusing the user with some
unexpanded variable, it's better to not even inventory the unresolved value.
Ticket: ENT-5190
> ENT-5190/master: Prevented inventory of unresolved variables for diskfree and loadavg

- inventory/any.cf
If cf-monitord is not running, or is simply unable to resolve these variables,
then they are inventoried as is. Instead of confusing the user with some
unexpanded variable, it's better to not even inventory the unresolved value.
Ticket: ENT-5190
(cherry picked from commit eb15c94847407cfa00ba00fee595c89e5bcd9770)
> ENT-5190/3.15.x: Prevented inventory of unresolved variables for diskfree and loadavg

- inventory/any.cf
If cf-monitord is not running, or is simply unable to resolve these variables,
then they are inventoried as is. Instead of confusing the user with some
unexpanded variable, it's better to not even inventory the unresolved value.
Ticket: ENT-5190
(cherry picked from commit eb15c94847407cfa00ba00fee595c89e5bcd9770)
> ENT-5190/3.12.x: Prevented inventory of unresolved variables for diskfree and loadavg

- cfe_internal/enterprise/CFE_hub_specific.cf
The changes in cfengine/nova#1584 introduce a better way to
refresh inventory than just doing it periodically from agent
run. However, we still need to refresh the information about the
variables shown on the Inventory page in Mission Portal.
A new PHP CLI task with a more appropriate name
'inventory_variables_refresh' was introduced in
cfengine/mission-portal@d2550582, but we want to keep using the
old task for backwards compatibility.
Ticket: ENT-4864
Changelog: Inventory refresh is no longer part of agent run on the hub
> Simplify the periodic inventory refresh

- controls/cf_serverd.cf
- controls/def.cf
(cherry picked from commit 19bde59d04e034260d9ab2547ecd00ad7328fad0)
> 3.15.x: Added 'data' shortcut to cf-serverd, defaults to sys.workdir/data

- controls/cf_serverd.cf
- controls/def.cf
(cherry picked from commit 19bde59d04e034260d9ab2547ecd00ad7328fad0)
> 3.12.x: Added 'data' shortcut to cf-serverd, defaults to sys.workdir/data

- inventory/any.cf
Changelog: Fixed system UUID inventory for certain VMWare VMs where dmidecode gives UUID bytes in wrong order.
Changelog: Fixed dmi inventory to prefer sysfs to dmidecode for most variables for improved performance and to handle e.g. CoreOS hosts that don't have dmidecode.
Ticket: CFE-3249
Using sysfs has two advantages over using dmidecode:
1. It's faster; no need to start a process (actually two processes,
sh -c 'dmidecode -s ...' and the dmidecode process itself)
for each value we want to collect.
2. It makes it possible to collect DMI info on hosts without
dmidecode, such as CoreOS hosts.
When present (it's not present e.g. on RHEL 5 hosts),
sysfs is at least as reliable as using dmidecode directly.
However, the UUID is returned incorrectly on some VMWare VMs
(those with hardware …
> CFE-3249/3.15.x: Change logic for dmi inventory to prefer sysfs, except for UUID

- cfe_internal/update/update_policy.cf
The bundle should not care about which OS is being used on. The
policy using this bundle should decide. And it already does.
Changelog: /var/cfengine/bin/python symlink creation on SLES was fixed
> Remove bad class guard in the cfe_internal_setup_python_symlink bundle

- cfe_internal/update/update_policy.cf
The bundle should not care about which OS is being used on. The
policy using this bundle should decide. And it already does.
Changelog: /var/cfengine/bin/python symlink creation on SLES was fixed
(cherry picked from commit c39f7a15292ac2e675dbbd56f0620803256c8ee9)
> [3.15.x] Remove bad class guard in the cfe_internal_setup_python_symlink bundle

- cfe_internal/update/update_policy.cf
findfiles() skips relative paths and issues warnings for them.
Ticket: ENT-5187
> Only use absolute paths from $PATH in setup_python_symlink()

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/import.sh
Data import on a superhub manipulates schemas which requires
various locks on the PostgreSQL DB. cf-hub also acquires DB locks
while it's running and so there is a risk of deadlocks. To avoid
them, let's stop the cf-hub process while the import is running
and then start it again.
This should not be a problem because the cf-hub process on a
superhub is only collecting reports from the superhub itself.
https://github.com/cfengine/masterfiles/pull/1686
https://github.com/cfengine/nova/pull/1618
> Stop cf-hub for the time we import data on a superhub

- cfe_internal/enterprise/federation/federation.cf
We have switched to doing inventory refresh as part of the import
process because we needed to do a refresh by hostkey only for the
superhub. But this is now happening implicitly with the new
PostgreSQL notification handling mechanism. The CLI task is only
refreshing the lists of variables to show or not show in Mission
Portal. And that's the same on a superhub, a feeder or any other
hub. So we can now again just rely on the CLI task to be run as
part of an agent run.
> Stop doing inventory refresh as part of FR import process

- lib/paths.cf
The paths observed on an OpenSUSE 15 host varied a bit from the paths defined
for sles|suse, so it got a new section.
> CFE-3283/master: Added paths support for opensuse

- lib/paths.cf
The paths observed on an opensuse 15 host varied a bit from the paths defined
for sles|suse, so it got a new section.
Ticket: CFE-3283
(cherry picked from commit 95da1a7d0845590dbc50a498d245b3cceb113f4a)
> CFE-3283/3.15.x: Added paths support for opensuse

- lib/paths.cf
The paths observed on an opensuse 15 host varied a bit from the paths defined
for sles|suse, so it got a new section.
Ticket: CFE-3283
(cherry picked from commit 95da1a7d0845590dbc50a498d245b3cceb113f4a)
> CFE-3283/3.12.x: Added paths support for opensuse

- cfe_internal/enterprise/federation/federation.cf
- lib/services.cf
This change makes sure that standard_services service_method from the default
namespace is used when trying to manage services. Prior to this change, it was
trying to use standard_services service method from the
cfengine_enterprise_federation namespace.
Ticket: ENT-5406
----
#
> ENT-5406/master: Fixed use of standard_services service_method in federation policy

- lib/services.cf
Prior to this change, if you were in a non-default namespace and specified
default:standard_service as the service method, the bundle would not be found
because it was looking in the callers namespace and not the default namespace.
This change makes sure that any time standard_services service_method from the
default namespace is requested that the standard_services bundle from the
default namespace is used for the implementation.
> ENT-5406/3.15.x: Fixed selection of standard_services when used from non-default namespace

- lib/services.cf
Prior to this change, if you were in a non-default namespace and specified
default:standard_service as the service method, the bundle would not be found
because it was looking in the callers namespace and not the default namespace.
This change makes sure that any time standard_services service_method from the
default namespace is requested that the standard_services bundle from the
default namespace is used for the implementation.
> ENT-5406/3.12.x: Fixed selection of standard_services when used from non-default namespace

- cfe_internal/enterprise/federation/federation.cf
'pg_ctl --mode smart restart' tries to wait for running
operations to finish and for open connections to be
closed. However, if there are some long-time connections (like
the notify handler added to cf-hub in cfengine/nova#1584), the
restart fails. In such cases we need to do 'pg_ctl --mode fast'
which terminates the remaining open connections gracefully. Doing
'--mode smart' first should provide a good grace period for other
(short-time) connections to finish all the operations.
Also let's use self-documenting long options instead of short
options with comments.
Ticket: ENT-4864
(cherry picked from commit 2906524e1e6554ad9ae33415e61ec6f5f24f6896)
> ENT-5420 Fall back to '--mode fast' when restarting PostgreSQL in FR policy

- cfe_internal/enterprise/federation/federation.cf
Using pg_ctl directly on systemd systems causes instability in
services due to systemd reacting to postgresql being restarted.
Ticket: ENT-5420
> ENT-5420/3.15.x Added use of services promise for FR postgresql reconfig in case of systemd

- cfe_internal/enterprise/main.cf
active_hub class is needed to properly manage runalerts.php
processes promise on non-systemd systems so had to swap
order of methods promises.
Ticket: ENT-5432
> ENT-5432: Fixed runalerts processes promise on non-systemd systems (3.12.x)

- cfe_internal/update/update_policy.cf
EL8 stopped shipping python and python[23] by default. This change falls back to
the platform-python if no other version is available so that package modules
written in python can work without requiring external dependencies. If python or
pyton[23] is found in PATH, they are preferred.
Also, this PR includes a change that prevents considering sys.bindir as a location for python symlink target. It's sometimes in PATH, and if it's considered, it can result in a self-referential link.
> CFE-3291/master: Made python symlink fall back to platform-python

- cfe_internal/enterprise/ha/ha.cf
These have to be the same otherwise the perimissions are flipping
(and thus not converging properly) during agent runs.
Changelog: HA setups no longer have flipping permissions on /opt/cfengine/notification_scripts
> Synchronize /opt/cfengine/notification_scripts mog() between HA and non-HA

- cfe_internal/enterprise/main.cf
active_hub class is needed to properly manage runalerts.php
processes promise on non-systemd systems so had to swap
order of methods promises.
Ticket: ENT-5432
(cherry picked from commit 4a490adfc881ad0f88cc1fa0c6840c98ab0f861b)
> ENT-5432: Fixed runalerts processes promise on non-systemd systems

- MPF.md
> CFE-3307/3.15.x: Fixed invalid example setting input_name_patterns via augments

- Makefile.am
- configure.ac
So that re-releases have distinctive file names.
Ticket: ENT-5418
Changelog: Release number was added to MPF tarballs
https://github.com/cfengine/masterfiles/pull/1737
https://github.com/cfengine/buildscripts/pull/726
> Add the release number to the pkg.tar.gz tarball

- Makefile.am
- configure.ac
So that re-releases have distinctive file names.
Ticket: ENT-5429
Changelog: Release number was added to MPF tarballs
(cherry picked from commit 3a711f59be67eccb0de1e2e16d28fa9cab8bff7a)
> [3.15.x] Add the release number to the pkg.tar.gz tarball

- Makefile.am
- configure.ac
So that re-releases have distinctive file names.
Ticket: ENT-5429
Changelog: Release number was added to MPF tarballs
(cherry picked from commit 3a711f59be67eccb0de1e2e16d28fa9cab8bff7a)
> [3.12.x] Add the release number to the pkg.tar.gz tarball

- cfe_internal/update/update_policy.cf
- modules/packages/Makefile.am
Reverts cfengine/masterfiles#1738
Was failing several jenkins CI tests. See https://github.com/cfengine/masterfiles/pull/1738 for details.
> Revert "CFE-3237 Copy modules from masterfiles to workdir on hub during update"

- controls/reports.cf
> ENT-5531/3.12.x: Admitted ::1 as a query source on Enterprise hubs

- cfe_internal/enterprise/federation/federation.cf
We weren't checking to see if an fcontext existed for the
cftransport user before attempting to remove it.
Ticket: ENT-5555
> ENT-5555: Modified cftransport cleanup to avoid errors

- templates/federated_reporting/dump.sh
Previously an empty values column in m_inventory such as when a
host has not reported would cause corrupt SQL to be dumped.
In this case we should simply not include that host in the
output in a similar way that __inventory is built from v_inventory
in latest schema.
Ticket: ENT-5562
> ENT-5562 Changed m_inventory dumping behavior to exclude when values is null (3.12.x)

- templates/federated_reporting/dump.sh
Previously an empty values column in m_inventory such as when a
host has not reported would cause corrupt SQL to be dumped.
In this case we should simply not include that host in the
output in a similar way that __inventory is built from v_inventory
in latest schema.
Ticket: ENT-5562
(cherry picked from commit 65cd6c4de925d18e198eedb92105b6b84ef71627)
> ENT-5562 Changed m_inventory dumping behavior to exclude when values is null (3.15.x)

- modules/packages/zypper.in
process.stdout is of type 'bytes' in Python 3 and needs to be
decoded to get a 'string' object.
Ticket: CFE-3364
Changelog: The zypper module is now fully compatible with Python 3
> Fix two Python 3 incompatibilities in the zypper module

- modules/packages/zypper.in
process.stdout is of type 'bytes' in Python 3 and needs to be
decoded to get a 'string' object.
Ticket: CFE-3364
Changelog: The zypper module is now fully compatible with Python 3
(cherry picked from commit ba32c3e6089ac50d4032832dce034ec8b1db9936)
Conflicts:
modules/packages/zypper.in
> [3.12.x] Fix two Python 3 incompatibilities in the zypper module

- modules/packages/zypper.in
process.stdout is of type 'bytes' in Python 3 and needs to be
decoded to get a 'string' object.
Ticket: CFE-3364
Changelog: The zypper module is now fully compatible with Python 3
(cherry picked from commit ba32c3e6089ac50d4032832dce034ec8b1db9936)
> [3.15.x] Fix two Python 3 incompatibilities in the zypper module

- standalone_self_upgrade.cf.in
With this change, Enterprise hubs can automatically download packages into the
master_software_updates distribution tree and Enterprise agents are able to
upgrade themselves  using the packages from the master_software_updates
distribution tree.
Ticket: ENT-6010
(cherry picked from commit 572434c94e021e561404f09038e4f99d7ab8412d)
> ENT-6010/3.15.x: Aligned unattended self upgrade package map with current state

- standalone_self_upgrade.cf.in
With this change, Enterprise hubs can automatically download packages into the
master_software_updates distribution tree and Enterprise agents are able to
upgrade themselves  using the packages from the master_software_updates
distribution tree.
Ticket: ENT-6010
(cherry picked from commit 572434c94e021e561404f09038e4f99d7ab8412d)
> ENT-6010/3.12.x: Aligned unattended self upgrade package map with current state

- cfe_internal/enterprise/CFE_knowledge.cf
Especially this concerns lmdb files.
system_owned perms body was used previously but for solaris systems the use
of "sys" group seems incorrect so changing to "root" for solaris is the
net result of this change.
Ticket: CFE-3362
merge with:
https://github.com/cfengine/core/pull/4200
> CFE-3362 Changed group for state dir files promise to match defaults per OS 

- .travis.yml
Otherwise they can be out of sync, such as 3.15.x tests/acceptance/testall
wanting cf-secret but 3.15.2 not having it.
Ticket: none
> Changed travis release jobs to use release tag of core matching packages installed

- lib/files.cf
manage_variable_values_ini no longer tries to edit fields in the particular INI
file section. It's unnecessary because there is a promise to delete all entries
from the section before inserting to ensure that all entries are completely
managed. So trying to edit the fields doesn't make sense.
set_variable_values_ini is available for editing specific values in an INI
section.
Ticket: CFE-3372
----
#
> CFE-3372/master: Stopped trying to edit fields in manage_variable_values_ini

- lib/services.cf
Each cfengine run the service was disabled even if the `UnitFileState` was
`disabled`. This change adds support for the disabled service state when
managing systemd services.
Ticket: CFE-3367
Supersedes https://github.com/cfengine/masterfiles/pull/1761 (updated commit message and added ticket reference)
> CFE-3367/master: Stopped disabling disabled systemd unit each run when disabled state requested

- lib/services.cf
Each cfengine run the service was disabled even if the `UnitFileState` was
`disabled`. This change adds support for the disabled service state when
managing systemd services.
Ticket: CFE-3367
(cherry picked from commit 50a58751cf3b98c6ca1da59ff246312f2ad32e95)
----
#
> CFE-3367/3.15.x: Stopped disabling disabled systemd unit each run when disabled state requested

- lib/services.cf
Each cfengine run the service was disabled even if the `UnitFileState` was
`disabled`. This change adds support for the disabled service state when
managing systemd services.
Ticket: CFE-3367
(cherry picked from commit 50a58751cf3b98c6ca1da59ff246312f2ad32e95)
----
#
> CFE-3367/3.12.x: Stopped disabling disabled systemd unit each run when disabled state requested

- lib/files.cf
manage_variable_values_ini no longer tries to edit fields in the particular INI
file section. It's unnecessary because there is a promise to delete all entries
from the section before inserting to ensure that all entries are completely
managed. So trying to edit the fields doesn't make sense.
set_variable_values_ini is available for editing specific values in an INI
section.
Ticket: CFE-3372
(cherry picked from commit 91ae46590c80638574486e2613d81fe1adf83048)
> CFE-3372/3.15.x: Stopped trying to edit fields in manage_variable_values_ini

- lib/files.cf
manage_variable_values_ini no longer tries to edit fields in the particular INI
file section. It's unnecessary because there is a promise to delete all entries
from the section before inserting to ensure that all entries are completely
managed. So trying to edit the fields doesn't make sense.
set_variable_values_ini is available for editing specific values in an INI
section.
Ticket: CFE-3372
(cherry picked from commit 91ae46590c80638574486e2613d81fe1adf83048)
> CFE-3372/3.12.x: Stopped trying to edit fields in manage_variable_values_ini

- controls/def.cf
- controls/update_def.cf.in
- lib/bundles.cf
- lib/cfe_internal_hub.cf
- lib/cfengine_enterprise_hub_ha.cf
- lib/commands.cf
- lib/common.cf
- lib/databases.cf
- lib/edit_xml.cf
- lib/examples.cf
- lib/files.cf
- lib/guest_environments.cf
- lib/monitor.cf
- lib/packages.cf
- lib/paths.cf
- lib/processes.cf
- lib/services.cf
- lib/stdlib.cf
- lib/storage.cf
- lib/users.cf
- lib/vcs.cf
In 3.7.3 def.json started being parsed natively by the agent (CFE-2156). No
currently supported versions require this policy based parsing, so we can redact
it and simplify the policy.
----
#
> Removed policy based parsing of def.json

- lib/bundles.cf
- lib/cfe_internal_hub.cf
- lib/feature.cf
- lib/files.cf
- lib/services.cf
- lib/vcs.cf
> CFE-3378/master: Replaced @ignore with useful doc strings

- lib/services.cf
This change allows the use of servie_policy => "enable" or "enabled" without
actually enabling the service during each execution. "disabled" and "disable" are
handled similarly.
Ticket: ENT-6073
> ENT-6073/master: Aligned systemd services behavior for service_policy => "enable|enabled|disable|disabled"

- lib/services.cf
This change brings understanding of "active" and "inactive" states for services
when managed by systemd. An "active" service state means the service should be
running. An "inactive" service state means the service should not be running.
NOTE: When "active" or "inactive" service states are used, no promises about a
services state on boot are made.
Ticket: ENT-6074
> ENT-6074/master: Added service states "active" and "inactive" for systemd

- lib/services.cf
This change allows the use of servie_policy => "enable" or "enabled" without
actually enabling the service during each execution. "disabled" and "disable" are
handled similarly.
Ticket: ENT-6073
> ENT-6073/12.x: Aligned systemd services behavior for service_policy => "enable|enabled|disable|disabled"

- lib/services.cf
This change brings understanding of "active" and "inactive" states for services
when managed by systemd. An "active" service state means the service should be
running. An "inactive" service state means the service should not be running.
NOTE: When "active" or "inactive" service states are used, no promises about a
services state on boot are made.
Ticket: ENT-6074
(cherry picked from commit 5d1a01ff3293c2c39325720b64ea0c77f9acf503)
> ENT-6074/3.15.x: Added service states "active" and "inactive" for systemd

- lib/services.cf
This change moves the systemd service management promises to their own bundle.
There should be no change in behavior as using standard_services when systemd is
present will still result in the use of the same promises. This change makes it
easier to maintain the policy as it is logically separate and allows explicit
management of systemd services.
> CFE-3381/master: Moved systemd service management to own bundle

- lib/vcs.cf
Not all versions of git support inclusion of untracked files when stashing. This
change probes git to determine if it is capable, only using the option when it's
available.
> CFE-3383/master: Made git_stash only stash untracked files when capable

- lib/packages.cf
- lib/paths.cf
- promises.cf.in
Packages promises only possibly supported back to 3.15.1 due to
need for interpreter attribute on package_module body and no
earlier version available for termux.
Paths added to support the interpreter path for packages.
Also several convenience paths added both for termux and generic unix:
- paths.tmp_path, paths.bin_path, paths.var_path, paths.etc_path
Ticket: CFE-3288
> CFE-3288 Adjusted package_module and paths for termux platform

- lib/files.cf
- tests/acceptance/lib/files/replace_uncommented_substrings.cf
- tests/acceptance/lib/files/replace_uncommented_substrings.cf.after
- tests/acceptance/lib/files/replace_uncommented_substrings.cf.before
This bundle and accompanying body aid in replacing all occurrences of a string
in a file that do not follow a comment character.
Ticket: ENT-6117
> ENT-6117/master: Added replace_uncommented_substrings

- inventory/os.cf
Previously it was based on lsb executable, which is still used as a fallback.
Also added hard coded strings for CentOS 5 and 6.
Debian 7+ and Ubuntu 12+ already have os-release files.
> Inventory OS variable (inventory_os.description in policy) is now based on os-release

- lib/files.cf
- tests/acceptance/lib/files/replace_uncommented_substrings.cf
- tests/acceptance/lib/files/replace_uncommented_substrings.cf.after
- tests/acceptance/lib/files/replace_uncommented_substrings.cf.before
This bundle and accompanying body aid in replacing all occurrences of a string
in a file that do not follow a comment character.
Ticket: ENT-6117
(cherry picked from commit d77f5de5a69f16e3e63feb94eb9447bc4f16a866)
----
#
> ENT-6117/3.15.x: Added replace_uncommented_substrings

- lib/files.cf
Ticket: ENT-6117
(cherry picked from commit 58dcce6babb93e5a8ed1b54248b7bedd2263a37f)
> ENT-6117/3.15.x: Added history for backport of replace_uncommented_substrings

- inventory/os.cf
Previously:
```
RedHatEnterpriseServer 6.7
```
Now:
```
Red Hat Enterprise Linux Server 6.7 (Santiago)
```
This is more user friendly, and matches the format on newer systems with os-release.
> ENT-6124: Cleaned up Mission Portal OS variable (inventory_os.description) on RHEL 5 & 6

- inventory/os.cf
Oopsie in previous commit:
cfengine/masterfiles@8c959b62655c0ae40dcb7b1f675ac64a25c98f36
> ENT-6124: Fixed space before version number for RHEL 5 / 6

- MPF.md
- controls/def.cf
This change sets the delay for updating the inventory of currently installed
packages to 0, effectively disabling any delay. This inventory affects
packagesmatching() as well as inventory collected by an Enterprise hub. Without
this change, changes to software made outside CFEngine may not be realized for
up to 60 minutes.
Ticket: ENT-6154
> Removed delay in refreshing software installed inventory

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
https://github.com/cfengine/nova/pull/1693
https://github.com/cfengine/masterfiles/pull/1807
https://github.com/cfengine/system-testing/pull/353
> ENT-6035 Added duplicate host cleanup during FR import

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
This feature removes duplicate hostkey entries during federated reporting
import based on lastreporttimestamp in __hosts table.
Enable this feature by defining a class in augments (def.json):
```
{
"classes": {
"cfengine_mp_fr_handle_duplicate_hostkeys": ["any::"]
}
}
```
Ticket: ENT-6035
(cherry picked from commit 998c953a584299a9c30634338f38688546e5d0ac)
Conflicts:
cfe_internal/enterprise/federation/federation.cf
https://github.com/cfengine/nova/pull/1701
https://github.com/cfengine/masterfiles/pull/1823
> ENT-6035 Added optional handle duplicates step in federated reporting import (3.15.x)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-6035
https://github.com/cfengine/masterfiles/pull/1828
https://github.com/cfengine/documentation/pull/2361
> Federated Reporting documentation additions and re-organization

- cfe_internal/core/watchdog/README.md
- cfe_internal/core/watchdog/templates/watchdog-windows.ps1.mustache
- cfe_internal/core/watchdog/watchdog.cf
- lib/commands.cf
This change adds an external watchdog for windows. When enabled, any cf-agent
processes found running longer than 5 minutes are terminated.
> ENT-5538/master: Added watchdog for Windows

- cfe_internal/core/watchdog/README.md
- cfe_internal/core/watchdog/templates/watchdog-windows.ps1.mustache
- cfe_internal/core/watchdog/watchdog.cf
- lib/commands.cf
This change adds an external watchdog for windows. When enabled, any cf-agent
processes found running longer than 5 minutes are terminated.
Ticket: ENT-5538
(cherry picked from commit 6bdc03df8d3c1a74c72442800e3f6ff79f86cca2)
> ENT-5538/3.15.x: Added watchdog for Windows

- controls/cf_serverd.cf
This is an attempt to clarify a common misconception that `bundle server
access_rules` is somehow special. There is no need to modify this file in the
MPF in order to define custom access promises. Instead, simply define a custom
server bundle, e.g. bundle server my_access_rules.
Merge with: https://github.com/cfengine/documentation/pull/2369
> CFE-3427/master: Changed bundle server access_rules to mpf_default_access_rules

- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
(cherry picked from commit c4ced8e23bc55722b252def2233bbdd6d1df60e0)
----
#
> ENT-6082 disable *-list-cached tests on deb7 and solaris11 - 3.15.x

- inventory/any.cf
This packages promise was in place to provide package inventory used by
packagematching() and packageupdatesmatching() out of the box. This is not
needed since ENT-5480 introduced the zypper package module.
Ticket: ENT-6375
> ENT-6375/master: Removed unnecessary packages promises

- inventory/any.cf
This packages promise was in place to provide package inventory used by
packagematching() and packageupdatesmatching() out of the box. This is not
needed since ENT-5480 introduced the zypper package module.
Ticket: ENT-6375
(cherry picked from commit 1c2427d0c9fdbd9bc136dea1442f5f25eb3d2eed)
> ENT-6375/3.15.x: Removed unnecessary packages promise on SuSE

- lib/files.cf
- tests/acceptance/README.org
- tests/acceptance/lib/files/edit_line_converge.cf
- tests/acceptance/lib/files/edit_line_converge.cf.expected
- tests/acceptance/lib/files/edit_line_converge.cf.start
- tests/acceptance/lib/files/edit_line_converge_prepend.cf
- tests/acceptance/lib/files/edit_line_converge_prepend.cf.expected
- tests/acceptance/lib/files/edit_line_converge_prepend.cf.start
Superceeds https://github.com/cfengine/masterfiles/pull/1853
> bundle edit_line converge fixups, converge_prepend addition/master

- cfe_internal/enterprise/CFE_hub_specific.cf
- Fix interpretation of cf-hub --show-license 
- Move --show-license option to promiser so that it's more clear in reporting
> ENT-6473/master: Fixed interpretation of cf-hub --show-license from REPAIRED to KEPT

- controls/def.cf
- lib/packages.cf
This change moves the default settings from bundle def to bundle
package_module_knowledge, enabling standalone policy to include the stdlib and
make packages promises implemented by package modules. Before this change,
errors would be emitted because query_installed_ifelapsed and
query_updates_ifelapsed were not set.
This change does not inhibit the ability to configure these settings via
augments (def.json) by setting package_module_query_installed_ifelapsed and
package_module_query_updates_ifelapsed.
> CFE-3504/master: Enabled packages promises using package_module without bundle def

- controls/def.cf
- lib/packages.cf
Ticket: CFE-3504
This change moves the default settings from bundle def to bundle
package_module_knowledge, enabling standalone policy to include the stdlib and
make packages promises implemented by package modules. Before this change,
errors would be emitted because query_installed_ifelapsed and
query_updates_ifelapsed were not set.
This change does not inhibit the ability to configure these settings via
augments (def.json) by setting package_module_query_installed_ifelapsed and
package_module_query_updates_ifelapsed.
(cherry picked from commit 8877a248be1c7d91ecf3a91b6ce20d8f8c1ca7db)
> CFE-3504/3.15.x: Enabled packages promises using package_module without bundle def

- lib/services.cf
If a service is not enabled in rc.conf on FreeBSD, trying to get the status
always results in something like:
```
Cannot 'status' ntpd. Set ntpd_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
0
```
As the exit code is zero, cf-agent would try to stop this service. Using
onestatus always returns the wanted exit code, regardless if the service is
enabled or not.
```
ntpd is not running.
1
```
----
Thanks @systemheld. I cleaned up trailing whitespace and added some metadata to link things around with our ticketing system. This PR supersedes your original one https://github.com/cfengine/masterfiles/pull/1876
Thanks @skreuzer for the quick review.
> CFE-3515/master: service status on FreeBSD now uses onestatus

- lib/services.cf
If a service is not enabled in rc.conf on FreeBSD, trying to get the status
always results in something like:
```
Cannot 'status' ntpd. Set ntpd_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
0
```
As the exit code is zero, cf-agent would try to stop this service. Using
onestatus always returns the wanted exit code, regardless if the service is
enabled or not.
```
ntpd is not running.
1
```
Ticket: CFE-3515
(cherry picked from commit d137fd9cea14ba361ee9530796f0a70d015f55f2)
> CFE-3515/3.15.x: service status on FreeBSD now uses onestatus

- lib/services.cf
If a service is not enabled in rc.conf on FreeBSD, trying to get the status
always results in something like:
```
Cannot 'status' ntpd. Set ntpd_enable to YES in /etc/rc.conf or use 'onestatus' instead of 'status'.
0
```
As the exit code is zero, cf-agent would try to stop this service. Using
onestatus always returns the wanted exit code, regardless if the service is
enabled or not.
```
ntpd is not running.
1
```
Ticket: CFE-3515
(cherry picked from commit d137fd9cea14ba361ee9530796f0a70d015f55f2)
> CFE-3515/3.12.x: service status on FreeBSD now uses onestatus

- MPF.md
- controls/def.cf
- promises.cf.in
With this change, you can specify a list of bundles to run before autorun
polices. This can be useful if you want to have autorun policies execute based
on soft classes that are not persistent. E.g. prod hosts.
Ticket: ENT-6603
> ENT-6603/master: Added ability to specify a list of bundles to run before autorun (for classification)

- MPF.md
- controls/def.cf
- promises.cf.in
With this change, you can specify a list of bundles to run before autorun
polices. This can be useful if you want to have autorun policies execute based
on soft classes that are not persistent. E.g. prod hosts.
Ticket: ENT-6603
(cherry picked from commit 06dbe78951fbb0e8ed7a4d2df90a655b82e19de5)
> ENT-6603/3.15.x: Added ability to specify a list of bundles to run before autorun (for classification)

- cfe_internal/enterprise/CFE_hub_specific.cf
The inform output generated by these commands is distracting for new users.
Already the promises were set to be contained in a silent body, this just
extends that silence to suppress from inform. The command results are still
interpreted the same, and if one of these commands is not kept, they will still
emit an error.
Ticket: ENT-6563
-----
Before:
```
[root@hub ~]# cf-agent -KI
info: Executing 'no timeout' ... '/var/cfengine/httpd/php/bin/php /var/cfengine/httpd/htdocs/index.php cli_tasks process_api_events'
info: Completed execution of '/var/cfengine/httpd/php/bin/php /var/cfengine/httpd/htdocs/index.php cli_tasks process_api_events'
info: Executing 'no timeout' ... '/var/cfengine/httpd/php/bin/php /var/cfengine/httpd/htdocs/index.php cli_tasks …
```
> ENT-6563/master: Suppressed inform output from Enterprise Hub database maintenance operations

- cfe_internal/update/update_policy.cf
- inventory/redhat.cf
- modules/packages/apt_get.in
- modules/packages/yum.in
- modules/packages/zypper.in
Package modules that rely on python can be run with either python2 or python3.
We maintain a symlink pointing to a version of python found on the system that
is appropriate. In order to avoid confusion, since CFEngine's bin directory is
commonly found in $PATH we have renamed the symlink so that the symlink is not
used when a user types python on the console.
> CFE-3512/master: Renamed python symlink to cfengine-selected-python

- cfe_internal/enterprise/CFE_hub_specific.cf
The inform output generated by these commands is distracting for new users.
Already the promises were set to be contained in a silent body, this just
extends that silence to suppress from inform. The command results are still
interpreted the same, and if one of these commands is not kept, they will still
emit an error.
Ticket: ENT-6563
>  ENT-6563/3.15.x: Suppressed inform output from Enterprise Hub database maintenance operations

- inventory/os.cf
Tested on:
OS strings are as shown ^
> ENT-6536: Shortened Inventory OS attribute to be more readable

- LICENSE
- m4/cf3_platforms.m4
- modules/packages/zypper.in
- tests/acceptance/testall
There were a few stale copyright headers from 2017 that weren't updated with the
change from 2020 -> 2021.
Ticket: None
> Updated stale copyright headers to 2021

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
This change makes def.control_server_allowusers the singular variable used to
control the list of users allowed to execute policy via cf-runagent. It
supersedes def.control_server_allowusers_policy_server and
def.control_server_allowusers_non_policy_server which are still used to set the
default value for def.control_server_allowusers. If
vars.control_server_allowusers is defined via Augments (def.json) that setting
will be used for both policy servers and non policy servers.
If further segmentation is desired, multiple augments can be used.
Ticket: CFE-3544
> CFE-3544/master: Added new interface for controlling users allowed to initiate cf-agent via cf-runagent

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
This change adds a new augmentable variable to control hosts that should be
allowed to initiate agent runs via cf-runagent.
Ticket: ENT-6673
> ENT-6673/master: Added vars.mpf_admit_cf_runagent_shell to control admission for cf-runagent requests

- lib/autorun.cf
Without the `services_autorun::` guard you get
```shell
% cf-promises -p json autorun.cf
error: Unresolved variable '@(services_autorun.found_inputs)' in input list, cannot parse
...
```
> Protect inputs for autorun.cf so cf-promises can parse it

- controls/def.cf
Ticket: CFE-3546
(cherry picked from commit 5558f11b4bfa043cbd03541abfca4e7d2fb26c43)
> CFE-3546/3.15.x: Fixed ability to define users authorized for using cf-runagent on policy servers

- controls/def.cf
Ticket: CFE-3546
(cherry picked from commit 5558f11b4bfa043cbd03541abfca4e7d2fb26c43)
> CFE-3546/3.12.x: Fixed ability to define users authorized for using cf-runagent on policy servers

- controls/def.cf
> ENT-6666/master: Added inventory of users and hosts allowed to use cf-runagent

- cfe_internal/core/limit_robot_agents.cf
cf-execd forks when spawning cf-agent and when handling other
requests.
Ticket: ENT-6182
https://github.com/cfengine/core/pull/4453
https://github.com/cfengine/masterfiles/pull/1891
> Do not limit the number of cf-execd processes

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/799
Ticket: ENT-6783
> ENT-6783/master: Disabled TLSv1 by default for Mission Portal's web server

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/800
Ticket: ENT-6783
(cherry picked from commit 00396d3ebcbfccb1ff1eb995c4562f70232bd67f)
> ENT-6783/3.15.x: Disabled TLSv1 by default for Mission Portal's web server

- cfe_internal/enterprise/templates/httpd.conf.mustache
Merge together: https://github.com/cfengine/buildscripts/pull/801
Ticket: ENT-6783
(cherry picked from commit 00396d3ebcbfccb1ff1eb995c4562f70232bd67f)
> ENT-6783/3.12.x: Disabled TLSv1 by default for Mission Portal's web server

- modules/packages/apk
package names can include dashes(-) so sed expression was incorrect.
Ticket: CFE-3585
> CFE-3585 Fixed alpine apk packages module to parse names properly

- MPF.md
Ticket: CFE-3598
(cherry picked from commit b009a5f360d3dd97314223a7d5c9d35b783bc67d)
> CFE-3598/3.15.x: Added example illustrating definition of services_autorun class

- cfe_internal/update/update_policy.cf
Prior to this change, if a file were changed into a directory or vice versa,
policy update would fail, e.g.
error: The object '/var/cfengine/inputs/testme' is not a directory. Cannot make a new directory without deleting it.
error: Errors encountered when actuating files promise '/var/cfengine/inputs'
error: Method 'cfe_internal_update_policy_cpv' failed in some repairs
This change results in files or directories being moved out of the way so that
policy update will complete and properly transform files into directory or vice
versa.
info: Moved obstructing file/link '/var/cfengine/inputs/testme' to '/var/cfengine/inputs/testme.cf-moved' to make directories for '/var/cfengine/inputs/testme/dummy'
info: Created parent directory for '/var/cfengine/inputs/testme'
info: Copied file …
> CFE-2984/master: Update policy now moves obstructions

- modules/packages/msiexec.bat
File is always \cfengine_package_install.log
See ENT-6824 TODO to save based on basename of msi file.
Ticket: ENT-6220
> ENT-6220 Added verbose logfile for msiexec package module file installs

- controls/def.cf
- modules/packages/msiexec.bat
Logs are now placed in a unique "basename"_install.log file in\cfengine_package_logs.
That dir is also added in controls/def.cf to cfe_log_dirs to be
pruned by cfe_internal/core/log_rotation.cf policy every $(def.mpf_log_dir_retention) days.
Ticket: ENT-6824
> ENT-6824 Changed msiexec package module install logs to be unique for each msi file

- cfe_internal/update/update_policy.cf
- controls/cf_serverd.cf
This change makes sure that hosts update their local cache of CMDB data from an
Enterprise hub.
Ticket: ENT-6788
> ENT-6788/master: Made Enterprise CMDB data update after policy update

- configure.ac
- modules/packages/Makefile.am
apk, snap and msiexec-list.vbs were missing from modules/packages/Makefile.am
and so would be missing from packaging.
Ticket: ENT-6814
> ENT-6814: Added missing packages modules scripts in makefile

- modules/packages/msiexec.bat
File is always \cfengine_package_install.log
See ENT-6824 TODO to save based on basename of msi file.
Ticket: ENT-6220
(cherry picked from commit 6edaa3ea8dfb5291a16ede70657c521174ebaf93)
> ENT-6220 Added verbose logfile for msiexec package module file installs (3.12.x)

- modules/packages/msiexec.bat
File is always \cfengine_package_install.log
See ENT-6824 TODO to save based on basename of msi file.
Ticket: ENT-6220
(cherry picked from commit 6edaa3ea8dfb5291a16ede70657c521174ebaf93)
> ENT-6220 Added verbose logfile for msiexec package module file installs (3.15.x)

- controls/def.cf
- modules/packages/msiexec.bat
Logs are now placed in a unique "basename"_install.log file in\cfengine_package_logs.
That dir is also added in controls/def.cf to cfe_log_dirs to be
pruned by cfe_internal/core/log_rotation.cf policy every $(def.mpf_log_dir_retention) days.
Ticket: ENT-6824
(cherry picked from commit c77d06a348a90034d5aeb21dde655f807ec69659)
> ENT-6824 Changed msiexec package module install logs to be unique for each msi file (3.12.x)

- controls/def.cf
- modules/packages/msiexec.bat
Logs are now placed in a unique "basename"_install.log file in\cfengine_package_logs.
That dir is also added in controls/def.cf to cfe_log_dirs to be
pruned by cfe_internal/core/log_rotation.cf policy every $(def.mpf_log_dir_retention) days.
Ticket: ENT-6824
(cherry picked from commit c77d06a348a90034d5aeb21dde655f807ec69659)
> ENT-6824 Changed msiexec package module install logs to be unique for each msi file (3.15.x)

- configure.ac
- modules/packages/Makefile.am
apk, snap and msiexec-list.vbs were missing from modules/packages/Makefile.am
and so would be missing from packaging.
Ticket: ENT-6814
> ENT-6814 Added missing packages modules scripts in makefile (3.12.x)

- configure.ac
- modules/packages/Makefile.am
apk, snap and msiexec-list.vbs were missing from modules/packages/Makefile.am
and so would be missing from packaging.
Ticket: ENT-6814
> ENT-6814 Added missing packages modules scripts in makefile (3.15.x)

- lib/packages.cf
- modules/packages/apk
- promises.cf.in
Note that repo-install and file-install API methods do not support multiple
packages. This should not affect most usage of this module.
(cherry picked from commit f9d3f2a)
(cherry picked from commit a209797)
Includes fix for CFE-3585
(cherry picked from commit 3cce164)
Ticket: CFE-3451
> CFE-3451 Added apk package module support for alpinelinux (3.12.x)

- modules/packages/Makefile.am
Commit a139ce9 improperly added reference
to msiexec-list.vbs.
Ticket: CFE-3607
> CFE-3607 Adjust modules/packages/Makefile.am for lack of msiexec packages module (3.12.x)

- lib/packages.cf
- modules/packages/apk
- promises.cf.in
Original ticket to add apk module was CFE-3451 so including that as changelog entry.
CFE-3585 refined the package module
CFE-3607 bootstrap was broken due to modules/packages/Makefile.am changes which
referred to apk module when the apk module was not back ported.
Ticket: CFE-3451
> CFE-3607 Added apk package module support for alpinelinux (3.15.x)

- cfe_internal/update/windows_unattended_upgrade.cf
- standalone_self_upgrade.cf.in
In versions before 3.12.7 sys.cf_version_release is not present so default to 1.
This will handle most cases well and enable upgrades from <3.12.7 to >=3.12.7.
Ticket: ENT-6219
(cherry picked from commit 2edd756bc6a9ba769e1912bdb56cc0339a7c9b9c)
> ENT-6219 Added default cf_version_release of 1 when sys var missing

- lib/paths.cf
yum has become an integral part of aix and it is  commonly used, as ibm has put  ehanced effort into the aix toolbox for linux applications (gnu freeware rpm packages for aix). so yum should be considered in cfengine as a valid package manager. this PR is part of ongoing efforts to make cfengine more aix aware.
> CFE-3615: add /usr/bin/yum to paths.cf for aix

- lib/paths.cf
(cherry picked from commit a139956ca32f378976f0a8ef538d96a1740f1a4e)
> CFE-3615: add /usr/bin/yum to paths.cf for aix (3.15.x)

- lib/common.cf
This PR supersedes #1932
This change removes body classes u_kept_successful_command from the standard
library. Note an identically named classes body still exists inside the
update.cf policy entry. This body that is being removed was only loaded by the
promises.cf entry and is believed to be some left over artifact from a time when
promises.cf loaded the update.cf policy. Another classes body,
kept_successful_command still remains in the standard library, and should be
used instead.
Ticket: CFE-3617
Changelog: Removed stale unused copy of u_kept_successful_command body. If you receive an error about undefined body, alter your policy to use kept_successful_command instead.
> CFE-3617: Removed stale unused copy of u_kept_successful_command body (master)

- inventory/linux.cf
Low entropy can cause all kinds of issues, including hanging agents. Tracking
this over time can be useful for understanding and avoiding issues.
Ticket: ENT-6495
> ENT-6495/master: Added measurement of entropy available on linux systems

- promises.cf.in
inventory/aix.cf is never loaded because !aix is missing in the other_unix_os class
> CFE-3614: Fixed loading of platform specific inventory on AIX (master)

- MPF.md
- cfe_internal/update/update_policy.cf
- controls/cf_serverd.cf
- controls/def.cf
merge together: https://github.com/cfengine/buildscripts/pull/814 https://github.com/cfengine/core/pull/4577
The plugins directory has seemingly gone unused since it was introduced to the
MPF in 2013, this change simply removes this directory from being considered for
sharing and updating.
Ticket: CFE-3618
> CFE-3618: Removed unused plugins directory (master)

- promises.cf.in
AIX was not considered in the expression that determined which set of
inventory policy files to load resulting in only generic inventory
policy being loaded. This change corrects the expression so that AIX
loads the AIX specific inventory.
Ticket: CFE-3614
(cherry picked from commit ea1b1e5a9ade42d8b49885307bd23330f22f23c6)
> CFE-3614: Fixed loading of platform specific inventory on AIX (3.15)

- controls/cf_agent.cf
- controls/def.cf
This pr builds on top of one from @vpodzime https://github.com/cfengine/masterfiles/pull/1960
> CFE-3622: Avoid setting files_single_copy in an erroneous way (master)

- promises.cf.in
AIX was not considered in the expression that determined which set of
inventory policy files to load resulting in only generic inventory
policy being loaded. This change corrects the expression so that AIX
loads the AIX specific inventory.
Ticket: CFE-3614
(cherry picked from commit ea1b1e5a9ade42d8b49885307bd23330f22f23c6)
> CFE-3614: Fixed loading of platform specific inventory on AIX (3.12)

- .travis.yml
Prior to this change, Travis was fetching packages from builds.cfengine.com
which was previously co-located with cfengine.com. However, this broke when we
deployed the new cfengine.com website into different infrastructure. Instead of
restoring functionality to builds.cfengine.com, I thought it better to use our
shiny new tooling and switched to cf-remote. The Travis build host is Ubuntu
16.04, so, in order to facilitate the change I had to install python 3.6 from
the deadsnakes personal package archive as it is required for both pip3 and cf-remote.
Ticket: ENT-6992
(cherry picked from commit 1f841f0f1bf894f64c2042ca4b8910f9ea470d83)
> ENT-6992: Switched Travis to using cf-remote for getting master packages (3.15)

- .travis.yml
- controls/def.cf
Prior to this change, Travis was fetching packages from builds.cfengine.com
which was previously co-located with cfengine.com. However, this broke when we
deployed the new cfengine.com website into different infrastructure. Instead of
restoring functionality to builds.cfengine.com, I thought it better to use our
shiny new tooling and switched to cf-remote. The Travis build host is Ubuntu
16.04, so, in order to facilitate the change I had to install python 3.6 from
the deadsnakes personal package archive as it is required for both pip3 and cf-remote.
Ticket: ENT-6992
(cherry picked from commit 1f841f0f1bf894f64c2042ca4b8910f9ea470d83)
> ENT-6992: Switched Travis to using cf-remote for getting master packages (3.12)

- cfe_internal/enterprise/CFE_hub_specific.cf
Prior to php version 8, libphp included the major version of php in it's file
name. Beginning with php 8, the major version of php was dropped from the
libraries file name. This change begins to prefer libphp.so if it's present.
> ENT-7039: Fixed detection of libphp apache module location (master)

- MPF.md
Currently (as of 3.17.0), cf-promises is not capable of detecting syntax errors
in policy files that are dynamically loaded by other dynamically loaded policy
files. This limitation can be worked around by leveraging loading from other
places in policy and this change references those other configuration options.
Ticket: CFE-1962
> CFE-1962: Added note about limitations of syntax checking dynamically loaded policy files (master)

- lib/cfe_internal_hub.cf
Issue was that these tasks broke no-noise deployment test, if it was
started at Hr00.
> ENT-7056 nightly maintenance tasks were silenced

- travis-scripts/before_install.sh
No real change in this repo, just updating the comment.
Kept lcov dependency because:
* Not a quick thing to remove, shows up in many places
* Probably necessary if we add some code coverage again
> ENT-7051: Removed codecov.io

- inventory/os.cf
Adopt use of sys.os_name_human & sys.os_version_major for OS inventory
attribute
Ticket: CFE-3569
Signed-off-by: larsewi <lars.erik.wik@northern.tech>
> CFE-3569: Adopt use of sys.os_name_human & sys.os_version_major

- controls/reports.cf
This change clarifies the description of how the report_data_select bodies work.
The previous verbiage indicated that the bodies were used by the hub instead of
by the host being collected from.
Ticket: ENT-7087
(cherry picked from commit 4f4bae3fdb442cf7462a4c5f2bb63960542753c5)
> ENT-7087: Clarified inline docs for authorizing data for reporting (3.12)

- MPF.md
- cfe_internal/recommendations.cf
- cfe_internal/update/update_policy.cf
- controls/def.cf
- controls/update_def.cf.in
Prior to this change, the default behavior of the MPF was to only ensure that
files in masterfiles were up to date with the files in inputs. Files in inputs
that did not exist in masterfiles were left undisturbed. To enable sync
behavior (a common user expectation) you had to explicitly define
'cfengine_internal_purge_policies'. Now, if you wish to return to the previous
default behavior, define the class 'cfengine_internal_purge_policies_disabled'.
Ticket: CFE-3662
> CFE-3662: Changed default behavior of policy update to keep inputs in sync with masterfiles (master)

- inventory/os.cf
Changed sys.os_name_major -> sys.os_version_major
One is correct, the other one isn't.
> Fixed new OS inventory string based on new vars

- cfe_internal/enterprise/federation/federation.cf
Due to master being more restrictive in referencing classes we
needed to add the default: namespace prefix to the classname
in order to properly reference this class which turns on or off
duplicate hostkey handling in federated reporting import processing.
Ticket: ENT-7094
> ENT-7094 Fixed cfengine_mp_fr_handle_duplicate_hostkeys class usage in policy

- cfe_internal/update/update_policy.cf
This change implements generating/updating host specific data files on a
CFEngine Enterprise hub. A data file for each host having host specific data
created, updated or deleted since the last check is create or re-generated.
Note: This does not consider any kind of host removal. This policy is only
concerned with keeping data for existing hosts up to date and available for
download by remote agents.
Ticket: ENT-6786
> ENT-6786: Added generation of host specific data files from the CFEngine Enterprise CMDB (master)

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/update/update_policy.cf
Trying to enforce user root ownership on $(sys.statedir) and
$(sys.workdir)/modules was causing many errors to be reported:
error: Could not look up name 'root'. (LookupAccountName)
Ticket: ENT-4628
> ENT-4628 Guard again enforcing root ownership for CFEngine files on Windows

- cfe_internal/enterprise/CFE_knowledge.cf
- cfe_internal/update/update_policy.cf
Trying to enforce user root ownership on $(sys.statedir) and
$(sys.workdir)/modules was causing many errors to be reported:
error: Could not look up name 'root'. (LookupAccountName)
Ticket: ENT-4628
(cherry picked from commit d6ae4b084610bfd91ac3c20b5fd5b0cf987a0e19)
> ENT-4628 Guard again enforcing root ownership for CFEngine files on Windows (3.15.x)

- controls/def.cf
- inventory/README.md
- inventory/any.cf
This policy was originally introduced for CFEngine 3.6.0 as an easy way to
provide information from an external system via a data interface. Since then new
functionality has been introduced, especially Augments and the new host specific
data which implement this from core.
It's always been disabled by default, and now there has been a report of it
causing errors, so I think it's perfectly safe to remove.
> CFE-3712: Removed stale CMDB inventory policy (master)

- controls/def.cf
- inventory/README.md
- inventory/any.cf
This policy was originally introduced for CFEngine 3.6.0 as an easy way to
provide information from an external system via a data interface. Since then new
functionality has been introduced, especially Augments and the new host specific
data which implement this from core.
It's always been disabled by default, and now there has been a report of it
causing errors, so I think it's perfectly safe to remove.
Ticket: CFE-3712
(cherry picked from commit fcfa962666a86bee9df96795e0f33e1e17f5ffc5)
> CFE-3712: Removed stale CMDB inventory policy (3.18)

- lib/packages.cf
A bug in ifelse in pre 3.15.3 binaries coupled with
a bug regarding evaluation of $(this.promiser) in doubly-referenced
values (https://tracker.mender.io/browse/ENT-7358) causes
package_module_query_installed_ifelapsed and
package_module_query_updates_ifelapsed to be undefined
(-678 value) when newer policy is run with pre
3.15.3 binaries.
Ticket: ENT-7356
> ENT-7356 Fixed package module augments settings usage for pre 3.15.3 binaries

- lib/packages.cf
A bug in ifelse in pre 3.15.3 binaries coupled with
a bug regarding evaluation of $(this.promiser) in doubly-referenced
values (https://tracker.mender.io/browse/ENT-7358) causes
package_module_query_installed_ifelapsed and
package_module_query_updates_ifelapsed to be undefined
(-678 value) when newer policy is run with pre
3.15.3 binaries.
Ticket: ENT-7356
(cherry picked from commit 5060b929960a3a5bec2045721bc1176e340887f4)
> ENT-7356 Fixed package module augments settings usage for pre 3.15.3 binaries (3.15.x)

- lib/packages.cf
A bug in ifelse in pre 3.15.3 binaries coupled with
a bug regarding evaluation of $(this.promiser) in doubly-referenced
values (https://tracker.mender.io/browse/ENT-7358) causes
package_module_query_installed_ifelapsed and
package_module_query_updates_ifelapsed to be undefined
(-678 value) when newer policy is run with pre
3.15.3 binaries.
Ticket: ENT-7356
(cherry picked from commit 5060b929960a3a5bec2045721bc1176e340887f4)
> ENT-7356 Fixed package module augments settings usage for pre 3.15.3 binaries (3.18.x)

- standalone_self_upgrade.cf.in
This was missed in ENT-5752 work and will cause problems in self-upgrade.
Ticket: CFE-3703
> CFE-3703 Add interpreter attribute to standalone self upgrade package_module bodies

- modules/packages/vendored/zypper.mustache
Same change as included in masterfiles commit
ef02bcb265b7a285b280efddb87413f68372ba2e
which covered apt_get and yum but missed zypper.
Ticket: ENT-7442
> ENT-7442 Fixup zypper package module script to work properly with interpreter attribute

- standalone_self_upgrade.cf.in
This was missed in ENT-5752 work and will cause problems in self-upgrade.
Ticket: CFE-3703
(cherry picked from commit 8d35228286c868c780a2daacfafbf0bce45a214c)
> CFE-3703: Add interpreter attribute to standalone self upgrade package_module bodies (3.15)

- standalone_self_upgrade.cf.in
This was missed in ENT-5752 work and will cause problems in self-upgrade.
Ticket: CFE-3703
(cherry picked from commit 8d35228286c868c780a2daacfafbf0bce45a214c)
> CFE-3703: Add interpreter attribute to standalone self upgrade package_module bodies (3.18)

- MPF.md
- lib/autorun.cf
- promises.cf.in
The class services_autorun continues to enable both automatic inclusion of .cf
files in services/autorun and the running of bundles tagged with autorun.
This change adds the classes services_autorun_inputs and
services_autorun_bundles for independently enabling addition of .cf files in
services/autorun and automatic execution of bundles tagged with autorun
respectively.
Ticket: CFE-3715
> CFE-3715: Added separate classes for controlling autorun inputs and bundles (master)

- modules/packages/vendored/zypper.mustache
Same change as included in masterfiles commit
ef02bcb265b7a285b280efddb87413f68372ba2e
which covered apt_get and yum but missed zypper.
Ticket: ENT-7442
(cherry picked from commit 684ec90b028360a63726ce5fce37629682668c00)
> ENT-7442: Fixup zypper package module script to work properly with interpreter attribute (3.18)

- modules/packages/vendored/zypper.mustache
Same change as included in masterfiles commit
ef02bcb265b7a285b280efddb87413f68372ba2e
which covered apt_get and yum but missed zypper.
Ticket: ENT-7442
(cherry picked from commit 684ec90b028360a63726ce5fce37629682668c00)
> ENT-7442: Fixup zypper package module script to work properly with interpreter attribute (3.15)

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7233
(cherry picked from commit 15add8d20540bfb092088fa0f8197455c31977ad)
> ENT-7233: Added cleanup of database and status semaphore when federation target_state is off (3.18)

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-7233
(cherry picked from commit 15add8d20540bfb092088fa0f8197455c31977ad)
> ENT-7233: Added cleanup of database and status semaphore when federation target_state is off (3.15)

- lib/cfe_internal_hub.cf
Issue was that these tasks broke no-noise deployment test, if it was
started at Hr00.
(cherry picked from commit 478db759fe80e3c6cab9a883e3c41cf5e5b5759a)
> ENT-7056: nightly maintenance tasks were silenced (3.15)
