- cfe_internal/host_info_report.cf
regression introduced in commit a970facfddde1ea62b268fc0d94da4d834e0d781 for Redmine#4507
> fix variable reference

- cfe_internal/CFE_hub_specific.cf
- cfe_internal/cfengine_processes.cf
- controls/cf_execd.cf
- update.cf
- update/update_bins.cf
- update/update_policy.cf
- update/update_processes.cf
(cherry picked from commit 9206e119e1af8a702495204b64d55729f3c0d054)
Conflicts:
controls/cf_execd.cf Classe guards needed to be adjusted
> Make workdir relocatable.

- lib/3.5/paths.cf
- lib/3.6/paths.cf
- lib/3.7/paths.cf
Fix path[ping] for FreeBSD 9.3, 10.x, 11.x
> Change: Update paths.cf

- lib/3.6/files.cf
- lib/3.7/files.cf
Updating a self referential "see also" section to point to something useful.
Supersedes https://github.com/cfengine/masterfiles/pull/402
> Improve inline documentation

- lib/3.5/paths.cf
- lib/3.6/paths.cf
- lib/3.7/paths.cf
> Add path to dtrace, zfs and zpool on FreeBSD

- controls/3.8/cf_agent.cf
- controls/3.8/cf_execd.cf
- controls/3.8/cf_hub.cf
- controls/3.8/cf_monitord.cf
- controls/3.8/cf_runagent.cf
- controls/3.8/cf_serverd.cf
- controls/3.8/def.cf
- controls/3.8/reports.cf
- controls/3.8/update_def.cf
- lib/3.8/autorun.cf
- lib/3.8/bundles.cf
- lib/3.8/cfe_internal.cf
- lib/3.8/cfengine_enterprise_hub_ha.cf
- lib/3.8/commands.cf
- lib/3.8/common.cf
- lib/3.8/databases.cf
- lib/3.8/edit_xml.cf
- lib/3.8/examples.cf
- lib/3.8/feature.cf
- lib/3.8/files.cf
- lib/3.8/guest_environments.cf
- lib/3.8/monitor.cf
- lib/3.8/packages.cf
- lib/3.8/paths.cf
- lib/3.8/processes.cf
- lib/3.8/services.cf
- lib/3.8/stdlib.cf
- lib/3.8/storage.cf
- lib/3.8/users.cf
- lib/3.8/vcs.cf
I mindlessly copied the 3.7 directories.  Some evolution shall surely
be needed, but tests fail on master without these (symlinks won't do)
so let's start with this.
> redmine7237: Add 3.8 sub-directories for controls/ and lib/.

- update/update_bins.cf
Same as #470 but for the 3.6.x branch.
> add missing commas to update_bins.cf (2)

- modules/packages/apt_get
Some apt_get modifications supporting Ubuntu 10 and Debain 6.
> Add support for Debian 6 and Ubuntu 10

- CHANGELOG.md
- controls/3.7/update_def.cf
- controls/3.8/update_def.cf
Ref: https://dev.cfengine.com/issues/7315
> Add: Support for class augmentation from def.json in update policy

- lib/3.7/autorun.cf
- lib/3.8/autorun.cf
- promises.cf
Ref: https://dev.cfengine.com/issues/7317
> Change: autorun related verbose_mode class guards to DEBUG

- CHANGELOG.md
Ref: https://dev.cfengine.com/issues/7022
Ref: https://github.com/cfengine/masterfiles/pull/429
> Add: Changelog entry for removing _not_repaired classes

- CHANGELOG.md
- lib/3.7/stdlib.cf
- lib/3.8/stdlib.cf
This work is to facilitate more modular loading of inputs in the future.
> Change: Switch stdlib inputs to classic arrays

- example_def.json
Comma missing in the example def.json
> MIssing comma

- example_def.json
477b7d2f4e19888ac5ae13ec8486489075ac5039)
Conflicts:
example_def.json
> MIssing comma (cherry picked from commit

- cfe_internal/core/log_rotation.cf
- Handles for better identification of promises in logs and reporting
- DEBUG reports for improved policy debugging
> Change: Improve in-line docs for internal log maintenance

- lib/3.7/cfe_internal.cf
> Add: Debug reports in cfe_internal_cleanup_agent_reports

- lib/3.7/cfe_internal.cf
- lib/3.8/cfe_internal.cf
- Fix missing report files in 3.8 tree
- Add DEBUG reports
- Change multiple function calls to define variables
Ref: https://dev.cfengine.com/issues/7527
> Change: Improve efficiency and debug reports

- lib/3.6/paths.cf
- lib/paths.cf
Superceedes https://github.com/cfengine/masterfiles/pull/562
> Add: Path to svcprop in stdlib

- inventory/any.cf
(cherry picked from commit 4ee12bb4901db1d474e53f9f8dfc170adbf0170e)
> Fix: Syntax errors

- cfe_internal/update/update_bins.cf
(cherry picked from commit a540d28035e4554fbb16cf0bea0769b56956ff99)
> Add: Debug report when trigger_upgrade is set

- cfe_internal/update/update_bins.cf
- cfe_internal/update/update_policy.cf
- update.cf
Ref: https://dev.cfengine.com/issues/7662
> Change: Seperate binary details from policy update

- lib/services.cf
Ref: https://dev.cfengine.com/issues/7663
> Change: Remove horizontal rule potentially causing issues

- lib/common.cf
Ref: https://dev.cfengine.com/issues/7418
> Add: New `results` classes body [Redmine#7481]

- lib/3.7/paths.cf
(cherry picked from commit a887965d07152cc5cd0489685bc978eb42011397)
> Add path to virtualenv

- lib/3.7/paths.cf
(cherry picked from commit 0851e6abfa883da6c5b27b1da46fb90bab9ab98f)
> Add groupdel, groupmod, userdel and usermod to debian paths

- controls/def.cf
(cherry picked from commit e2e5967d18b2ee5831cf4e5f82e95218ec9f208b)
> fix controls/def.cf to look for def.json in the right location

- controls/def.cf
(cherry picked from commit 7838d8081756b54c1f3c4e8564a86cbc9b6f1ab5)
> Add missing override_classes to control/def.cf

- lib/common.cf
These changes should make the stdlib docs for the results class render
more beautifully.
> Change: Cleanup formatting

- lib/common.cf
> lib/common.cf: clarify "results" body

- cfe_internal/update/update_bins.cf
Changelog: Add guard for binary upgrade during bootstrap Redmine #7861
(cherry picked from commit bc380647f91aa392a23b936f40d06af74abfadfd)
> Add guard for binary upgrade during bootstrap

- cfe_internal/update/cfe_internal_update_from_repository.cf
(cherry picked from commit cb3bc6f2ca61539bcbbe4ac8068aa321325a6d3b)
> Add: Debug reports for internal masterfiles deploy mechanism

- lib/bundles.cf
@nickanderson pretty simple and clean, saves a step over `cmerge()`.
> lib/bundles.cf: add collect bundle similar to cmerge

- lib/services.cf
> Change: Suppress standard services noise on SUSE

- controls/def.cf
> Add log rotation for $(sys.workdir)/state/promise.log file

- promises.cf
> Fix: Only parse services/autorun/*.cf when services_autorun is defined

- templates/host_info_report.mustache
> Add: Memory information to host info report

- lib/reports.cf
- lib/stdlib.cf
> Add: printfile bodies to stdlib

- tests/acceptance/17_packages/12_new/timed/packagesmatching.cf
Add acceptance test to make sure packagesmatching() and
packageupdatesmatching() is working with new package promise.
> CFE-2246 packagesmatching() and packageupdatesmatching() fix.

- controls/def.cf
> Fix: Work around impaired class definition from augments

- controls/def.cf
- inventory/any.cf
@nickanderson as discussed in #531 and IRC
> inventory: rework LLDP inventory to produce a "info" data container through -f json

- lib/files.cf
> Add: edit_line contains_literal_block to stdlib

- lib/files.cf
(cherry picked from commit c8e09851f9407f420b5beded442d486d5ad34e25)
> Add: edit_line contains_literal_string to stdlib

- lib/3.6/services.cf
- lib/3.7/services.cf
Ref: Jira #CFE-2806
(cherry picked from commit bfe0b4d2f067a92da92e8db8635381d52dc3e62f)
> Fix: CFEngine choking on standard services

- cfe_internal/enterprise/templates/httpd.conf.mustache
(cherry picked from commit 3995802ce19af49e5b1eb6d36405ceffc21e430d)
> Change: Apache config for 2.4

- cfe_internal/CFE_cfengine.cf
- cfe_internal/enterprise/mission_portal.cf
(cherry picked from commit 42f929dc8558accdf97d137e34a0b882f942b900)
> Add: Additional policy debug reports

- cfe_internal/enterprise/templates/httpd.conf.mustache
This helps to prevent potential man in the middle attacks.
> Change: Enable strict transport security

- cfe_internal/enterprise/templates/httpd.conf.mustache
This change reduces the information shared by apache.
> Change: Reduce Enteprise webserver info

- cfe_internal/enterprise/templates/httpd.conf.mustache
This improves our out of the box security profile.
> Change: Disable http TRACE method

- cfe_internal/enterprise/templates/httpd.conf.mustache
> Change: Disable RC4 Cipher for ssl in Mission Portal

- controls/def.cf
> Add: Enterprise appliaction log dir to rotation

- cfe_internal/enterprise/templates/httpd.conf.mustache
Wiht some suggestions from https://cipherli.st/
> Change: Additional apache hardening

- inventory/any.cf
> Add: Inventory for system product name (model)

- lib/bundles.cf
> Change: cronjob bundle tolerates different spacing

- cfe_internal/enterprise/mission_portal.cf
> Add: Ensure appropriate permissions for SSL files

- .travis.yml
- README.md
- cfe_internal/enterprise/ha/ha.cf
- cfe_internal/enterprise/main.cf
- controls/3.6/cf_hub.cf
- controls/3.6/cf_serverd.cf
- controls/3.6/update_def.cf.in
- controls/cf_hub.cf
- controls/update_def.cf.in
- lib/3.6/cfe_internal_hub.cf
- lib/3.6/common.cf
- lib/3.6/files.cf
- lib/3.6/packages.cf
- lib/3.6/processes.cf
- lib/cfe_internal_hub.cf
- lib/cfengine_enterprise_hub_ha.cf
- lib/processes.cf
- modules/packages/apt_get
- modules/packages/pkg
- tests/acceptance/17_packages/resources/build-deb-repo
- tests/acceptance/17_packages/resources/build-rpm-repo
- tests/acceptance/17_packages/resources/putinrepo.sh
- tests/acceptance/lib/files/set_config_values.cf.finish
- tests/acceptance/lib/files/set_config_values.cf.start
- tests/acceptance/lib/files/set_line_based_config_values.cf.finish
- tests/acceptance/lib/files/set_line_based_config_values.cf.start
- tests/acceptance/lib/reports/cat.cf.sub
- tests/acceptance/lib/reports/head.cf.sub
- tests/style_check.sh
- tests/unit/test_package_module_pkg
This is just an intro, adding a very simple and very quick trailing-whitespace check for pull requests.
The purpose is to extend this with lint, coding style checks and nice checks for the C code if we port it to Core.
> Travis whitespace check

- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test.cf
- tests/acceptance/17_packages/10_new/unsafe/the_great_package_test_generator.py
> Test: Add same class guard for CentOS 5 as for Redhat 5.

- cfe_internal/enterprise/templates/httpd.conf.mustache
> Change: Session Cookies use HTTPOnly and secure attribtues

- cfe_internal/enterprise/CFE_knowledge.cf
Cleaning up left over remnants.
Jira #ENT-2812
> Remove: Reference to deprecated sql_lite

- LICENSE
- README.md
- cfe_internal/CFE_cfengine.cf
- cfe_internal/core/log_rotation.cf
- cfe_internal/core/main.cf
- cfe_internal/core/watchdog/watchdog.cf
- controls/3.6/update_def.cf.in
- controls/update_def.cf.in
- lib/3.6/common.cf
- lib/3.6/files.cf
- lib/3.6/packages.cf
- lib/3.6/vcs.cf
- lib/README.md
- lib/common.cf
- lib/files.cf
- lib/packages.cf
- lib/vcs.cf
- modules/packages/nimclient
- promises.cf.in
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix some typos

- controls/cf_agent.cf
- controls/def.cf
- example_def.json
> CFE-2461: Allow specifying agent maxconnections via def.json

- lib/common.cf
> Add: Classes body tailored for use with diff

- tests/unit/test_package_module_apt_get
> Use correct protocol format in apt_get unit test.

- lib/stdlib.cf
- lib/templates/junit.mustache
- lib/templates/tap.mustache
- lib/testing.cf
Needs review and testing @nickanderson
> Add jUnit bundles and include them in stdlib.cf

- MPF.md
- controls/def.cf
- example_def.json
- promises.cf.in
- tests/acceptance/00_basics/def.json/control_common_bundlesequence_end.cf
- tests/acceptance/00_basics/def.json/control_common_bundlesequence_end.cf.json
> CFE-2460: Add ability to append to bundlesequnece with def.json

- CHANGELOG.md
> 3.10.0 changelog

- MPF.md
- cfe_internal/update/update_policy.cf
> Add class to enable post transfer verrification during policy updates

- lib/files.cf
> CFE-2519: Fix ability to select INI region with metachars

- modules/packages/apt_get
- tests/unit/test_package_module_apt_get
> Fix apt_get package module incorrectly using interactive mode.

- modules/packages/apt_get
1. First try python3, then python
2. Search for the python binaries in PATH
> Small fixes to the previous commit.

- cfe_internal/enterprise/CFE_knowledge.cf
Manually backport missing body.
> Fix missing body

- promises.cf.in
> CFE-2602: Update stubbed example package module controls

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
- example_def.json
- tests/acceptance/00_basics/def.json/server_dirs.cf
- tests/acceptance/00_basics/def.json/server_dirs.cf.json
> CFE-2582: Backport templates shortcut

- lib/bundles.cf
The prunetree bundle allws you to delete files and directories up to a
sepcified depth older than a specified number of days.
> CFE-2608: Add prunetree bundle to stdlib

- lib/bundles.cf
The prunetree bundle allws you to delete files and directories up to a
sepcified depth older than a specified number of days.
(cherry picked from commit 8e4b1f83fa7a723b04bc7ec89cf5cbf0f17ccc39)
> CFE-2608 Backport prunetree bundle to stdlib

- lib/event.cf
@nickanderson similar to `testing.cf`
@yann-soubeyrand maybe this is useful regarding your questions about event handling...
> CFE-2609: lib/event.cf: add event handling framework

- MPF.md
- controls/cf_agent.cf
- controls/def.cf
- example_def.json
> CFE-2458: Allow specification of files_single_copy via augments

- MPF.md
- controls/cf_agent.cf
- controls/def.cf
- example_def.json
(cherry picked from commit ad5cb863d33b39c8055416368de5743752436b5f)
> CFE-2458: Backport allowing specification of files_single_copy via augments

- lib/paths.cf
> ENT-3121: Add oslevel to well known paths.

- cfe_internal/enterprise/mission_portal.cf
> ENT-3134: Fix command to restart apache on config change

- inventory/aix.cf
- promises.cf.in
> ENT-3117: Add aix OOTB oslevel inventory

- inventory/aix.cf
- promises.cf.in
(cherry picked from commit db1356e821ab60cf2deebd9cbaff59386bcb1327)
> ENT-3117 Backport: Add aix OOTB oslevel inventory

- MPF.md
- controls/def.cf
- controls/reports.cf
> CFE-2505: Enable specification of monitoring_include via augments

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
> CFE-2623: Configure call_collect_interval from augments (enable_client_initiated_reporting)

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
* CFE-2623: Configure call_collect_interval from augments (enable_client_initiated_reporting)
* Update MPF.md
(cherry picked from commit 43fb3eb39d26695e959c4cbeea9ece0d2f8bc011)
> CFE-2623: Configure call_collect_interval from augments (enable_client_initiated_reporting) (#905)

- MPF.md
- controls/cf_hub.cf
- controls/def.cf
> CFE-2622: Configure exclude_hosts in body hub control via augments

- lib/packages.cf
- modules/packages/Makefile.am
- modules/packages/zypper
- promises.cf.in
> CFE-2533: Add zypper package module

- cfe_internal/update/update_bins.cf
- configure.ac
- standalone_self_upgrade.cf.in
- update.cf
Also removes symlinking into /usr/local/sbin (CFE-2636)
> ENT-3155: Refactor self upgrade

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
> CFE-2660: server control maxconnections can be configured via augments

- MPF.md
- cfe_internal/core/main.cf
> CFE-2326: Add bundle to track component variables to restart when necessary

- lib/cfe_internal_hub.cf
> Change: Do not silence Enterprise hub maintenance

- tests/unit/test_package_module_apt_get
I completely reworked the commit - now it's just plain file copy, no fancy cherry-picking or merge conflict resolution
> ENT-3283: copy test_package_module_apt_get file from master 

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-3313: Ensure that Mission Portal can export pdf and csv reports

- .travis.yml
(cherry picked from commit 42e6ee87304484494439ad5554d3daee09bcd561)
> Update Travis to test with 3.7.6

- standalone_self_upgrade.cf.in
Backport fixes for standalone self upgrade
(cherry picked from commit e2087643817be11268c8bafb4524776717d14f2d)
> ENT-3395 ENT-3368 ENT-3377

- cfe_internal/enterprise/templates/httpd.conf.mustache
To mirror similar commit in buildscripts repo:
https://github.com/cfengine/buildscripts/pull/259/commits/a3082ad0f5ec9d262a57218c6f104581e4603ed6
> ENT-3265: Add apache config to new LDAP API

- cfe_internal/enterprise/CFE_hub_specific.cf
(cherry picked from commit b2f2fffecc7630c0497d2dc0b1712ca53d1d1202)
> Remove outdated comments

- lib/files.cf
> CFE-2714: fixed an error in the file_make_mustache_*, incorrect variable name used

- inventory/any.cf
> CFE-2097: Policy Release Id is now inventoried by default

- inventory/any.cf
(cherry picked from commit fc37d6cc1e0eb9e1a3093cb86ef75a6a41e186cd)
> Fix call to readjson for 3.7.x compat

- tests/acceptance/lib/files/insert_ini_section.cf
- tests/acceptance/lib/files/insert_ini_section.cf.finish
(cherry picked from commit eb732f0fe19606d9d86b4cf1a73641b039bc1153)
> CFE-2721: Add test for insert_ini_section and mutliple sections

- tests/acceptance/00_basics/def.json/control_common_bundlesequence_end.cf
@nickanderson This was causing the test to fail on my VM, dunno why.
> Explicitly set perms for augments bundle test

- MPF.md
- templates/cfengine_watchdog.mustache
> ENT-3251: Add external watchdog support for stuck cf-execd

- lib/packages.cf
https://tracker.mender.io/browse/CFE-2759
> CFE-2759 : prevent yum from locking when possible

- lib/packages.cf
(cherry picked from commit 5e7ae0bb7a2c76f51ae70177c79d0d7076f05bb5)
> CFE-2759 : prevent yum from locking in package_methods when possible

- CHANGELOG.md
Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>
> Add changelog entry for 3.10.3

- CHANGELOG.md
Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>
> Add 3.7.7 changelog

- CHANGELOG.md
Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>
> Update changelog for 3.7.7-build2

- cfe_internal/update/update_policy.cf
Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>
> Synthax fix

- MPF.md
- standalone_self_upgrade.cf.in
- update.cf
> ENT-3592: Avoid executing self upgrade policy unnecessarily and improve docs

- CHANGELOG.md
and 3.11.0 which should be on master
> Changelog for 3.12.0 beta

- lib/paths.cf
> ENT-3823 Remove more smartquotes

- lib/packages.cf
- modules/packages/Makefile.am
- modules/packages/slackpkg
(cherry picked from commit e52051858165549645557c3cd1ba1ea98c594698)
> CFE-2827 Slackware package module support (3.12)

- CHANGELOG.md
I doubt there will be more changes for 3.12.0, so we can as well merge this
> Add changelog for 3.12.0

- cfe_internal/update/update_processes.cf
(cherry picked from commit c3d5423ed7bce4103e3f35429b74a7b6b252bde7)
> ENT-3883 Fix variables so that cfengine services start on windows

- lib/3.7/bundles.cf
(cherry picked from commit 98ea7d877a0dbc385d4725337d0005fd851f0dc1)
> ENT-3946 Only consider files that exist for rotation

- standalone_self_upgrade.cf.in
This change resolves an issue where the package fails to finish upgrading on
AIX.
> ENT-3972 Fix unattended self upgrade on AIX

- README.md
(cherry picked from commit 5545970a7dd8e3188595e2731b8666ee86dd06bf)
> Update buildbadges for 3.12.x

- .travis.yml
- cfe_internal/CFE_cfengine.cf
- cfe_internal/recommendations.cf
(cherry picked from commit 061d2332feb81ee8328f565836a6a1fb64f0369a)
> Fix backwards compatibility with 3.7.x

- modules/packages/zypper
Reported by LGTM:
https://lgtm.com/rules/6780086/
> Removed unused variable in zypper module

- cfe_internal/CFE_cfengine.cf
Ticket: CFE-2920
Signed-off-by: Ole Herman Schumacher Elgesem <ole.elgesem@cfengine.com>
(cherry picked from commit f4520c4cc1123b42b841aee649d959e9443d7672)
> Made internal bundle common to avoid errors in daemons

- MPF.md
(cherry picked from commit 94f8b0c85a65f1befc6933bd3d2ecabbbbaa74a8)
> CFE-2926 Fix name of tunable to control max client side report history

- inventory/any.cf
- promises.cf.in
merge with https://github.com/cfengine/nova/pull/1279
> CFE-2924 Add inventory of AWS EC2 linux instances

- inventory/any.cf
- promises.cf.in
EC2 classification contributed by Mike Weilgart and Aleksey Tsalolikhin
(cherry picked from commit 9d74221e1d0ed5c38e44484e71b40e1efe5d0d2d)
> CFE-2924 Add inventory of AWS EC2 linux instances 3.12.x

- .travis.yml
this should fix issue Ole saw in https://travis-ci.org/cfengine/masterfiles/jobs/446356223#L1013
> use nightly builds from master branch

- MPF.md
- controls/cf_execd.cf
- controls/def.cf
(cherry picked from commit d5486360933249c1741983e720f24868e72dee9c)
> ENT-4308 Configure agent_expireafter from augments

- tests/acceptance/testall
https://github.com/cfengine/core/pull/3425
https://github.com/cfengine/masterfiles/pull/1274
https://github.com/cfengine/buildscripts/pull/492
https://github.com/cfengine/enterprise/pull/470
> WIP ENT-4064: Backport cf-check diagnose to 3.12.1

- cfe_internal/enterprise/templates/runalerts.php.mustache
- cfe_internal/enterprise/templates/runalerts.sh.mustache
Change sql argument to all, to run all type of alerts.
> ENT-4266 Fix runalerts script

- cfe_internal/core/limit_robot_agents.cf
- update.cf
> CFE-2963 & CFE-2964 & ENT-4352

- lib/cfe_internal_hub.cf
https://github.com/cfengine/nova/pull/1329
> ENT-4331 Handle cleanup of status table after it's been renamed

- lib/paths.cf
Supersedes https://github.com/cfengine/masterfiles/pull/1323
> CFE-3013: Add paths for timedatectl and journalctl (master)

- lib/paths.cf
(cherry picked from commit b395592623d6233a7e3d4b29a91d535e0d2eab1e)
> CFE-3013 Add path support for timedatectl and journalctl (3.10.x)

- lib/paths.cf
> Add path support for setfacl

- lib/paths.cf
(cherry picked from commit eab0a8c40896d8ac8566a7b9185e867d7e5ef7fa)
> Add path support for setfacl (3.12.x)

- lib/paths.cf
(cherry picked from commit eab0a8c40896d8ac8566a7b9185e867d7e5ef7fa)
> Add path support for setfacl (3.10.x)

- tests/acceptance/17_packages/01_init/unsafe/timed/001-prepare-repositories.cf
https://github.com/cfengine/buildscripts/pull/462
https://github.com/cfengine/nova/pull/1371
> ENT-4041 ubuntu-18

- lib/packages-ENT-3719.cf
- lib/packages.cf
- modules/packages/Makefile.am
- modules/packages/WiRunSQL.vbs
- modules/packages/msiexec.bat
- promises.cf.in
- tests/unit/mock_msi.bat
- tests/unit/test_package_module_msiexec.bat
https://github.com/cfengine/core/pull/3608
> 3.12.x-ENT-3719-msiexec-package-module PR

- lib/cfe_internal_hub.cf
Ticket: ENT-4588
(cherry picked from commit 9bc9f276684ffd036ad21aa48e37a1bfa2c78b8e)
> Fixed maintenance policy for promise log cleanup to respect history_length_days (3.12.x)

- lib/cfe_internal_hub.cf
Ticket: ENT-4588
(cherry picked from commit 9bc9f276684ffd036ad21aa48e37a1bfa2c78b8e)
> Fixed maintenance policy for promise log cleanup to respect history_length_days (3.10.x)

- cfe_internal/enterprise/federation/federation.cf
See: https://github.com/cfengine/system-testing/pull/213
> Policy fixes for federated reporting i2/i3

- cfe_internal/enterprise/federation/federation.cf
Support for pulling SQL dumps from the feeders by superhub. Just like we, CFE people, like it.
> Pull support for Federated Reporting dump transport

- 3rdparty/core/determine-version.py
That's where the most up to date version is.
Ticket: CFE-3071
> Update determine_version.py from the core repo

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/psql_wrapper.sh
merge with 
https://github.com/cfengine/nova/pull/1421
> ENT-4611: when superhub enabled ensure partition schema is correct

- 3rdparty/core/determine-version.py
It has a couple improvements over the old version originally
copied over here.
Ticket: CFE-3039
> Sync determine_version.py from core

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/psql_wrapper.sh
merge with https://github.com/cfengine/nova/pull/1437
> ENT-4612: policy calls ensure_feeders(ARRAY) to ensure feeders in database

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/dump.sh
- templates/federated_reporting/filter.sed.mustache
- templates/federated_reporting/import.sh
- templates/federated_reporting/import_file.sh
includes ENT-4611/ENT-4612 for now, will clean that up.
merge with https://github.com/cfengine/nova/pull/1441
> ENT-4613 Import database dumps into feeder schema

- cfe_internal/enterprise/federation/federation.cf
Tested, works:
```
olehermanse@OHMBP-4153 Downloads $ cf-remote -H $CLOUD_USER$SUPERHUB,$CLOUD_USER$FEEDER sudo "cat /opt/cfengine/federation/cfapache/setup-status.json"
ubuntu@34.244.107.217: 'cat /opt/cfengine/federation/cfapache/setup-status.json' -> '{'
ubuntu@34.244.107.217:                                                              '  "configured": true,'
ubuntu@34.244.107.217:                                                              '  "hostkey": "SHA=613e1e33664439e732fdd7cc0949980c9afa9998da8c8d12039335cae62b4c9e",'
ubuntu@34.244.107.217:                                                              '  "role": "superhub",'
ubuntu@34.244.107.217:                                                              '  "transport_ssh_public_key": "ssh-ed25519 …
```
> ENT-4750: Removed space in setup-status fingerprint

- cfe_internal/enterprise/federation/federation.cf
> ENT-4749: Run pg_ctl as cfpostgres user and not root

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/filter.sed.mustache
merge with https://github.com/cfengine/nova/pull/1443
> ENT-4526: handle __promiselog* tables in import

- templates/federated_reporting/import_file.sh
> ENT-4745: cleaned up output of import_file.sh

- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/dump.sh
- templates/federated_reporting/filter.sed.mustache
- templates/federated_reporting/import_file.sh
merge with https://github.com/cfengine/nova/pull/1446
> ENT-4772: Use db table whitelist and create schema on superhub

- templates/federated_reporting/import.sh
- templates/federated_reporting/import_file.sh
ENT-4742: fix deadlock issues with parallel import
The data import is what takes a long time and what we need to
parallelize, setting up the schemas and attaching them can be
done serially before/after the data import.
Merge together: https://github.com/cfengine/nova/pull/1450
> Separate data import from schema setup and attaching in FR

- cfe_internal/enterprise/federation/federation.cf
> Fix missing default namespace prefix for if_elapsed body.

- templates/federated_reporting/import.sh
- templates/federated_reporting/import_file.sh
Two small fixes for potentially big issues with the ETL process in FR.
> FR blocker fixes

- templates/federated_reporting/dump.sh
- templates/federated_reporting/filter.sed.mustache
Redirect all questions to @vpodzime.
> ENT-4817: Fixed errors discovered when testing with 3.12 FR Feeder

- cfe_internal/enterprise/federation/federation.cf
- tests/unit/Makefile.am
- tests/unit/test_federation_policy
Also added a unit test at tests/unit/test_federation_policy
> ENT-4874: Changed FR policy to honor target_state properly

- templates/federated_reporting/50-merge_inserts.awk
See individual commits for details.
> Fixes and improvements for the merge_inserts.awk filter

- MPF.md
- cfe_internal/update/update_processes.cf
Reverts cfengine/masterfiles#1511
> Revert "Fixed agent disabling on systemd systems"

- MPF.md
- cfe_internal/core/main.cf
- cfe_internal/update/update_processes.cf
- travis-scripts/valgrind.sh
> CFE-2429/master: Manage cfengine components via policy on systemd managed hosts

- lib/services.cf
Superceeds: https://github.com/cfengine/masterfiles/pull/1330
> CFE-3167/master: Fixed detections of service state on FreeBSD

- modules/packages/pkgsrc
Ticket: CFE-3153
(cherry picked from commit f80b035c2716bae909572346d6b960c4b1630312)
> CFE-3153/3.12.x: Fixed pkgsrc in case where multiple Prefix paths are returned for pkg_install

- modules/packages/pkgsrc
Ticket: CFE-3153
(cherry picked from commit f80b035c2716bae909572346d6b960c4b1630312)
> CFE-3153 Fixed pkgsrc in case where multiple Prefix paths are returned for pkg_install

- lib/paths.cf
> lib/paths.cf: Add usermod path for redhat systems

- MPF.md
- cfe_internal/core/main.cf
- cfe_internal/update/update_processes.cf
- travis-scripts/valgrind.sh
Reverts cfengine/masterfiles#1522
> Revert "CFE-2429/master: Manage cfengine components via policy on systemd managed hosts"

- lib/paths.cf
(cherry picked from commit ffd47c6ac1580af42575a90cdc3cf1e16282431a)
> 3.12.x: lib/paths.cf: Add usermod path for redhat systems

- MPF.md
(cherry picked from commit 1b3a3cfe04c253ad7bdb70ac882dca4934f71306)
> Fixed grammar

- lib/packages.cf
- modules/packages/snap
This PR supersedes the [original pr](https://github.com/cfengine/masterfiles/pull/1033) that was abandoned in order to address PR review.
> CFE-2811/master: Added snap package module

- travis-scripts/valgrind.sh
Follow-up from:
https://github.com/cfengine/masterfiles/pull/1564
I'll add this function to the GODS repo, after merge:
https://gitlab.com/Northern.tech/OpenSource/gods
> Travis: Wait for PIDs to terminate by polling ps

- cfe_internal/core/watchdog/README.md
> ENT-4995/3.12.x: Added documentation for watchdog

- cfe_internal/enterprise/federation/federation.cf
- lib/paths.cf
Ticket: ENT-5077
merge with https://github.com/cfengine/system-testing/pull/270
> ENT-5077: Switched to using semanage to handle cftransport user on selinux systems

- cfe_internal/core/watchdog/README.md
> Added documentation for watchdog

- cfe_internal/enterprise/federation/federation.cf
Ticket: ENT-5051
merge together
https://github.com/cfengine/nova/pull/1555
https://github.com/cfengine/masterfiles/pull/1572
https://github.com/cfengine/system-testing/pull/272
> ENT-5051: Added policy to revert changes when FR is turned off (removed/uninstalled)

- cfe_internal/CFE_cfengine.cf
> CFE-3220/master: Added brief descriptions to bodies and bundles in cfe_internal/CFE_cfengine.cf

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-5138
https://github.com/cfengine/buildscripts/pull/645
https://github.com/cfengine/mission-portal/pull/963
https://github.com/cfengine/nova/pull/1561
> Added username from apache request notes to access log

- standalone_self_upgrade.cf.in
> ENT-5152/master: Enabled SUSE 12 for self upgrade

- standalone_self_upgrade.cf.in
Ticket: ENT-5152
(cherry picked from commit 5170cfe3f2b9205f5515a8573047b10cd3090ab3)
> ENT-5152/3.12.x: Enabled SUSE 12 for self upgrade

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-5138
(cherry picked from commit b886d7979ca2f6cdd88918369514416207188b3a)
https://github.com/cfengine/mission-portal/pull/970
https://github.com/cfengine/nova/pull/1569
https://github.com/cfengine/buildscripts/pull/648
> Added username from apache request notes to access log (3.12.x)

- cfe_internal/update/update_policy.cf
> Fixed typo in docs for cf_promises_validated class

- controls/cf_serverd.cf
- controls/def.cf
> Added 'data' shortcut to cf-serverd, defaults to sys.workdir/data

- cfe_internal/update/update_policy.cf
- lib/packages.cf
- promises.cf.in
> CFE-3284/master: Added zypper as default package manager for opensuse

- cfe_internal/update/update_policy.cf
- lib/packages.cf
- promises.cf.in
Ticket: CFE-3284
(cherry picked from commit e4c4bd6381357d5942e1d5e326df1edbbb8feadc)
> CFE-3284/3.15.x: Added zypper as default package manager for opensuse

- cfe_internal/update/update_policy.cf
- lib/packages.cf
- promises.cf.in
Ticket: CFE-3284
(cherry picked from commit e4c4bd6381357d5942e1d5e326df1edbbb8feadc)
> CFE-3284/3.12.x: Added zypper as default package manager for opensuse

- cfe_internal/enterprise/federation/federation.cf
> Fixed a typo in vars report for FR selinux policy

- cfe_internal/CFE_cfengine.cf
> CFE-3305/master: Fixed typo preventing recommendation bundles from running

- cfe_internal/CFE_cfengine.cf
> CFE-3305/3.12.x: Fixed typo preventing recommendation bundles from running

- MPF.md
> CFE-3307/master: Fixed invalid example setting input_name_patterns via augments

- MPF.md
> CFE-3307/3.12.x: Fixed invalid example setting input_name_patterns via augments

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-4715/master: Stopped continual repair of ha_enabled semaphore

- cfe_internal/enterprise/CFE_knowledge.cf
> Changed path to scripts from docroot to public_docroot

- cfe_internal/update/update_policy.cf
- modules/packages/Makefile.am
Since now they are managed by masterfiles.
#
> CFE-3237 Copy modules from masterfiles to workdir on hub during update

- controls/reports.cf
> ENT-5531/master: Admitted ::1 as a query source on Enterprise hubs

- cfe_internal/update/update_policy.cf
- modules/packages/Makefile.am
> CFE-3237 Update modules from masterfiles

- lib/cfe_internal_hub.cf
> Deleted deprecated __PromiseExecutionsLog from process that cleans log tables

- cfe_internal/enterprise/templates/httpd.conf.mustache
Changed global DocumentRoot to public_docroot
Ticket: ENT-5580
> Fixed broken redirect from http to htttps

- cfe_internal/core/main.cf
So that we know the ability to limit this is important, I added a reference to
the public ticket as a stakeholder/promisee.
Ticket: CFE-1799
----
#
> CFE-1799/master: Added cross reference to promise

- lib/bundles.cf
- lib/cfe_internal_hub.cf
- lib/feature.cf
- lib/files.cf
- lib/services.cf
- lib/vcs.cf
Ticket: CFE-3378
(cherry picked from commit 3987b9d8a4ab019c15e1ea67c6115094d7fdfdee)
> CFE-3378/3.15.x: Replaced @ignore with useful doc strings

- lib/bundles.cf
- lib/cfe_internal_hub.cf
- lib/feature.cf
- lib/files.cf
- lib/services.cf
- lib/vcs.cf
Ticket: CFE-3378
(cherry picked from commit 3987b9d8a4ab019c15e1ea67c6115094d7fdfdee)
> CFE-3378/3.12.x: Replaced @ignore with useful doc strings

- inventory/any.cf
> ENT-6115 Added check for aws ec2 metadata content to make CI more reliable

- lib/files.cf
> ENT-6117/master: Added history for backport of replace_uncommented_substrings

- inventory/any.cf
merge with https://github.com/cfengine/nova/pull/1705
> ENT-6161/master: Added inventory for Timezone and GMT Offset

- inventory/any.cf
Merge together: https://github.com/cfengine/nova/pull/1706
Ticket: ENT-6161
(cherry picked from commit fe228f485bd884a65621fa93a581f7c3c3eea383)
> Added inventory for Timezone and GMT Offset

- lib/paths.cf
> Added ability to extend known paths without modifying vendored policy

- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
> ENT-6082 disable [local-]updates-list-cached tests on deb7 and solaris11

- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
(cherry picked from commit c4ced8e23bc55722b252def2233bbdd6d1df60e0)
----
#
> ENT-6082 disable *-updates-list-cached test on deb7 and solaris11 - 3.12.x

- inventory/any.cf
Merge with: https://github.com/cfengine/mission-portal/pull/1229
> ENT-6212/master: Added inventory for policy servers

- lib/packages.cf
- modules/packages/apk
- promises.cf.in
Note that repo-install and file-install API methods do not support multiple
packages. This should not affect most usage of this module.
Ticket: CFE-3451
> CFE-3451 Added apk package module support for alpinelinux

- inventory/any.cf
Merge together: https://github.com/cfengine/mission-portal/pull/1236
Ticket: ENT-6212
(cherry picked from commit efa1204c4b3b16332695358417a99b80758aae64)
> ENT-6212/3.15.x: Added inventory for policy servers

- inventory/any.cf
Merge together: https://github.com/cfengine/mission-portal/pull/1237
Ticket: ENT-6212
(cherry picked from commit efa1204c4b3b16332695358417a99b80758aae64)
> ENT-6212/3.12.x: Added inventory for policy servers

- cfe_internal/enterprise/CFE_hub_specific.cf
Ticket: ENT-6228
Merge together: 
https://github.com/cfengine/mission-portal/pull/1248
https://github.com/cfengine/nova/pull/1734
> Added maintenance policy to update health diagnostics failures table on enterprise hubs

- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/httpd.conf.mustache
> Added redirect to remove index.php from Mission Portal's URL

- promises.cf.in
```
-Copyright 2020 Northern.tech AS
+Copyright 2021 Northern.tech AS
```
> Updated copyright headers to 2021

- lib/files.cf
> CFE-3541/master: Fixed docs describing xdev behavior in depth_search bodies

- lib/files.cf
Ticket: CFE-3541
(cherry picked from commit a22818aef2315e732b0969fbabe27b981c1608b3)
> CFE-3541/3.15.x: Fixed docs describing xdev behavior in depth_search bodies

- lib/files.cf
Ticket: CFE-3541
(cherry picked from commit a22818aef2315e732b0969fbabe27b981c1608b3)
> CFE-3541/3.12.x: Fixed docs describing xdev behavior in depth_search bodies

- controls/def.cf
> CFE-3546/master: Fixed ability to define users authorized for using cf-runagent on policy servers

- cfe_internal/enterprise/templates/httpd.conf.mustache
> Do not apply redirect from index.php to internal APIs

- inventory/any.cf
merge together: https://github.com/cfengine/nova/pull/1749
Ticket: ENT-6782
> ENT-6782/master: Prevent setgid files from causing continual repair related to setuid file inventory & inventory setgid files

- modules/packages/msiexec-list.vbs
- modules/packages/msiexec.bat
(cherry picked from commit 3c9b5ce0da709b9ed70e7a8c2fcd534e5873505c)
----
#
> ENT-4669 Use VBScript to enumerate installed packages - 3.15.x

- MPF.md
> CFE-3598/master: Added example illustrating definition of services_autorun class

- MPF.md
Ticket: CFE-3598
(cherry picked from commit b009a5f360d3dd97314223a7d5c9d35b783bc67d)
> CFE-3598/3.12.x: Added example illustrating definition of services_autorun class

- lib/cfe_internal_hub.cf
> ENT-6841/master: Added description of psql_lock_wait_before_acquisition measurement

- lib/cfe_internal_hub.cf
Ticket: ENT-6841
(cherry picked from commit 2cb1152d250c3f4988718ea6bb2dcad9f047e2da)
> ENT-6841/3.15.x: Added description of psql_lock_wait_before_acquisition measurement

- modules/packages/Makefile.am
- modules/packages/msiexec-list.vbs
- modules/packages/msiexec.bat
Also required ENT-6814 fix.
Ticket: ENT-4669
> ENT-4669 Use VBScript to enumerate installed packages (3.12.x)

- tests/acceptance/17_packages/12_new/timed/installed-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
> ENT-6939 skip oftten-failing packages tests

- cfe_internal/recommendations.cf
> spelling fix, s/reccommend/recommend/

- CHANGELOG.md
> ENT-4628 Added changelog entry

- README.md
Removed 3.10.x
Ticket: ENT-6713
> ENT-6713 Adjusted badges for 3.18.0 release

- MPF.md
Also added History for when configuration was introduced.
Ticket: ENT-7417
> ENT-7417: Fixed example showing configuration for collecting CPU measurements (master)

- MPF.md
Also added History for when configuration was introduced.
Ticket: ENT-7417
(cherry picked from commit d4d95f280e50a907552e562226a67e90075497b4)
> ENT-7417: Fixed example showing configuration for collecting CPU measurements (3.18)

- MPF.md
Also added History for when configuration was introduced.
Ticket: ENT-7417
(cherry picked from commit d4d95f280e50a907552e562226a67e90075497b4)
> ENT-7417: Fixed example showing configuration for collecting CPU measurements (3.15)

- MPF.md
Also added History for when configuration was introduced.
Ticket: ENT-7417
(cherry picked from commit d4d95f280e50a907552e562226a67e90075497b4)
> ENT-7417: Fixed example showing configuration for collecting CPU measurements (3.12)

- templates/README.md
- templates/cf-apache.service.mustache
- templates/cf-execd.service.mustache
- templates/cf-hub.service.mustache
- templates/cf-monitord.service.mustache
- templates/cf-postgres.service.mustache
- templates/cf-serverd.service.mustache
https://github.com/cfengine/core/pull/4314
https://github.com/cfengine/masterfiles/pull/1699
> ENT-5125 Synchronized systemd units with core/misc/systemd

- templates/README.md
- templates/cf-apache.service.mustache
- templates/cf-execd.service.mustache
- templates/cf-hub.service.mustache
- templates/cf-monitord.service.mustache
- templates/cf-postgres.service.mustache
- templates/cf-serverd.service.mustache
merge together
https://github.com/cfengine/core/pull/4737
https://github.com/cfengine/masterfiles/pull/2017
> ENT-5125 Synchronized systemd units with core/misc/systemd (3.18.x)

- templates/README.md
- templates/cf-apache.service.mustache
- templates/cf-execd.service.mustache
- templates/cf-hub.service.mustache
- templates/cf-monitord.service.mustache
- templates/cf-postgres.service.mustache
- templates/cf-serverd.service.mustache
merge together
https://github.com/cfengine/core/pull/4737
https://github.com/cfengine/masterfiles/pull/2018
> ENT-5125 Synchronized systemd units with core/misc/systemd (3.15.x)

- cfe_internal/update/update_policy.cf
> CFE-3721 Skip ownership of package modules on termux

- modules/promises/cfengine.py
> Added custom promise python library

- Makefile.am
- modules/promises/cfengine.sh
- tests/acceptance/30_custom_promise_types/05_cp_using_library.cf
- tests/acceptance/30_custom_promise_types/06_cp_with_classes.cf
- tests/acceptance/30_custom_promise_types/07_python_library.cf
- tests/acceptance/30_custom_promise_types/08_slist_attrs.cf
- tests/acceptance/30_custom_promise_types/09_log_level.cf
- tests/acceptance/30_custom_promise_types/09_log_level.cf.sub
- tests/acceptance/30_custom_promise_types/10_log_level_bad_module.cf
- tests/acceptance/30_custom_promise_types/10_log_level_bad_module.cf.sub
- tests/acceptance/30_custom_promise_types/16_data_attrs.cf
- tests/acceptance/30_custom_promise_types/19_different_promise_types.cf
- tests/acceptance/30_custom_promise_types/copy_always_info.py
- tests/acceptance/30_custom_promise_types/copy_promises.py
- tests/acceptance/30_custom_promise_types/cp-with-classes.sh
- tests/acceptance/30_custom_promise_types/cp.sh
- tests/acceptance/30_custom_promise_types/json_insert.py
- tests/acceptance/30_custom_promise_types/multiline_insert.py
- tests/acceptance/Makefile.am
https://github.com/cfengine/core/pull/4771
> CFE-3628 Move bash and python CPT libraries and tests from core

- Makefile.am
- modules/promises/cfengine.py
- modules/promises/cfengine.sh
- tests/acceptance/30_custom_promise_types/05_cp_using_library.cf
- tests/acceptance/30_custom_promise_types/06_cp_with_classes.cf
- tests/acceptance/30_custom_promise_types/07_python_library.cf
- tests/acceptance/30_custom_promise_types/08_slist_attrs.cf
- tests/acceptance/30_custom_promise_types/09_log_level.cf
- tests/acceptance/30_custom_promise_types/09_log_level.cf.sub
- tests/acceptance/30_custom_promise_types/10_log_level_bad_module.cf
- tests/acceptance/30_custom_promise_types/10_log_level_bad_module.cf.sub
- tests/acceptance/30_custom_promise_types/16_data_attrs.cf
- tests/acceptance/30_custom_promise_types/19_different_promise_types.cf
- tests/acceptance/30_custom_promise_types/copy_always_info.py
- tests/acceptance/30_custom_promise_types/copy_promises.py
- tests/acceptance/30_custom_promise_types/cp-with-classes.sh
- tests/acceptance/30_custom_promise_types/cp.sh
- tests/acceptance/30_custom_promise_types/json_insert.py
- tests/acceptance/30_custom_promise_types/multiline_insert.py
- tests/acceptance/Makefile.am
merge together: https://github.com/cfengine/core/pull/4791
> CFE-3628 Move bash and python CPT libraries and tests from core - 3.18.x

- MPF.md
> CFE-3775: Added cross reference to packagesmatching functions from MPF tunables

- MPF.md
Ticket: CFE-3775
(cherry picked from commit 67a8bf15da8d217fbfc1545b46eed83b10251348)
> CFE-3775: Added cross reference to packagesmatching functions from MPF tunables (3.15)

- inventory/redhat.cf
Ticket: ENT-7628
(cherry picked from commit 89650d51a9b24fad6724d106022558cd425b87b7)
> ENT-7628: Fixed backwards compatibility to 3.15.x (3.15)

- inventory/redhat.cf
> ENT-7628: Fixed backwards compatibility to 3.15.x

- inventory/redhat.cf
Ticket: ENT-7628
(cherry picked from commit 89650d51a9b24fad6724d106022558cd425b87b7)
> ENT-7628: Fixed backwards compatibility to 3.15.x (3.18)

- cfbs/cleanup.sh
> CFE-3781: Added script to cleanup artifacts after cfbs build

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/cfsecret.py
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/distributed_cleanup.py
- templates/federated_reporting/nova_api.py
- templates/federated_reporting/pull_dumps_from.sh
- templates/federated_reporting/transfer_distributed_cleanup_items.sh
> ENT-7215 Added distributed_cleanup utility for Federated Reporting (3.18)

- templates/cf-apache.service.mustache
> ENT-7948: Set apache umask to 0177

- templates/cf-apache.service.mustache
Ticket: ENT-7948
(cherry picked from commit 52d60cf3a046ba807b03a9c7bbde5368e3faf178)
> ENT-7948: Set apache umask to 0177 (3.18)

- templates/cf-apache.service.mustache
Ticket: ENT-7948
(cherry picked from commit 52d60cf3a046ba807b03a9c7bbde5368e3faf178)
> ENT-7948: Set apache umask to 0177 (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-7966
(cherry picked from commit 9b16bd1b8325ad48ee898ac2a7f8b11d6f17be9f)
> ENT-7966: Fixed path to httpd.pid (3.15)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-7966
(cherry picked from commit 9b16bd1b8325ad48ee898ac2a7f8b11d6f17be9f)
> ENT-7966: Fixed path to httpd.pid (3.18)

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-7966: Fixed path to httpd.pid

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-7961: Enforced permissions for Postgres log

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-7961: Enforced permissions for Postgres log (3.18)

- cfe_internal/enterprise/CFE_knowledge.cf
Ticket: ENT-7961
(cherry picked from commit 5e4b80aafc787ff934a8d11a98ae2b4f06fbc9d6)
> ENT-7961: Enforced permissions for Postgres log (3.15)

- CHANGELOG.md
> Updated changelogs for 3.18.1 release

- CHANGELOG.md
> Added changelog entry for ENT-8065 (3.18)

- CHANGELOG.md
> Added changelog for ENT-8065 (3.15)

- tests/acceptance/17_packages/12_new/timed/installed-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/local-updates-list-cached.cf
- tests/acceptance/17_packages/12_new/timed/test_module
- tests/acceptance/17_packages/12_new/timed/updates-list-cached.cf
> ENT-6966 Re-enabled *-list-cached tests

- templates/federated_reporting/import.sh
Feeder dump files have in their name the hostkey of the feeder.
If this hostkey is not present in the __hubs table then skip
that dump file and log a warning recommending either to delete
the file or add the feeder to superhub.
Ticket: ENT-8229
> ENT-8229 Skip invalid feeder dump files during import

- templates/federated_reporting/import.sh
Feeder dump files have in their name the hostkey of the feeder.
If this hostkey is not present in the __hubs table then skip
that dump file and log a warning recommending either to delete
the file or add the feeder to superhub.
Ticket: ENT-8229
(cherry picked from commit ad83552cec64b507251422b692d49f669d56a069)
> ENT-8229 Skip invalid feeder dump files during import (3.15)

- templates/federated_reporting/import.sh
Feeder dump files have in their name the hostkey of the feeder.
If this hostkey is not present in the __hubs table then skip
that dump file and log a warning recommending either to delete
the file or add the feeder to superhub.
Ticket: ENT-8229
(cherry picked from commit ad83552cec64b507251422b692d49f669d56a069)
> ENT-8229 Skip invalid feeder dump files during import (3.18)

- cfe_internal/enterprise/federation/federation.cf
> Truncate FR dabase settings when a feeder is off

- lib/paths.cf
Ticket: None
Signed-off-by: larsewi <lars.erik.wik@northern.tech>
> Added prelink to paths.cf

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-8280 Enforce proper owner and perms on docroot

- prepare.sh
To avoid the ton of noise when running 'cf-agent -KIf update.cf'
the first time after 'cfbs install'.
Ticket: CFE-3872
> Change permissions of files and dirs in prepare.sh

- cfe_internal/enterprise/federation/federation.cf
> ENT-8294 Only run clean_when_off FR bundle on FR hubs

- .travis.yml
- travis-scripts/valgrind.sh
(cherry picked from commit c4ba485c83144ab453fb3f009aa1e1d4f5c958b0)
> Fixed Travis failure 'E: Unable to locate package python3.6' (3.18.x)

- .travis.yml
- travis-scripts/valgrind.sh
(cherry picked from commit c4ba485c83144ab453fb3f009aa1e1d4f5c958b0)
> Fixed Travis failure 'E: Unable to locate package python3.6' (3.15.x)

- templates/federated_reporting/import.sh
> Fixed psql not found while FR import

- templates/federated_reporting/import.sh
Ticket: ENT-8353
(cherry picked from commit 9e0601ae87951fafe8b7337edf8c2fb94b40dd63)
> Fixed psql not found while FR import (3.15.x)

- templates/federated_reporting/import.sh
Ticket: ENT-8353
(cherry picked from commit 9e0601ae87951fafe8b7337edf8c2fb94b40dd63)
> Fixed psql not found while FR import (3.18.x)

- modules/packages/vendored/pkg.mustache
Originally proposed in https://github.com/cfengine/masterfiles/pull/1886 by @gpiero (Thank you!).
I altered the commit messages to align with our CONTRIBUTING guidelines.
This PR supersedes https://github.com/cfengine/masterfiles/pull/1886
> CFE-3568: Various fix-ups for FreeBSD pkg module (master)

- cfe_internal/enterprise/CFE_knowledge.cf
Ticket: ENT-8280
(cherry picked from commit 47ed8015f6806c67b3d37d8afee80f9f792978c8)
> ENT-8280 Enforce proper owner and perms on docroot (3.15)

- LICENSE
- m4/cf3_platforms.m4
- modules/packages/vendored/zypper.mustache
- promises.cf.in
- tests/acceptance/testall
This one was done manually, just a few files.
> Updated copyright notices to 2022

- templates/federated_reporting/distributed_cleanup.py
> Add hub interactively in distributed-cleanup.py

- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/distributed_cleanup.py
> ENT-8611/ENT-8979 Fixed and enabled testing of distributed cleanup utility (3.18)

- tests/acceptance/lib/files/set_line_based-ENT-5866.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf.expected-result
> Fix location of the expected result of the set_line_based test

- lib/files.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf.expected-result
- tests/acceptance/lib/files/set_line_based-ENT-5866.cf.start
Backports of #2430  and #2433.
> [3.18.x] set_line_based() fixes

- cfe_internal/update/update_policy.cf
Thanks to Alex Song for reporting this.
Ticket: ENT-9056
> ENT-9056 Renamed body depth_search u_infinate_client_policy to u_infinite_client_policy

- .github/workflows/style_check.yml
> ENT-9189: Added style check github action

- .github/workflows/style_check.yml
Ticket: ENT-9189
(cherry picked from commit 6658ac413f6e0cb17d3b751325bc3b8833f2228a)
> ENT-9189: Added style check github action (3.18)

- .github/workflows/style_check.yml
Ticket: ENT-9189
(cherry picked from commit 6658ac413f6e0cb17d3b751325bc3b8833f2228a)
> ENT-9189: Added style check github action (3.15)

- .github/workflows/ci.yml
Will need to figure out how to make a PR refer to changed yml files
> ENT-9162: Fix github actions ci references

- .github/workflows/ci.yml
> ENT-9162: Fixed path to github workflows

- standalone_self_upgrade.cf.in
> ENT-9210: Added self upgrade knowledge for debian 11

- .github/workflows/ci.yml
- .github/workflows/style_check.yml
- .github/workflows/tests.yml
- tests/acceptance/testall
> ENT-9162: Added acceptance tests and job dependencies (3.18)

- .github/workflows/ci.yml
- .github/workflows/style_check.yml
- .github/workflows/tests.yml
- tests/acceptance/testall
> ENT-9162: Added acceptance test and job dependencies (3.15)

- templates/cf-serverd.service.mustache
Reflecting the changes from https://github.com/cfengine/core/commit/962bac57c2af.
https://github.com/cfengine/core/pull/5045
https://github.com/cfengine/masterfiles/pull/2485
> ENT-8456: Adapt the cf-serverd.service template to the version from core

- controls/cf_execd.cf
> ENT-8107: Removed stale reference to cf-twin

- CHANGELOG.md
> ENT-9573: Manually added changelog entry (3.18)

- cfe_internal/update/cfe_internal_dc_workflow.cf
- cfe_internal/update/cfe_internal_update_from_repository.cf
> ENT-9625: Stopped applying locks to masterfiles-stage

- cfe_internal/enterprise/mission_portal.cf
- cfe_internal/enterprise/templates/httpd.conf.mustache
Otherwise cf-agent might not find it
Ticket: ENT-9603
> Use absolute path to httpd.pid

- cfe_internal/enterprise/CFE_knowledge.cf
> ENT-9693: Added policy to enforce proper permissions on Mission Portal ldap directory

- cfe_internal/enterprise/CFE_knowledge.cf
Ticket: ENT-9665
https://github.com/cfengine/buildscripts/pull/1179
https://github.com/cfengine/masterfiles/pull/2562
> ENT-9665: Added /opt/cfengine/build ownership and permissions promises

- cfe_internal/enterprise/CFE_knowledge.cf
Reverts cfengine/masterfiles#2562
> Revert "ENT-9665: Added /opt/cfengine/build ownership and permissions promises"

- MPF.md
- controls/cf_execd.cf
- controls/def.cf
> ENT-9614: Made body maxmaillines in body executor control configurable via Augments

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
Ticket: ENT-9196
fake together for testing workflows: https://github.com/cfengine/core/pull/5214, the together javascript action won't know any better and will include the PR anyhow.
> ENT-9196: Added together action to support multi-repo github workflows

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
Ticket: ENT-9196
(cherry picked from commit f3627ae1dbbcb41064cb22edd7bfaf0d4f1934da)
> ENT-9196: Added together action to support multi-repo github workflows (3.18)

- .github/workflows/ci.yml
- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
Ticket: ENT-9196
(cherry picked from commit f3627ae1dbbcb41064cb22edd7bfaf0d4f1934da)
> ENT-9196: Added together action to support multi-repo github workflows (3.21)

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
> ENT-10190: Upgraded together javascript action

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
Ticket: ENT-10190
(cherry picked from commit 83af8925be3e423e9e102b823c2277b54f19e9c8)
> ENT-9196: Upgraded together javascript action (3.18)

- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
Ticket: ENT-10190
(cherry picked from commit 83af8925be3e423e9e102b823c2277b54f19e9c8)
> ENT-9196: Upgraded together javascript action (3.21)

- inventory/any.cf
Dyslexia FTL! I had entered the wrong ticket number, this simply fixes my mistake.
> ENT-9806: Fixed stakeholder on policy version inventory promise

- inventory/any.cf
Dyslexia FTL! I had entered the wrong ticket number, this simply fixes my mistake.
> ENT-9806: Fixed stakeholder on policy version inventory promise (3.21)

- inventory/any.cf
Dyslexia FTL! I had entered the wrong ticket number, this simply fixes my mistake.
(cherry picked from commit 225577e11d224c6388d9f86865d639d16ee22739)
> ENT-9806: Fixed stakeholder on policy version inventory promise (3.18)

- standalone_self_upgrade.cf.in
> ENT-10335: Added support for RockyLinux in self upgrade

- prepare.sh
These changes align the result from cfbs build with the masterfiles package
tarball artifact built during release.
Ticket: ENT-10345
> ENT-10345: Aligned masterfiles module build steps with release tarball

- standalone_self_upgrade.cf.in
Ticket: ENT-10335
(cherry picked from commit f4503293099fe0528feb32222d3ec3a95b5b13d9)
> ENT-10335: Added support for RockyLinux in self upgrade (3.21)

- standalone_self_upgrade.cf.in
Ticket: ENT-10335
(cherry picked from commit f4503293099fe0528feb32222d3ec3a95b5b13d9)
> ENT-10335: Added support for RockyLinux in self upgrade (3.18)

- promises.cf.in
(cherry picked from commit ca5cbc6c5e5b4c87a63a9a1eeb7438d27f3dbccc)
> Fix indentation in promises.cf.in (3.21)

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
Ticket: ENT-10212
(cherry picked from commit db9e398bb9c1bb1c64ff3f9f649166f7716b1084)
> ENT-10212: Made allowconnects and allowallconnects configurable via Augments (3.21)

- MPF.md
- controls/cf_serverd.cf
- controls/def.cf
Ticket: ENT-10212
(cherry picked from commit db9e398bb9c1bb1c64ff3f9f649166f7716b1084)
> ENT-10212: Made allowconnects and allowallconnects configurable via Augments (3.18)

- lib/paths.cf
> ENT-10413: Added ss to paths for linux

- lib/paths.cf
Ticket: ENT-10413
(cherry picked from commit a5c35b13cd133158c8ccee6a19d4d71e53b07371)
> ENT-10413: Added ss to paths for linux (3.21)

- lib/paths.cf
Ticket: ENT-10413
(cherry picked from commit a5c35b13cd133158c8ccee6a19d4d71e53b07371)
> ENT-10413: Added ss to paths for linux (3.18)

- MPF.md
- cfe_internal/enterprise/templates/httpd.conf.mustache
- controls/def.cf
Ticket: ENT-10412
(cherry picked from commit 07d4bf76c2357cc6f20958e3908cd28af58f5f3d)
> ENT-10412: Made Mission Portal Apache SSLProtocol configurable via augments (3.21)

- MPF.md
> ENT-10480: Updated history for ability to extend input_name_patterns (3.21)

- .github/workflows/tests.yml
> ENT-10667: Adjust acceptance test job for non-master branches (3.18)

- CHANGELOG.md
> Added missing changelog entry

- .github/workflows/tests.yml
Ticket: ENT-10667
(cherry picked from commit c8af56be04a4f22742ac4651d034b1cb0b87a8a9)
> ENT-10667: Adjust acceptance test job for non-master branches (3.21)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
- templates/federated_reporting/config.sh.mustache
- templates/federated_reporting/import.sh
- Improved failure logging during federated reporting schema import
- Added debug_import class for federated reporting import debugging
> ENT-10921: Improved failure logging during federated reporting schema import (3.21)

- MPF.md
Ticket: ENT-10921
(cherry picked from commit 0bdd46e8734c471b7a1ee55ff33289794d415527)
> ENT-10921: Added cherry picked versions for improved federated reporting debugging augment (3.21)

- MPF.md
Ticket: ENT-10921
(cherry picked from commit 0bdd46e8734c471b7a1ee55ff33289794d415527)
> ENT-10921: Added cherry picked versions for improved federated reporting debugging augment (3.18)

- MPF.md
- cfe_internal/enterprise/federation/federation.cf
> ENT-10900: Made enterprise federated reporting dump interval configurable via Augments

- MPF.md
(cherry picked from commit 4d3d024783f8b664e88419569a6bbc697ec2a917)
> ENT-10900: Updated versions for dump_interval history (3.18)

- MPF.md
(cherry picked from commit 4d3d024783f8b664e88419569a6bbc697ec2a917)
> ENT-10900: Updated versions for dump_interval history (3.21)

- cfe_internal/enterprise/federation/federation.cf
Needs #2816 to be merged first. Adds one more commit that makes bigger changes in the policy, probably too disruptive for backporting.
> Follow up for FR SSH SELinux context fixes

- cfe_internal/enterprise/federation/federation.cf
> [3.18.x] FR SELinux fixes

- cfe_internal/enterprise/federation/federation.cf
> [3.21.x] FR SELinux fixes

- CHANGELOG.md
Relates to:
- https://github.com/cfengine/enterprise/pull/783
- https://github.com/cfengine/core/pull/5407
> ENT-11083: Added changelog for 3.21.4

- CHANGELOG.md
Relates to:
- https://github.com/cfengine/enterprise/pull/782
- https://github.com/cfengine/core/pull/5406
> ENT-11034: Added changelog for 3.18.7

- cfe_internal/recommendations.cf
> ENT-8785: Added recommendation for installing gnu parallel on federated reporting superhubs

- inventory/any.cf
Ticket: ENT-10988
(cherry picked from commit d9978725c64dcfcc395e2cc9ccea0a2f68369dd8)
> ENT-10988: Refactored AWS IMDS retrieval to support both IMDSv1 and IMDSv2 (3.21)

- CHANGELOG.md
- MPF.md
Merge together: https://github.com/cfengine/documentation/pull/3228
> ENT-11371 MPF.md: Fixed many inconsistencies (3.21)

- MPF.md
Found while working on:
https://github.com/cfengine/masterfiles/pull/2836
> MPF.md: Forward-ported changes from 3.21.x

- MPF.md
(cherry picked from commit a9ced082f945956a0d302154b66a2432f9f93c37)
> Fixed link reference to mailmaxlines (3.21)

- MPF.md
- cfe_internal/enterprise/templates/httpd.conf.mustache
- controls/def.cf
> ENT-11393: Added ability to configure SSLCipherSuite via Augments

- MPF.md
- cfe_internal/enterprise/CFE_hub_specific.cf
- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-11421: Added ability to configure Mission Portal Apache SSLCACertificateFile via Augments

- MPF.md
- lib/packages.cf
- promises.cf.in
- Added ability to influence default package manager and inventory via Augments
- Added freebsd package_module and package_inventory since we have pkg packages module available
> CFE-4345: Added freebsd package_module and package_inventory since we have packages module available (3.18)

- MPF.md
- lib/packages.cf
- promises.cf.in
- Added ability to influence default package manager and inventory via Augments
- Added freebsd package_module and package_inventory since we have pkg packages module available
> CFE-4345: Added freebsd package_module and package_inventory since we have pkg packages module available (3.21)

- MPF.md
Added ability to influence default package manager and inventory via Augments
Ticket: CFE-3612
> CFE-3612: Update version introduced for commit 87292179415a0d4770281715a850ef49d2991842

- lib/files.cf
This change simply aims to fix links in the rendered documentation.
> Updated see also references

- lib/vcs.cf
> CFE-4375: Refactored extraction of home directory from parsing getent output to getuserinfo()

- MPF.md
> ENT-11570: Added documentation for customizing domain via Augments

- MPF.md
> ENT-11569: Added documentation for mailto, mailfrom, smtpserver and maxmaillines

- MPF.md
Ticket: ENT-11569
(cherry picked from commit d1c96a744f6e5af8ab1853a46a6abc5688dfbec4)
> ENT-11569: Added documentation for mailto, mailfrom, smtpserver and maxmaillines (3.18)

- MPF.md
Ticket: ENT-11570
(cherry picked from commit c630d037dbcbde55606ee3c0760f6f86711175ec)
> ENT-11570: Added documentation for customizing domain via Augments (3.18)

- MPF.md
- controls/cf_execd.cf
- services/autorun/README.md
* Fix typo maximumm -> maximum, maxmaillines -> mailmaxlines
* Fix links
* Add documentation for configuring mailmaxlines via augment
> Fix some documentation issues

- services/autorun/README.md
> ENT-11807: Fixed link target for Adding additional policy files for update inputs

- .github/workflows/bootstrap_policy_run_check.yml
- .github/workflows/style_check.yml
- .github/workflows/tests.yml
- .github/workflows/valgrind.yml
- **GH Actions: Upgraded to Ubuntu 22**
- **GH Actions: Upgraded checkout action to v4**
> GH Actions: Upgraded versions of Ubuntu and checkout action

- cfe_internal/recommendations.cf
Just trying to improve the experience understanding what to do about psql
recommendations.
> Improved human readability for psql recommendations

- modules/packages/vendored/nimclient.mustache
> CFE-4415: Fix shell typo in nimclient module script

- cfe_internal/enterprise/templates/httpd.conf.mustache
> ENT-11421: Fixed inverted condition for use of SSLCACertificateFile

- .github/workflows/ci.yml
> ENT-11734: Update branches to test against with new LTS: master, 3.24.x and 3.21.x

- cfe_internal/enterprise/templates/httpd.conf.mustache
Signed-off-by: Mikita Pilinka <mikita.pilinka@northern.tech>
> ENT-11472: Added CSP HTTP Header to Mission Portals apache config

- cfe_internal/enterprise/templates/httpd.conf.mustache
> Changed Mission Portal's CSP to support data url images

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-12010
together
https://github.com/cfengine/mission-portal/pull/2563
https://github.com/cfengine/masterfiles/pull/2939
> Adjusted CSP in httpd.conf to suit ACE javascript editor

- .github/workflows/ci.yml
Ticket: ENT-11734
(cherry picked from commit ed7a8347a2160bfbf84710378de84ee0bbc2c2cf)
> Update branches to test against with new LTS: master, 3.24.x and 3.21.x (3.24)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit e2d08e94c3696bdd8e7b69a15ec2d910f3d6176a)
> Changed Mission Portal's CSP to support data url images (3.24.x)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-12010
(cherry picked from commit 65f36c1a97b6176265bb8750076b010aedc29817)
> Adjusted CSP in httpd.conf to suit ACE javascript editor (3.24.x)

- cfe_internal/enterprise/templates/httpd.conf.mustache
Ticket: ENT-12010
(cherry picked from commit 65f36c1a97b6176265bb8750076b010aedc29817)
> Adjusted CSP in httpd.conf to suit ACE javascript editor (3.21)

- MPF.md
- lib/feature.cf
- lib/services.cf
(cherry picked from commit 12a01fcf0710d77e01ad20c7800aaf3dcae5118a)
> Fix typo and some formatting issues (3.24)

- MPF.md
- lib/feature.cf
- lib/services.cf
(cherry picked from commit 12a01fcf0710d77e01ad20c7800aaf3dcae5118a)
> Fix typo and some formatting issues (3.21)

- README.md
> Fixed tiny typo in README: policy /for/ installations

- inventory/linux.cf
Ticket: CFE-3429
Signed-off-by: Craig Comstock <craig.comstock@northern.tech>
> Use current process ID to investigate proc filesystem to workaround in-container non-root owned symlinks

- .github/workflows/tests.yml
> Tidied up some not needed steps in tests workflow

- .github/workflows/tests.yml
Ticket: none
(cherry picked from commit 02e3a7a7d4e70cbd424db8834bc51f58a052fd63)
> Tidied up some not needed steps in tests workflow (3.24)

- controls/def.cf
Reverts cfengine/masterfiles#2969
> Revert "CFE-2528: Changed the default for allowallconnects"

- CHANGELOG.md
Ticket: ENT-12842
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
> ENT-12842: Updated CHANGELOG.md for 3.24.2 (3.24.x)

- lib/paths.cf
> ENT-12988: Added dmidecode to well known paths for Red Hat

- standalone_self_upgrade.cf.in
I patched this in my MPF and it has been working fine.
> Added Ubuntu 24.04 and Debian 12 to standalone_self_upgrade.

- standalone_self_upgrade.cf.in
> CFE-4573: Added Ubuntu 24.04 and Debian 12

- cfe_internal/recommendations.cf
- inventory/linux.cf
> Inventory Unique NFS Servers and Recommend consistency in definition

- controls/def.cf
> CFE-4588: Fixed duplicate bundlesequence_end when bundlesequence_classification not defined (3.21)
